var stops = {
"0001": {"id": "VLRMGHN", "verbose": "Valerie and Meaghan"},
"0002": {"id": "MCNLYERKA", "verbose": "McKinley and Eureka"},
"0005": {"id": "TCBTGT", "verbose": "Town Center Blvd at Target"},
"0021": {"id": "BLOMPNR", "verbose": "Bloomington Rd. at Pioneer Plaza"},
"0055": {"id": "WSFLDWLM", "verbose": "Westfield and William"},
"0062": {"id": "MHRYADRSN", "verbose": "McHenry and Anderson"},
"0063": {"id": "RLNDAZTEC", "verbose": "Roland and Aztec"},
"0066": {"id": "PLAKIRK", "verbose": "Paula and Kirk Lane"},
"0067": {"id": "CFDCAMP", "verbose": "Country Fair Dr. and Camp"},
"0074": {"id": "STEPK", "verbose": "State and Park"},
"0076": {"id": "WNCHTMRK", "verbose": "Winchester and Tamarack"},
"0100": {"id": "IU", "verbose": "Illini Union"},
"0101": {"id": "LSE", "verbose": "Lincoln Square"},
"0102": {"id": "CLTNCRVCR", "verbose": "Clayton and Creve Coeur"},
"0112": {"id": "LNCLNVT", "verbose": "Lincoln and Vermont"},
"0113": {"id": "FLKNCH", "verbose": "Florida and Kinch"},
"0114": {"id": "SLYBKDOD", "verbose": "Slayback and Dodson West"},
"0127": {"id": "UWALMART", "verbose": "Urbana WalMart"},
"0142": {"id": "MYRARGPK", "verbose": "Myra Ridge and Ridge Park"},
"0144": {"id": "MKTPLCN", "verbose": "Market Place North Entrance"},
"0153": {"id": "6THPDY", "verbose": "Sixth and Peabody"},
"0156": {"id": "GDWNCB", "verbose": "Goodwin at Ceramics Building"},
"0173": {"id": "WDFLDCTS", "verbose": "Woodfield and Curtis Road"},
"0202": {"id": "MKTMKTV", "verbose": "Market and Marketview"},
"0206": {"id": "CTGRVDE", "verbose": "Cottage Grove and Delaware"},
"0211": {"id": "ADRSNELIOT", "verbose": "Anderson and Eliot"},
"0212": {"id": "NWTNNWMK", "verbose": "Newton and Newmark"},
"0213": {"id": "UNIAVE", "verbose": "University Avenue Mid Block"},
"0215": {"id": "BRDNTLSN", "verbose": "Bardeen and Toalson"},
"0217": {"id": "PKLNCTBRAD", "verbose": "Parkland Ct. and Bradley"},
"0223": {"id": "CHCHPSPCT", "verbose": "Church and Prospect"},
"0226": {"id": "PADNR", "verbose": "Pennsylvania and Dorner"},
"0231": {"id": "SWTCHGRSTRLWY", "verbose": "Switchgrass and Trailway"},
"0233": {"id": "WNDSRMLKN", "verbose": "Windsor and Mullikin"},
"0235": {"id": "STEBRD", "verbose": "State and Beardsley"},
"0240": {"id": "WNCHSMC", "verbose": "Winchester and Sumac"},
"0241": {"id": "CRSNTROD", "verbose": "Crescent and Rodney"},
"0243": {"id": "FRLNCTGRV", "verbose": "Fairlawn and Cottage Grove"},
"0245": {"id": "MIKNCH", "verbose": "Michigan and Kinch"},
"0256": {"id": "RNDLFSTNAG", "verbose": "Randolph and Stanage"},
"0265": {"id": "CTSMDWBRTN", "verbose": "Curtis Meadow and Brighton"},
"0270": {"id": "JOHNNEW", "verbose": "John and New"},
"0303": {"id": "SCWDCACT", "verbose": "Scottswood and Calif. Ct."},
"0311": {"id": "PSPCTASRD", "verbose": "Prospect and Ayrshire Dr."},
"0314": {"id": "PSPCTFRNS", "verbose": "Prospect and Francis"},
"0323": {"id": "BDMRLCNPL", "verbose": "Broadmoor and Lincoln Pl."},
"0327": {"id": "VINBRKNS", "verbose": "Vine and Brookens"},
"0331": {"id": "KBYWAVE", "verbose": "Kirby and Waverly"},
"0333": {"id": "SOLO", "verbose": "Solo Cup"},
"0334": {"id": "PMNADSK", "verbose": "Pomona and Deske Ct."},
"0336": {"id": "VINSRTS", "verbose": "Vine and Shurts"},
"0338": {"id": "ITMKT", "verbose": "Illinois Terminal at Market St."},
"0342": {"id": "1STHZLWD", "verbose": "First and Hazelwood"},
"0344": {"id": "ANTHYRK", "verbose": "Anthony at Rural King"},
"0347": {"id": "CFS", "verbose": "Country Fair South Entrance"},
"0352": {"id": "BDMRGLN", "verbose": "Broadmoor and Galen"},
"0353": {"id": "JMS", "verbose": "Jefferson Middle School"},
"0356": {"id": "KBYDNCN", "verbose": "Kirby and Duncan"},
"0366": {"id": "RACEWASH2", "verbose": "Race and Washington #2"},
"0402": {"id": "MCNLYTRMNT", "verbose": "McKinley and Tremont"},
"0404": {"id": "RNDLFERKA", "verbose": "Randolph and Eureka"},
"0407": {"id": "PSPCTMKTV", "verbose": "Prospect and Marketview"},
"0411": {"id": "DNCNSTNBK", "verbose": "Duncan and Stoneybrook"},
"0414": {"id": "SPFLDWHTN", "verbose": "Springfield and Wheaton"},
"0415": {"id": "WASHCSQR", "verbose": "Washington and Country Squire"},
"0427": {"id": "STLYKBY", "verbose": "Staley and Kirby"},
"0435": {"id": "WDSRCLSL", "verbose": "WIndsor and Carlisle"},
"0436": {"id": "MLKNSTNBDG", "verbose": "Mullikin and Stonebridge"},
"0443": {"id": "RACESWND", "verbose": "Race and Sherwin"},
"0445": {"id": "GRNPINE", "verbose": "Green and Pine"},
"0452": {"id": "UNIELM", "verbose": "University and Elm"},
"0462": {"id": "CCRAPTS", "verbose": "Country Club Rd. at Apts."},
"0463": {"id": "MHRYPND", "verbose": "McHenry and Pond"},
"0466": {"id": "CLTNCSV", "verbose": "Clayton and Crestview"},
"0511": {"id": "RMNBRAD", "verbose": "Romine and Bradley"},
"0513": {"id": "CRSNTRBR", "verbose": "Crescent and Round Barn Road"},
"0522": {"id": "BNTBRKRVRKNL", "verbose": "Bentbrook and Riverknoll"},
"0523": {"id": "STEBRCH", "verbose": "State and Birch"},
"0530": {"id": "GLNYKSH", "verbose": "Galen and Yorkshire"},
"0543": {"id": "KRANNERT", "verbose": "Krannert"},
"0546": {"id": "NEILERKA", "verbose": "Neil and Eureka"},
"0547": {"id": "CTGRVHRDG", "verbose": "Cottage Grove and Harding"},
"0554": {"id": "SCWDNV", "verbose": "Scottswood and Nevada"},
"0560": {"id": "VTKNCH", "verbose": "Vermont and Kinch"},
"0563": {"id": "MPLPKWLM", "verbose": "Maplepark and William"},
"0564": {"id": "ADRSNHTHN", "verbose": "Anderson and Hawthorne"},
"0573": {"id": "WSFLDCRLTN", "verbose": "Westfield and Carrelton"},
"0576": {"id": "WMBGWNTN", "verbose": "Williamsburg and Winston"},
"0595": {"id": "PKLNBDFD", "verbose": "Park Lane and Bedford"},
"0603": {"id": "CBLFLDBDGPT", "verbose": "Cobblefield and Bridge Point Dr"},
"0612": {"id": "HNTRCSQR", "verbose": "Hunter and Country Squire"},
"0613": {"id": "PAAG", "verbose": "Pennsylvania and Ag. Engineering"},
"0623": {"id": "DEPOT", "verbose": "MTD Garage"},
"0626": {"id": "PSPCTBRD", "verbose": "Prospect and Beardsley"},
"0632": {"id": "FLDSFRHL", "verbose": "Fields South and Farhills"},
"0634": {"id": "CPRRDGMLKN", "verbose": "Copper Ridge and Mullikin"},
"0636": {"id": "VINCA", "verbose": "Vine and California"},
"0655": {"id": "WDSRCCS", "verbose": "Windsor at Christie Clinic"},
"0660": {"id": "MNLRMN", "verbose": "Main and Lierman"},
"0662": {"id": "UNIMATS", "verbose": "University and Mattis"},
"0700": {"id": "FOXSTE", "verbose": "Fox Drive and StateSt."},
"0724": {"id": "FRVWGWN", "verbose": "Fairview and Goodwin"},
"0732": {"id": "KBYGDVWW", "verbose": "Kirby and Grandview Dr. W."},
"0735": {"id": "PAPAR", "verbose": "Pennsylvania at PAR"},
"0750": {"id": "JOHNEDWN", "verbose": "John and Edwin"},
"0765": {"id": "MNCHSNT", "verbose": "Main and Chestnut"},
"0787": {"id": "CLTNHLT", "verbose": "Clayton and Hilltop"},
"0795": {"id": "ALPBRAD", "verbose": "Alpine and Bradley"},
"1000": {"id": "1SE14", "verbose": "First and Southeast Lot E-14"},
"1011": {"id": "PSPCTHVD", "verbose": "Prospect and Harvard"},
"1014": {"id": "MN150", "verbose": "Main and Rt. 150"},
"1025": {"id": "PSPCTLOW", "verbose": "Prospect at Lowes"},
"1026": {"id": "PHILOMI", "verbose": "Philo and Michigan"},
"1034": {"id": "SGRPKLNCT", "verbose": "Springer and Parkland Ct."},
"1051": {"id": "BRADWLNT", "verbose": "Bradley and Walnut"},
"1054": {"id": "SSTNJACT", "verbose": "Susan Stone and Jane Ann Ct."},
"1101": {"id": "BRDYGBC", "verbose": "Brady at Grace Baptist Church"},
"1132": {"id": "ADRSNSLVR", "verbose": "Anderson and Silver"},
"1133": {"id": "NEILEGB", "verbose": "Neil and Edgebrook"},
"1134": {"id": "PSPCTPKLN", "verbose": "Prospect and Park Lane"},
"1135": {"id": "LSDMYNRD", "verbose": "Lake Shore Dr. and Maynard"},
"1136": {"id": "BNFLDPKNS", "verbose": "Brownfield and Perkins"},
"1141": {"id": "ONESOUTH", "verbose": "ONE Illinois South"},
"1142": {"id": "NEILGAR", "verbose": "Neil and Garwood"},
"1143": {"id": "PAADRSN", "verbose": "Pennsylvania and Anderson"},
"1144": {"id": "SSTNPLN", "verbose": "Susan Stone and Plains Ct."},
"1145": {"id": "TMGTCHHL", "verbose": "Timbergate and Cherry Hills"},
"1150": {"id": "PSPCTVTRA", "verbose": "Prospect and Ventura"},
"1151": {"id": "FLOD", "verbose": "Florida and Orchard"},
"1154": {"id": "WASHRAIN", "verbose": "Washington and Rainbow View"},
"1156": {"id": "PDKWLOTM", "verbose": "Paddock Dr. West at Winfield Village Lot"},
"1162": {"id": "CRSNTGRNDL", "verbose": "Crescent and Greendale"},
"1164": {"id": "WDSRWIND", "verbose": "Windsor and Windward Blvd."},
"1166": {"id": "SSXWTRFD", "verbose": "Sussex and Waterford"},
"1174": {"id": "CTGRVBKWD", "verbose": "Cottage Grove and Burkwood"},
"1175": {"id": "NWTNNBL", "verbose": "Newton and Nobel"},
"1211": {"id": "RNDLFHIL", "verbose": "Randolph and Hill"},
"1214": {"id": "PKNSCOOK", "verbose": "Perkins and Cooks Lane"},
"1216": {"id": "ISWS", "verbose": "Water Survey"},
"1217": {"id": "SPFLDEDWN", "verbose": "Springfield and Edwin"},
"1221": {"id": "UNIPSPCT", "verbose": "University and Prospect"},
"1222": {"id": "RNDLFSPFLD", "verbose": "Randolph and Springfield"},
"1223": {"id": "CCSJ", "verbose": "County Satellite Jail"},
"1224": {"id": "CPRRDGCPR", "verbose": "Copper Ridge and Copper"},
"1226": {"id": "WNDSRLHRST", "verbose": "Windsor and Lyndhurst"},
"1232": {"id": "5THERKA", "verbose": "Fifth and Eureka"},
"1233": {"id": "MATSGNSQ", "verbose": "Mattis and Gentry Square Ln. South"},
"1234": {"id": "CHSTRWTR", "verbose": "Chester and Water"},
"1241": {"id": "RSRCHHBCO", "verbose": "Research at Hobbico"},
"1242": {"id": "GWNNV", "verbose": "Goodwin and Nevada"},
"1243": {"id": "CRNDOVTRA", "verbose": "Coronado and Ventura"},
"1246": {"id": "TLGRSSWTCHGRS", "verbose": "Tallgrass and Switchgrass"},
"1247": {"id": "MATSGVA", "verbose": "Mattis at Garden Village"},
"1250": {"id": "LNVWKLRNY", "verbose": "Linview and Killarney"},
"1251": {"id": "JOHNLYN", "verbose": "John and Lynn"},
"1252": {"id": "CHHLAPLWD", "verbose": "Cherry Hills and Applewood"},
"1253": {"id": "BNBLRSHRN", "verbose": "Bonnie Blair and Sharon"},
"1254": {"id": "CRSTWDLDU", "verbose": "Crestwood and Ladue"},
"1255": {"id": "5THVIN", "verbose": "Fifth and Vine"},
"1256": {"id": "ANTWTRS", "verbose": "Anthony and Walters"},
"1262": {"id": "CTGRVPHILO", "verbose": "Cottage Grove and Philo"},
"1266": {"id": "UNIMPL", "verbose": "University and Maple"},
"1267": {"id": "MPLPKCRLTN", "verbose": "Maplepark and Carrelton"},
"1274": {"id": "DSCCLK", "verbose": "D.S.C. on Clark"},
"1276": {"id": "CTRYBNDSPGHL", "verbose": "Country Bend and Springhill"},
"1312": {"id": "NWTNLGGT", "verbose": "Newton and Leggett"},
"1313": {"id": "RNDLFCLARK", "verbose": "Randolph and Clark"},
"1314": {"id": "HRISSHWD", "verbose": "Harris and Sherwood"},
"1315": {"id": "MISMITH", "verbose": "Michigan and Smith"},
"1317": {"id": "VINWASH", "verbose": "Vine and Washington"},
"1322": {"id": "JOHNRSL", "verbose": "John and Russell"},
"1323": {"id": "UNIMKT", "verbose": "University and Market"},
"1324": {"id": "BDWYTPSN", "verbose": "Broadway and Thompson"},
"1325": {"id": "PSPCTWASH", "verbose": "Prospect and Washington"},
"1327": {"id": "UNIGWN", "verbose": "University and Goodwin"},
"1331": {"id": "RLNDWTRS", "verbose": "Roland and Walters"},
"1332": {"id": "KBYWSTRN", "verbose": "Kirby and Western"},
"1333": {"id": "1STSMR", "verbose": "First and St. Mary's Rd."},
"1334": {"id": "MYFRTDR", "verbose": "Mayfair and Theodore"},
"1337": {"id": "BDWYBLY", "verbose": "Broadway and Bailey"},
"1340": {"id": "PARKVIEW", "verbose": "Parkview"},
"1344": {"id": "BNFLDJHN", "verbose": "Brownfield and Johnson"},
"1346": {"id": "KBYCRRGWY", "verbose": "Kirby and Carriage Way"},
"1347": {"id": "GRNMPL", "verbose": "Green and Maple"},
"1350": {"id": "UNIPRRE", "verbose": "University and Prairie"},
"1352": {"id": "WNCHASP", "verbose": "Winchester and Aspen"},
"1354": {"id": "MATSCHEVY", "verbose": "Mattis and Chevy Chase"},
"1355": {"id": "KNCHEASY", "verbose": "Kinch and Easy"},
"1356": {"id": "CHCHMCNLY", "verbose": "Church and McKinley"},
"1366": {"id": "FAR", "verbose": "Florida Ave. Residence Hall"},
"1370": {"id": "GRNPRRE", "verbose": "Green and Prairie"},
"1374": {"id": "WALMART", "verbose": "Walmart"},
"1404": {"id": "STEWHT", "verbose": "State and White"},
"1411": {"id": "4THGRG", "verbose": "Fourth and Gregory"},
"1412": {"id": "IETC", "verbose": "Illinois Employment Training Center"},
"1413": {"id": "WDSRRACE", "verbose": "Windsor and Race"},
"1414": {"id": "PSPCTCLMBA", "verbose": "Prospect and Columbia"},
"1422": {"id": "BCHRMN", "verbose": "Beech and Romine"},
"1425": {"id": "UNICHSTR", "verbose": "University and Chester"},
"1426": {"id": "BLOMKMRT", "verbose": "Bloomington at Home Depot"},
"1427": {"id": "CHCHFAIR", "verbose": "Church and Fair"},
"1430": {"id": "GRNRDGWY", "verbose": "Green and Ridgeway"},
"1437": {"id": "PKCNTRL", "verbose": "Park and Central"},
"1443": {"id": "WNDSRFLDS", "verbose": "Windsor and Fields"},
"1444": {"id": "ISR", "verbose": "Illinois Street Residence Hall"},
"1451": {"id": "NEILBRD", "verbose": "Neil and Beardsley"},
"1454": {"id": "CNVMKT", "verbose": "Convenience Dr. and Market"},
"1455": {"id": "GRGLIB", "verbose": "Gregory at Library"},
"1456": {"id": "MYRASLVHL", "verbose": "Myra Ridge and Silver Hill"},
"1460": {"id": "RACEHIGH", "verbose": "Race and High St."},
"1462": {"id": "FLCRTS", "verbose": "Florida and Curtiss"},
"1465": {"id": "FRVWLNCLN", "verbose": "Fairview and Lincoln"},
"1476": {"id": "UNIASH", "verbose": "University and Ash"},
"1494": {"id": "CBLFLDINV", "verbose": "Cobblefield and Inverness"},
"1503": {"id": "BNTBRKPNCRST", "verbose": "Bentbrook and Pinecrest"},
"1511": {"id": "AMBPHILO", "verbose": "Amber and Philo"},
"1512": {"id": "BLOMPSPCT", "verbose": "Bloomington and Prospect"},
"1514": {"id": "KNCHRAIN", "verbose": "Kinch and Rainbow View"},
"1515": {"id": "JOHNELM", "verbose": "John and Elm"},
"1520": {"id": "SLYBKMG", "verbose": "Slayback and McGee"},
"1523": {"id": "6THGRG", "verbose": "Sixth and Gregory"},
"1531": {"id": "PKRMN", "verbose": "Park and Romine"},
"1532": {"id": "JOHNGRFLD", "verbose": "John and Garfield"},
"1536": {"id": "LNCLNOR", "verbose": "Lincoln and Oregon"},
"1537": {"id": "WASHASH", "verbose": "Washington and Ash"},
"1542": {"id": "KBYROSE", "verbose": "Kirby and Rose Dr."},
"1546": {"id": "6THCHAL", "verbose": "Sixth and Chalmers"},
"1552": {"id": "BNFLDML", "verbose": "Brownfield and Mary Lou Dr."},
"1553": {"id": "PLAMATS", "verbose": "Paula and Mattis"},
"1554": {"id": "SPFLDHILND", "verbose": "Springfield and Highland"},
"1557": {"id": "SWNDYNKR", "verbose": "Sherwin and Yankee Ridge"},
"1566": {"id": "BLOMSNST", "verbose": "Bloomington and Sunset"},
"1567": {"id": "TCBMNRDS", "verbose": "Town Center and Menards"},
"1573": {"id": "JOHNKNWD", "verbose": "John and Kenwood"},
"1600": {"id": "DNCNCRSNG", "verbose": "Duncan and Crossing Ct."},
"1601": {"id": "WASHSCWD", "verbose": "Washington and Scottswood"},
"1605": {"id": "WMBGMATS", "verbose": "Williamsburg and Mattis"},
"1611": {"id": "CMBLQNWAY", "verbose": "Campbell and Queensway"},
"1613": {"id": "NEILN", "verbose": "Neil and North"},
"1614": {"id": "PLAHNYSKL", "verbose": "Paula and Honeysuckle"},
"1616": {"id": "CACC", "verbose": "Carroll at Carroll Addition Community Center"},
"1623": {"id": "CRSGTCRSGTCT", "verbose": "Crossgate and Crossgate Ct."},
"1625": {"id": "CLTNPMNA", "verbose": "Clayton and Pomona"},
"1626": {"id": "BLOMMTDF", "verbose": "Bloomington and Mittendorf"},
"1631": {"id": "PSPCTDNSN", "verbose": "Prospect and Dennison"},
"1632": {"id": "NEILARC", "verbose": "Neil and Arcadia"},
"1633": {"id": "PAKNCH", "verbose": "Pennsylvania and Kinch"},
"1635": {"id": "DNCNVLR", "verbose": "Duncan and Valerie"},
"1636": {"id": "CTGRVWASH", "verbose": "Cottage Grove and Washington"},
"1637": {"id": "VINWDSR", "verbose": "Vine and Windsor"},
"1640": {"id": "OAKGTY", "verbose": "Oak and Gerty"},
"1641": {"id": "RACEWTHL", "verbose": "Race and Whitehall Ct."},
"1643": {"id": "VINSNYC", "verbose": "Vine and Sunnycrest"},
"1645": {"id": "MNUBNA", "verbose": "Main and Urbana"},
"1646": {"id": "BLOMHGN", "verbose": "Bloomington and Hagan"},
"1651": {"id": "CHCHPRRE", "verbose": "Church and Prairie"},
"1652": {"id": "LNCLNBRAD", "verbose": "Lincoln and Bradley"},
"1656": {"id": "BNTBRKGLFCRK", "verbose": "Bentbrook and Golf Creek"},
"1661": {"id": "STEJOHN", "verbose": "State and John"},
"1662": {"id": "LGN1ST", "verbose": "Logan and First"},
"1663": {"id": "MNGLVR", "verbose": "Main and Glover"},
"1666": {"id": "BNBLRNNBTH", "verbose": "Bonnie Blair and Nancy Beth"},
"1670": {"id": "DDSNIL", "verbose": "Dodson and Illinois"},
"1672": {"id": "FLRACE", "verbose": "Florida and Race"},
"1675": {"id": "PDKECTS", "verbose": "Paddock Dr. East and Curtis Road"},
"1682": {"id": "RACEWDSR", "verbose": "Race and Windsor"},
"1699": {"id": "1STCHAL", "verbose": "First and Chalmers"},
"1714": {"id": "STESTNAG", "verbose": "State and Stanage"},
"1717": {"id": "LKVWWTGTN", "verbose": "Lakeview and Worthington"},
"1721": {"id": "MATSPRNCTN", "verbose": "Mattis and Princeton"},
"1722": {"id": "BNTBRKSTLY", "verbose": "Bentbrook and Staley"},
"1725": {"id": "WSFLDSRDN", "verbose": "Westfield and Sheridan"},
"1735": {"id": "CB", "verbose": "Country Brook"},
"1742": {"id": "BDMRRBT", "verbose": "Broadmoor and Robert"},
"1746": {"id": "SPFLDPSPCT", "verbose": "Springfield and Prospect"},
"1752": {"id": "CRSNTJOHN", "verbose": "Crescent and John"},
"1756": {"id": "1STSTDM", "verbose": "First and Stadium"},
"1774": {"id": "OAK", "verbose": "Oak between Hazelwood and St. Mary's"},
"1777": {"id": "2NDHILL", "verbose": "Second and Hill"},
"1814": {"id": "CHCHBUSY", "verbose": "Church and Busey"},
"1952": {"id": "CFDRP", "verbose": "Country Fair Dr. at R.P. Lumber"},
"1961": {"id": "GLNWLSH", "verbose": "Galen and Wilshire"},
"1971": {"id": "ANTHYVP", "verbose": "Anthony at Value Place"},
"2003": {"id": "MLKNWSTBRGH", "verbose": "Mullikin and Westborough"},
"2004": {"id": "WINDWTRFD", "verbose": "Windward and Waterford"},
"2006": {"id": "LAR", "verbose": "LAR"},
"2009": {"id": "NEILTCA", "verbose": "Neil and Town Center Apt."},
"2012": {"id": "STLYAMHT", "verbose": "Staley and Amherst"},
"2013": {"id": "HGNDNSN", "verbose": "Hagan and Dennison"},
"2015": {"id": "TCBMJR", "verbose": "Town Center at Meijer"},
"2021": {"id": "BDWYUNI", "verbose": "Broadway and University"},
"2024": {"id": "JOHNDGWD", "verbose": "John and Dogwood"},
"2033": {"id": "PHILOHRDG", "verbose": "Philo and Harding"},
"2036": {"id": "5THCLMBA", "verbose": "Fifth and Columbia"},
"2040": {"id": "WASH2ND", "verbose": "Washington and Second"},
"2041": {"id": "NEILHLY", "verbose": "Neil and Healey"},
"2054": {"id": "5THBRD", "verbose": "Fifth and Beardsley"},
"2061": {"id": "RACEMI", "verbose": "Race and Michigan"},
"2062": {"id": "WASH4TH", "verbose": "Washington and Fourth"},
"2063": {"id": "MEIJER", "verbose": "Meijer Drive at Meijer"},
"2093": {"id": "GLNSLBY", "verbose": "Galen and Salisbury"},
"2101": {"id": "CPRRDGSND", "verbose": "Copper Ridge and Sand"},
"2103": {"id": "SMRNEIL", "verbose": "St Mary's Road and Neil"},
"2111": {"id": "FOXWDSR", "verbose": "Fox and Windsor"},
"2112": {"id": "PLAPWRS", "verbose": "Paula and Powers"},
"2114": {"id": "BDMRDVD", "verbose": "Broadmoor and David"},
"2124": {"id": "FOXCE", "verbose": "Fox Drive at Community Elements"},
"2126": {"id": "LNCLNCHCH", "verbose": "Lincoln and Church"},
"2143": {"id": "LNCLNOH", "verbose": "Lincoln and Ohio"},
"2145": {"id": "MPLPKALTN", "verbose": "Maplepark and Alton"},
"2146": {"id": "MPLPKLWNDL", "verbose": "Maplepark and Lawndale"},
"2147": {"id": "SWTCHGRSWLDFLWR", "verbose": "Switchgrass and Wildflower"},
"2152": {"id": "PHILOWDSR", "verbose": "Philo and Windsor"},
"2157": {"id": "WDGWDTMGT", "verbose": "Wedgewood and Timbergate"},
"2163": {"id": "CHCHMLR", "verbose": "Church and Miller"},
"2164": {"id": "CHCHELM", "verbose": "Church and Elm"},
"2166": {"id": "RBRCFD", "verbose": "Round Barn Road and Country Fair Dr."},
"2170": {"id": "HZLWDOAK", "verbose": "Hazelwood and Oak"},
"2174": {"id": "FLFLCT", "verbose": "Florida and Florida Ct."},
"2181": {"id": "MKTLGN", "verbose": "Market and Logan"},
"2201": {"id": "MNBRDWY", "verbose": "Main and Broadway"},
"2205": {"id": "VINEGRN", "verbose": "Vine and Evergreen Ct. W"},
"2206": {"id": "PAMD", "verbose": "Pennsylvania and Maryland Dr."},
"2212": {"id": "BRDWLKMJR", "verbose": "Boardwalk and Meijer Dr."},
"2213": {"id": "CFDCONE", "verbose": "Country Fair Dr. and Cone"},
"2214": {"id": "6THARY", "verbose": "Sixth and Armory"},
"2215": {"id": "WASHKNCH", "verbose": "Washington and Kinch"},
"2216": {"id": "BNFLDSLYN", "verbose": "Brownfield and Sharlyn"},
"2217": {"id": "KBYDODD", "verbose": "Kirby and Dodds"},
"2221": {"id": "UNIMCNLY", "verbose": "University and McKinley"},
"2222": {"id": "PKMAT", "verbose": "Park and Mathews"},
"2223": {"id": "CCRWLLW", "verbose": "Country Club and Willow"},
"2224": {"id": "ADRSNFRLN", "verbose": "Anderson and Fairlawn"},
"2225": {"id": "HRISMPL", "verbose": "Harris and Maple"},
"2227": {"id": "WMBGSTRG", "verbose": "Williamsburg and Summit Ridge"},
"2234": {"id": "BRADDNCN", "verbose": "Bradley and Duncan"},
"2236": {"id": "CCNH", "verbose": "County Nursing Home"},
"2237": {"id": "MYFRSNFR", "verbose": "Mayfair and Sandpiper"},
"2242": {"id": "RNDLFAVNDL", "verbose": "Randolph and Avondale"},
"2245": {"id": "VINMHRY", "verbose": "Vine and McHenry"},
"2247": {"id": "SMRGRIF", "verbose": "St. Mary's Road and Griffith"},
"2252": {"id": "FLCTGRV", "verbose": "Florida and Cottage Grove"},
"2255": {"id": "PSPCTFLRPK", "verbose": "Prospect and Floral Park"},
"2257": {"id": "WASHHKRY", "verbose": "Washington and Hickory"},
"2261": {"id": "LNCLNKING", "verbose": "Lincoln and Kettering Park"},
"2264": {"id": "GRNGRGST", "verbose": "Green and Gregory St."},
"2266": {"id": "MLKNCTSMDW", "verbose": "Mullikin and Curtis Meadow"},
"2267": {"id": "WDSRNEIL", "verbose": "Windsor and Neil"},
"2270": {"id": "VINELM", "verbose": "Vine and Elm"},
"2271": {"id": "LKVWWGWD", "verbose": "Lakeview and Wedgewood"},
"2272": {"id": "PSPCTHIL", "verbose": "Prospect and Hill"},
"2273": {"id": "ONENORTH", "verbose": "ONE Illinois North"},
"2303": {"id": "GRNRACE", "verbose": "Green and Race"},
"2304": {"id": "WNDVRPBLCK", "verbose": "Wendover and Pebble Creek"},
"2305": {"id": "NEILHIL", "verbose": "Neil and Hill St."},
"2306": {"id": "LWNDLBLPK", "verbose": "Lawndale and Bellepark"},
"2311": {"id": "ODGHF", "verbose": "Orchard and George Huff"},
"2313": {"id": "MATSSTHWD", "verbose": "Mattis and Southwood"},
"2315": {"id": "STEVIN", "verbose": "State and Vine"},
"2316": {"id": "MHRYLYN", "verbose": "McHenry and Lynn"},
"2321": {"id": "CTGRVOR", "verbose": "Cottage Grove and Oregon"},
"2323": {"id": "FLRTLG", "verbose": "Florida and Rutledge"},
"2325": {"id": "VINGHF", "verbose": "Vine and George Huff"},
"2327": {"id": "EASTKER", "verbose": "Eastern and Kerr"},
"2332": {"id": "BRADRNDLF", "verbose": "Bradley and Randolph"},
"2333": {"id": "BL", "verbose": "Big Lots"},
"2335": {"id": "CHCHCRSN", "verbose": "Church and Carson"},
"2337": {"id": "5THGRV", "verbose": "Fifth and Grove"},
"2341": {"id": "SPFLDPRC", "verbose": "Springfield at Phillips Rec. Ctr."},
"2343": {"id": "WHT4TH", "verbose": "White and Fourth"},
"2344": {"id": "MJRPSPCT", "verbose": "Meijer Drive and Prospect"},
"2345": {"id": "WLRW", "verbose": "Bradley at WLRW"},
"2351": {"id": "FRLNERN", "verbose": "Fairlawn and Eastern"},
"2352": {"id": "BDWYLST", "verbose": "Broadway and Lake Side Terrace"},
"2353": {"id": "BRADCLTN", "verbose": "Bradley and Clayton"},
"2355": {"id": "CRSNTPKDL", "verbose": "Crescent and Parkdale"},
"2356": {"id": "RNDLFMPL", "verbose": "Randolph and Maple"},
"2360": {"id": "GDWNMRL", "verbose": "Goodwin at Materials Research"},
"2361": {"id": "UHS", "verbose": "Urbana High School"},
"2362": {"id": "NEILMSHL", "verbose": "Neil and Marshall"},
"2364": {"id": "APTHICRS", "verbose": "Airport Rd. and Highcross"},
"2365": {"id": "QNWAYRLND", "verbose": "Queensway and Roland"},
"2370": {"id": "CLTNHTG", "verbose": "Clayton and Heritage"},
"2373": {"id": "WRTCLMBA", "verbose": "Wright and Columbia"},
"2375": {"id": "WRTDBLN", "verbose": "Wright and Dublin"},
"2401": {"id": "WDSRCHHL", "verbose": "Windsor and Cherry Hills"},
"2403": {"id": "RACEMHRY", "verbose": "Race and McHenry"},
"2406": {"id": "HGNPNR", "verbose": "Hagen and Pioneer"},
"2410": {"id": "SSXSFLD", "verbose": "Sussex and Southfield"},
"2411": {"id": "HICRSALC", "verbose": "Highcross and Apostalic Life Church"},
"2412": {"id": "MATSANTA", "verbose": "Mattis and Anita"},
"2413": {"id": "PKNSRNTRW", "verbose": "Perkins and Raintree Woods"},
"2414": {"id": "PACT", "verbose": "Pennsylvania Ct."},
"2416": {"id": "WDSRDNBK", "verbose": "Windsor and Donnybrook"},
"2421": {"id": "SPFLDWLWN", "verbose": "Springfield and Westlawn"},
"2422": {"id": "STLYTRNBRY", "verbose": "Staley and Turnberry"},
"2423": {"id": "STEERKA", "verbose": "State and Eureka"},
"2431": {"id": "SPFLDEMWD", "verbose": "Springfield and Elmwood"},
"2434": {"id": "LNCLNIL", "verbose": "Lincoln and Illinois"},
"2435": {"id": "KNCHLH", "verbose": "Kinch and Lantern Hill"},
"2437": {"id": "GC", "verbose": "Ginger Creek Apts."},
"2441": {"id": "CVTRYRXFRD", "verbose": "Coventry and Roxford"},
"2444": {"id": "STMAT", "verbose": "St. Mathews"},
"2446": {"id": "BTSLRMN", "verbose": "Butzow and Lierman"},
"2450": {"id": "STEUNI", "verbose": "State and University"},
"2451": {"id": "GRGDNR", "verbose": "Gregory and Dorner"},
"2456": {"id": "CF", "verbose": "Country Fair"},
"2460": {"id": "PA6TH", "verbose": "Pennsylvania and Sixth"},
"2463": {"id": "NVLNCLN", "verbose": "Nevada and Lincoln"},
"2466": {"id": "CTSMDWFXBRGH", "verbose": "Curtis Meadow and Foxborough"},
"2470": {"id": "MLKNRMGNTN", "verbose": "Mullikin and Remington Way"},
"2472": {"id": "GRNISR", "verbose": "Green at Illinois Street Residence Hall"},
"2475": {"id": "ADRSNMI", "verbose": "Anderson and Michigan"},
"2507": {"id": "DNCNLWNDL", "verbose": "Duncan and Lawndale"},
"2512": {"id": "RMNBRD", "verbose": "Romine and Beardsley"},
"2513": {"id": "HNKHMTN", "verbose": "Hancock and Hamilton"},
"2515": {"id": "GLNPLMT", "verbose": "Galen and Plymouth"},
"2516": {"id": "CMBLCRT", "verbose": "Campbell and Curt"},
"2521": {"id": "MATSUSPS", "verbose": "Mattis at Post Office"},
"2524": {"id": "KBYLCLNRD", "verbose": "Kirby and Lincoln Rd."},
"2526": {"id": "WDSRDNCN", "verbose": "Windsor and Duncan"},
"2527": {"id": "TMPSNPK", "verbose": "Bradley and Thompson Park"},
"2530": {"id": "CRTSWNSTN", "verbose": "Curtis and Wynstone"},
"2533": {"id": "JOHNVCTR", "verbose": "John and Victor"},
"2534": {"id": "ODMIDS", "verbose": "Orchard Downs Mid-Block South"},
"2543": {"id": "FLLNDN", "verbose": "Florida and Linden"},
"2547": {"id": "LNCLNHIL", "verbose": "Lincoln and Hill"},
"2551": {"id": "INT1STSTP", "verbose": "Interstate at First Step"},
"2552": {"id": "GLNROSS", "verbose": "Galen and Ross"},
"2553": {"id": "NEILCLMBA", "verbose": "Neil and Columbia"},
"2554": {"id": "GWNGRG", "verbose": "Goodwin and Gregory"},
"2556": {"id": "ADRSNBRTN", "verbose": "Anderson and Brighton"},
"2560": {"id": "CHCHRNDLF", "verbose": "Church and Randolph"},
"2561": {"id": "MNABD", "verbose": "Main and Art Bartell Dr."},
"2562": {"id": "ATRIUM", "verbose": "Atrium Apts"},
"2570": {"id": "CTSMDWSTLY", "verbose": "Curtis Meadow and Staley"},
"2577": {"id": "BRADHKRY", "verbose": "Bradley and Hickory"},
"2602": {"id": "GHFRACE", "verbose": "George Huff and Race"},
"2606": {"id": "BDMRLNWD", "verbose": "Broadmoor and Lynwood"},
"2612": {"id": "GRNADRSN", "verbose": "Green and Anderson"},
"2614": {"id": "KBYBLPK", "verbose": "Kirby and Bellepark Dr."},
"2617": {"id": "DNCNHTWD", "verbose": "Duncan and Heathwood Ct."},
"2620": {"id": "CNHMPKNS", "verbose": "Cunningham and Perkins"},
"2622": {"id": "BRADJAS", "verbose": "Bradley and James"},
"2623": {"id": "PLALRKSPR", "verbose": "Paula and Larkspur"},
"2624": {"id": "GRGMUM", "verbose": "Gregory at Mumford Hall"},
"2626": {"id": "BNFLDCFTN", "verbose": "Brownfield and Clifton"},
"2633": {"id": "DNCNCLTN", "verbose": "Duncan and Clayton"},
"2634": {"id": "150DOD", "verbose": "U.S. 150 and Dodson Dr."},
"2635": {"id": "CLMBANEIL", "verbose": "Columbia and Neil"},
"2636": {"id": "BRWSLNST", "verbose": "Burwash and Lynhurst"},
"2641": {"id": "WDSRPSPCT", "verbose": "Windsor and Prospect"},
"2643": {"id": "CFW", "verbose": "Country Fair West Entrance"},
"2644": {"id": "WDSRWWBK", "verbose": "Windsor and Willowbrook Ct."},
"2651": {"id": "BDWYKER", "verbose": "Broadway and Kerr"},
"2652": {"id": "KBYCMBG", "verbose": "Kirby and Cambridge"},
"2654": {"id": "LNHSTARBR", "verbose": "Lyndhurst and Arbours Drive"},
"2660": {"id": "SPFLDLYN", "verbose": "Springfield and Lynn"},
"2663": {"id": "WLNTMN", "verbose": "Walnut and Main"},
"2666": {"id": "DVNLSDED", "verbose": "Devonshire and Lakeside Dr."},
"2674": {"id": "WLNTUNI", "verbose": "Walnut and University"},
"2703": {"id": "PDKELOTD", "verbose": "Paddock Dr. East at Winfeld Village Lot"},
"2714": {"id": "MHRYCTGRV", "verbose": "McHenry and Cottage Grove"},
"2715": {"id": "UNIRACE", "verbose": "University and Race"},
"2716": {"id": "ANTHYGW", "verbose": "Anthony at Goodwill"},
"2733": {"id": "PABDWY", "verbose": "Pennsylvania and Broadway"},
"2735": {"id": "2NDPK", "verbose": "Second and Park"},
"2740": {"id": "NEILINTR", "verbose": "Neil and Interstate"},
"2745": {"id": "GRDBTZ", "verbose": "Guardian Dr. and Butzow"},
"2746": {"id": "STESPFLD", "verbose": "State and Springfield"},
"2754": {"id": "STECLMBA", "verbose": "State and Columbia"},
"2761": {"id": "WRTCHCH", "verbose": "Wright and Church"},
"2762": {"id": "BLOMLA", "verbose": "Bloomington and Louisiana"},
"2764": {"id": "CLMBAHNK", "verbose": "Columbia and Hancock"},
"2770": {"id": "MATSWLM", "verbose": "Mattis and William"},
"2774": {"id": "WDSRMTRY", "verbose": "Windsor and Monterey"},
"2778": {"id": "JOHNHLYCST", "verbose": "John and Hollycrest"},
"2872": {"id": "4THBRAD", "verbose": "Fourth and Bradley"},
"2961": {"id": "INVPSTWK", "verbose": "Inverness and Prestwick Pt"},
"3001": {"id": "UNISCMR", "verbose": "University and Sycamore"},
"3003": {"id": "WLMSCTDL", "verbose": "William and Scottsdale"},
"3014": {"id": "4THPDY", "verbose": "Fourth and Peabody"},
"3036": {"id": "MHRYCMBS", "verbose": "McHenry and Combes"},
"3043": {"id": "SSTNGLNA", "verbose": "Susan Stone and Galena"},
"3051": {"id": "HICRSBA", "verbose": "Highcross and Bruce Acres"},
"3060": {"id": "MCNLYMPL", "verbose": "McKinley and Maple"},
"3062": {"id": "UNIFAIR", "verbose": "University and Fair"},
"3063": {"id": "DNCNWTRSN", "verbose": "Duncan and Watterson"},
"3064": {"id": "MKTKNYN", "verbose": "Market and Kenyon Rd."},
"3067": {"id": "BRADRDWD", "verbose": "Bradley and Redwood"},
"3072": {"id": "CHHLPNVY", "verbose": "Cherry Hills and Pine Valley"},
"3077": {"id": "MLKNIRNWD", "verbose": "Mullikin and Ironwood"},
"3100": {"id": "VINIL", "verbose": "Vine and Illinois"},
"3102": {"id": "DVNMYFR", "verbose": "Devonshire and Mayfair"},
"3103": {"id": "PSPCTBDMR", "verbose": "Prospect and Broadmoor"},
"3104": {"id": "MNDDSN", "verbose": "Main and Dodson"},
"3105": {"id": "VINWTR", "verbose": "Vine and Water"},
"3110": {"id": "LNCLNDE", "verbose": "Lincoln and Delaware"},
"3111": {"id": "KBYSCTDL", "verbose": "Kirby and Scottsdale"},
"3112": {"id": "FOXDVN", "verbose": "Fox and Devonshire"},
"3121": {"id": "IT", "verbose": "Illinois Terminal"},
"3123": {"id": "BRADCMI", "verbose": "Bradley and Champaign St."},
"3124": {"id": "CTRYBNDSUMHL", "verbose": "Country Bend and Summerhill"},
"3125": {"id": "BRDYHI", "verbose": "Brady and High"},
"3126": {"id": "PSPCTFRAN", "verbose": "Prospect and Francis"},
"3127": {"id": "MATSHNRY", "verbose": "Mattis and Henry St."},
"3135": {"id": "ANTDALE", "verbose": "Anthony and Dale"},
"3137": {"id": "KPDLNVW", "verbose": "Kettering and Linview"},
"3140": {"id": "MNPLR", "verbose": "Main and Poplar"},
"3142": {"id": "MYNRDCMRN", "verbose": "Maynard and Cameron"},
"3144": {"id": "MKTPLCS", "verbose": "Market Place South"},
"3147": {"id": "WDSRMLRS", "verbose": "Windsor and Melrose"},
"3152": {"id": "GLNNWBY", "verbose": "Galen and Newbury"},
"3153": {"id": "STECLARK", "verbose": "State and Clark"},
"3159": {"id": "CBLFLDGLNBRK", "verbose": "Cobblefield and Glenn Brooke"},
"3161": {"id": "FOXREMAX", "verbose": "Fox at Remax Real Estate"},
"3162": {"id": "SPFLD", "verbose": "Springfield and Country Fair"},
"3164": {"id": "BLGRSSDGGRS", "verbose": "Bluegrass and Sedgegrass"},
"3171": {"id": "MKTPLC", "verbose": "Market Place"},
"3172": {"id": "BDWYPK", "verbose": "Broadway and Park"},
"3201": {"id": "KBYRSWD", "verbose": "Kirby and Rosewood"},
"3202": {"id": "SPFLDDRPR", "verbose": "Springfield and Draper"},
"3207": {"id": "CPRRDGIRNWD", "verbose": "Copper Ridge and Ironwood"},
"3212": {"id": "CCCH", "verbose": "Champaign County Court House"},
"3214": {"id": "ODNS", "verbose": "Orchard Downs North Shelter"},
"3216": {"id": "PLASTIPAK", "verbose": "Plastipak"},
"3223": {"id": "SLYBKIRA", "verbose": "Slayback and Ira"},
"3227": {"id": "MCRTRHI", "verbose": "MacArthur and High"},
"3232": {"id": "KBYOAK", "verbose": "Kirby and Oak"},
"3236": {"id": "BNFLDDON", "verbose": "Brownfield and Donald"},
"3237": {"id": "BAYBRDWLK", "verbose": "Baytown and Boardwalk"},
"3242": {"id": "UNIRSL", "verbose": "University and Russell"},
"3243": {"id": "GRNLYN", "verbose": "Green and Lynn"},
"3244": {"id": "CHCHVCTR", "verbose": "Church and Victor"},
"3246": {"id": "1STPDY", "verbose": "First and Peabody"},
"3250": {"id": "GLNWDSR", "verbose": "Galen and Windsor"},
"3252": {"id": "HRISLA", "verbose": "Harris and Louisiana"},
"3253": {"id": "IETCMATS", "verbose": "I.E.T.C. and Mattis"},
"3254": {"id": "BRADSTE", "verbose": "Bradley and State"},
"3260": {"id": "PSPCTDVN", "verbose": "Prospect and Devonshire"},
"3261": {"id": "PSPCTLNSH", "verbose": "Prospect and Lincolnshire"},
"3262": {"id": "LYNPRK", "verbose": "Lynn and Park"},
"3263": {"id": "KBYSTE", "verbose": "Kirby and State"},
"3264": {"id": "WNCHBRBY", "verbose": "Winchester and Barberry"},
"3271": {"id": "MATSGLNPK", "verbose": "Mattis and Glenn Park Dr."},
"3272": {"id": "ILGLN", "verbose": "Illinois and Glenn Dr."},
"3274": {"id": "WDSRWEST", "verbose": "Windsor West Apts"},
"3304": {"id": "STEELS", "verbose": "State and Ells"},
"3305": {"id": "BNBLRAMY", "verbose": "Bonnie Blair and Amy"},
"3311": {"id": "GRN4TH", "verbose": "Green and Fourth"},
"3313": {"id": "STNBKMRAN", "verbose": "Stoney Brook and Moraine"},
"3315": {"id": "SPFLDWLS", "verbose": "Springfield and Willis"},
"3317": {"id": "KBYRDGRD", "verbose": "Kirby and Ridge Rd."},
"3321": {"id": "MHRYLYNE", "verbose": "McHenry & Lynn - East"},
"3324": {"id": "ADRSNHRDG", "verbose": "Anderson and Harding"},
"3325": {"id": "SMRSGSWTCHGRS", "verbose": "Summersage and Switchgrass"},
"3326": {"id": "PA4TH", "verbose": "Pennsylvania and Fourth"},
"3330": {"id": "WRTBCH", "verbose": "Wright and Beech"},
"3333": {"id": "DNCNCLKRD", "verbose": "Duncan and Clark"},
"3334": {"id": "NEILWLGFRD", "verbose": "Neil and Walingford"},
"3336": {"id": "GRNNEIL", "verbose": "Green and Neil"},
"3337": {"id": "WASH3RD", "verbose": "Washington and Third"},
"3341": {"id": "KERWRD", "verbose": "Kerr and Ward"},
"3343": {"id": "GRN6TH", "verbose": "Green and Sixth"},
"3344": {"id": "6THTFT", "verbose": "Sixth and Lorado Taft"},
"3356": {"id": "UNIVIN", "verbose": "University and Vine"},
"3360": {"id": "PMNABRAD", "verbose": "Pomona and Bradley"},
"3364": {"id": "WHT1ST", "verbose": "White and First"},
"3365": {"id": "RNDLFCLMBA", "verbose": "Randolph and Columbia"},
"3366": {"id": "BLOMCLLK", "verbose": "Bloomington and Clearlake"},
"3371": {"id": "DNCNPMDW", "verbose": "Duncan and Prairie Meadow"},
"3374": {"id": "WDSRLKWD", "verbose": "Windsor and Lakewood"},
"3376": {"id": "WMBG", "verbose": "Williamsburg between Bradley and Summerl"},
"3401": {"id": "WDSRBA", "verbose": "Windsor and Bel Air"},
"3407": {"id": "VINMNTCLR", "verbose": "Vine and Montclair"},
"3412": {"id": "CRSNTRBM", "verbose": "Crescent and Round Barn Manor"},
"3416": {"id": "CFDPK", "verbose": "Country Fair Dr. and Park"},
"3421": {"id": "HRISBRAD", "verbose": "Harris and Bradley"},
"3422": {"id": "CRSNTOLA", "verbose": "Crescent and Ola"},
"3423": {"id": "KBYALMA", "verbose": "Kirby and Alma"},
"3424": {"id": "JOHNMCHLCT", "verbose": "John and Mitchell Ct."},
"3432": {"id": "BDWYCM", "verbose": "Broadway at Save A Lot"},
"3435": {"id": "DVNPCH", "verbose": "Devonshire and Peach"},
"3441": {"id": "KBYKNWD", "verbose": "Kirby and Kenwood"},
"3442": {"id": "COLRCH", "verbose": "Colorado and Larch"},
"3443": {"id": "WDSRSTLW", "verbose": "Windsor and Stillwater"},
"3444": {"id": "FLWLY", "verbose": "Florida and Wiley"},
"3445": {"id": "DNRPDY", "verbose": "Dorner and Peabody"},
"3446": {"id": "SPFLDMCNLY", "verbose": "Springfield and McKinley"},
"3450": {"id": "RACEDE", "verbose": "Race and Delaware"},
"3451": {"id": "BRADPSPCT", "verbose": "Bradley and Prospect"},
"3452": {"id": "MNFREMNT", "verbose": "Main and Fremont"},
"3453": {"id": "WDFLDSV16", "verbose": "Woodfield at Savoy 16 Theaters"},
"3456": {"id": "BRADCRPS", "verbose": "Bradley and Crispus"},
"3457": {"id": "PAORCH", "verbose": "Pennsylvania and Orchard"},
"3460": {"id": "GRG2ND", "verbose": "Gregory and Second St"},
"3462": {"id": "WLNTBLY", "verbose": "Walnut and Bailey"},
"3464": {"id": "VINHLMS", "verbose": "Vine and Holmes"},
"3474": {"id": "TRLSFWN", "verbose": "Trails and Fawn Hill"},
"3487": {"id": "WINDCNTYSD", "verbose": "Windward and Countryside"},
"3501": {"id": "STEWASH", "verbose": "State and Washington"},
"3502": {"id": "PATTERSON", "verbose": "Patterson"},
"3503": {"id": "MKTBNB", "verbose": "Market St behind Barnes and Noble Books"},
"3504": {"id": "WASHLNR", "verbose": "Washington and Lanore"},
"3505": {"id": "CHCHORCD", "verbose": "Church and Orchard"},
"3511": {"id": "WDSRWNCH", "verbose": "Windsor and Winchester"},
"3513": {"id": "E14", "verbose": "Lot E-14"},
"3514": {"id": "CLMBAHKRY", "verbose": "Columbia and Hickory"},
"3516": {"id": "HOBBICO", "verbose": "Viking at Hobbico"},
"3521": {"id": "UNI4TH", "verbose": "University and Fourth"},
"3527": {"id": "WMBGGH", "verbose": "Williamsburg and Garden Hills Lane"},
"3532": {"id": "LNCLNEADS", "verbose": "Lincoln and Eads"},
"3534": {"id": "PKLN", "verbose": "Parkland College"},
"3537": {"id": "WLMBRNTWD", "verbose": "William and Brentwood"},
"3539": {"id": "BNTBRKBBCT", "verbose": "Bentbrook and Bentbrook Ct"},
"3540": {"id": "BLGRSTLGRS", "verbose": "Bluegrass and Tallgrass"},
"3541": {"id": "BLOMWLS", "verbose": "Bloomington and Willis"},
"3542": {"id": "MKTPLCSE", "verbose": "Market Place Southeast"},
"3544": {"id": "GRNLCST", "verbose": "Green and Locust"},
"3552": {"id": "GRNCDR", "verbose": "Green and Cedar"},
"3554": {"id": "LUMBER", "verbose": "Country Fair Dr. at Hundman Lumber"},
"3556": {"id": "WLMBLPRK", "verbose": "William and Bellepark"},
"3562": {"id": "TCBNEIL", "verbose": "Town Center Blvd and Neil"},
"3565": {"id": "FLSMITH", "verbose": "Florida and Smith"},
"3566": {"id": "SPFLDFLRA", "verbose": "Springfield and Flora"},
"3571": {"id": "WNCHCYPS", "verbose": "Winchester and Cypress"},
"3601": {"id": "RNDLFTRMNT", "verbose": "Randolph and Tremont"},
"3602": {"id": "MKTTLP", "verbose": "Market and Tulip Tree"},
"3615": {"id": "RE", "verbose": "Highcross and Kyle"},
"3617": {"id": "GRNORCH", "verbose": "Green and Orchard"},
"3621": {"id": "VINMCNLY", "verbose": "Vine and McKinley"},
"3622": {"id": "CTGRVERN", "verbose": "Cottage Grove and Eastern"},
"3623": {"id": "CTGRVSYNC", "verbose": "Cottage Grove and Sunnycrest"},
"3624": {"id": "ALPTMBLN", "verbose": "Alpine and Timberline"},
"3630": {"id": "MNWLNT", "verbose": "Main and Walnut"},
"3632": {"id": "FLSUNAPTS", "verbose": "Florida at Sunnycrest Apts."},
"3641": {"id": "BDMRBLMY", "verbose": "Broadmoor and Bellamy"},
"3642": {"id": "CFDCHCH", "verbose": "Country Fair Dr. and Church"},
"3643": {"id": "GWNHIL", "verbose": "Goodwin and Hill"},
"3644": {"id": "RLNDCMCHE", "verbose": "Roland and Comanche"},
"3650": {"id": "CRSGTIRNWD", "verbose": "Crossgate and Ironwood Ln"},
"3651": {"id": "LNCLNCA", "verbose": "Lincoln and California"},
"3652": {"id": "BRWSWDFLD", "verbose": "Burwash and Woodfield"},
"3653": {"id": "UNILYN", "verbose": "University and Lynn"},
"3655": {"id": "PHILOSLVR", "verbose": "Philo and Silver"},
"3656": {"id": "BNFLDCLMBA", "verbose": "Brownfield and Columbia"},
"3665": {"id": "BRADELM", "verbose": "Bradley and Elm"},
"3675": {"id": "BRADMATS", "verbose": "Bradley and Mattis"},
"3703": {"id": "VINLYN", "verbose": "Vine and Lynn"},
"3710": {"id": "STETC", "verbose": "State and Trade Center Dr."},
"3715": {"id": "CLRFRVW", "verbose": "Coler and Fairview"},
"3721": {"id": "SCWDOR", "verbose": "Scottswood and Oregon"},
"3723": {"id": "WASHPHLPS", "verbose": "Washington and Phillips"},
"3725": {"id": "NEILWHT", "verbose": "Neil and White"},
"3729": {"id": "DVNLNWD", "verbose": "Devonshire and Lynnwood Dr."},
"3735": {"id": "WDSRIMP", "verbose": "Windsor and Imperial"},
"3736": {"id": "PMNAHRTG", "verbose": "Pomona and Heritage"},
"3742": {"id": "BLGRSSMRSG", "verbose": "Bluegrass and Summersage"},
"3747": {"id": "JOHNMATS", "verbose": "John and Mattis"},
"3754": {"id": "RNDLFWLM", "verbose": "Randolph and William"},
"3762": {"id": "SPFLDELM", "verbose": "Springfield and Elm"},
"3766": {"id": "WRTSPFLD", "verbose": "Wright and Springfield"},
"3799": {"id": "CLTNCPT", "verbose": "Clayton and Compton"},
"3889": {"id": "SPFLDMAT", "verbose": "Springfield and Mathews"},
"3926": {"id": "PKLNSTFD", "verbose": "Park Lane and Stanford"},
"4006": {"id": "PSPCTGALN", "verbose": "Prospect and Galen"},
"4012": {"id": "UNIWLNT", "verbose": "University and Walnut"},
"4013": {"id": "SPFLDHVY", "verbose": "Springfield and Harvey"},
"4014": {"id": "ILBDWY", "verbose": "Illinois and Broadway"},
"4022": {"id": "RNDLFHLY", "verbose": "Randolph and Healey"},
"4024": {"id": "MKTPLCNE", "verbose": "Market Place North East"},
"4025": {"id": "UNICENT", "verbose": "University and Central"},
"4027": {"id": "CMIHS", "verbose": "Champaign House"},
"4031": {"id": "FLBRDWY", "verbose": "Florida and Broadway"},
"4037": {"id": "SPFLDGRFLD", "verbose": "Springfield and Garfield"},
"4040": {"id": "RMNERKA", "verbose": "Romine and Eureka"},
"4043": {"id": "VINMFRD", "verbose": "Vine and Mumford"},
"4044": {"id": "NVGRGPL", "verbose": "Nevada and Gregory Place"},
"4045": {"id": "EMS", "verbose": "Edison Middle School"},
"4051": {"id": "WRTWASH", "verbose": "Wright and Washington"},
"4053": {"id": "LRMNHNTR", "verbose": "Lierman and Hunter"},
"4061": {"id": "GRNBRCH", "verbose": "Green and Birch"},
"4064": {"id": "MATSSANG", "verbose": "Mattis and Sangamon"},
"4066": {"id": "UNIMCLGH", "verbose": "University and McCullough"},
"4067": {"id": "GLNTDR", "verbose": "Galen and Theodore"},
"4072": {"id": "CHHLBYHL", "verbose": "Cherry Hills and Bay Hill"},
"4100": {"id": "KBYCM", "verbose": "Kirby at County Market"},
"4102": {"id": "5THTRMNT", "verbose": "Fifth and Tremont"},
"4103": {"id": "GRNSTE", "verbose": "Green and State"},
"4105": {"id": "HRISBRD", "verbose": "Harris and Beardsley"},
"4112": {"id": "HSLRNDLF", "verbose": "Hessel and Randolph"},
"4113": {"id": "CTS1ST", "verbose": "Curtis Road and South First St."},
"4116": {"id": "PLAMELNE", "verbose": "Paula and Melanie"},
"4120": {"id": "VINWLS", "verbose": "Vine and Wills"},
"4125": {"id": "FRLN", "verbose": "Fairlawn"},
"4130": {"id": "STECHAS", "verbose": "State and Charles"},
"4132": {"id": "WMBGSMLN", "verbose": "Williamsburg and Summerlin"},
"4135": {"id": "NEILSTDM", "verbose": "Neil and Stadium"},
"4140": {"id": "UNIMTD", "verbose": "University at MTD"},
"4141": {"id": "CMBLDBNS", "verbose": "Campbell and Dobbins"},
"4143": {"id": "MATSWDSR", "verbose": "Mattis and Windsor"},
"4144": {"id": "WLMFROAK", "verbose": "William and Fairoaks"},
"4145": {"id": "ARYWRT", "verbose": "Armory and Wright"},
"4146": {"id": "CTSPDKW", "verbose": "Curtis Road and Paddock Dr West"},
"4149": {"id": "NEILCNTR", "verbose": "Neil and Center"},
"4150": {"id": "STEHIL", "verbose": "State and Hill"},
"4151": {"id": "KBYMYFR", "verbose": "Kirby and Mayfair"},
"4155": {"id": "MCNLYHVAD", "verbose": "McKinley and Harvard"},
"4160": {"id": "WDSRVYBK", "verbose": "Windsor and Valleybrook"},
"4164": {"id": "WRTCHAL", "verbose": "Wright and Chalmers"},
"4176": {"id": "SSTNMOS", "verbose": "Susan Stone and Moss"},
"4201": {"id": "GRNLNCLN", "verbose": "Green and Lincoln"},
"4203": {"id": "CLTNCVT", "verbose": "Clayton and Covington"},
"4205": {"id": "MNVIN", "verbose": "Main and Vine"},
"4206": {"id": "FLGRV", "verbose": "Florida and Grove"},
"4207": {"id": "DSC", "verbose": "Bradley at DSC"},
"4210": {"id": "UNI2ND", "verbose": "University and Second"},
"4215": {"id": "PSPCTASRC", "verbose": "Prospect and Ayrshire Cir."},
"4222": {"id": "RACENV", "verbose": "Race and Nevada"},
"4223": {"id": "CTGRVCO", "verbose": "Cottage Grove and Colorado"},
"4225": {"id": "LNCLNKLRNY", "verbose": "Lincoln and Killarney"},
"4226": {"id": "GRD", "verbose": "Butzow at Guardian West"},
"4232": {"id": "ADRSNEVRGN", "verbose": "Anderson and Evergreen Circle"},
"4235": {"id": "ASHTON", "verbose": "First at Ashton Woods"},
"4236": {"id": "CHCHJAS", "verbose": "Church and James"},
"4241": {"id": "1STGTY", "verbose": "First and Gerty"},
"4243": {"id": "RACEMBRK", "verbose": "Race at Meadowbrook Park"},
"4244": {"id": "CTGRVIL", "verbose": "Cottage Grove and Illinois"},
"4246": {"id": "MNGRV", "verbose": "Main and Grove"},
"4247": {"id": "1STE14", "verbose": "First and Southeast Lot E-14"},
"4255": {"id": "PKWRT", "verbose": "Park and Wright"},
"4262": {"id": "GRGIKE", "verbose": "Gregory at Ikenberry Commons"},
"4263": {"id": "RACECA", "verbose": "Race and California"},
"4272": {"id": "CRSNTJMS", "verbose": "Crescent at Jefferson Middle School"},
"4275": {"id": "SWNDPNDR", "verbose": "Sherwin and Pond Ridge"},
"4276": {"id": "WLNTLGN", "verbose": "Walnut and Logan"},
"4304": {"id": "JOHNFOLY", "verbose": "John and Foley"},
"4306": {"id": "FLVIN", "verbose": "Florida and Vine"},
"4310": {"id": "UMS", "verbose": "Urbana Middle School"},
"4315": {"id": "NEILBRAD", "verbose": "Neil and Bradley"},
"4322": {"id": "AMBUC", "verbose": "University and Ambucs Park Entrance"},
"4325": {"id": "RACEELM", "verbose": "Race and Elm"},
"4327": {"id": "GWNSPFLD", "verbose": "Goodwin and Springfield"},
"4330": {"id": "SPFLDJAS", "verbose": "Springfield and James"},
"4331": {"id": "KBYARW", "verbose": "Kirby and Arrow Rd."},
"4333": {"id": "CRSTWDBRAD", "verbose": "Crestwood and Bradley"},
"4334": {"id": "BNFLDARL", "verbose": "Brownfield and Arlene"},
"4340": {"id": "UNIJAS", "verbose": "University and James"},
"4341": {"id": "GRNWBR", "verbose": "Green and Webber"},
"4345": {"id": "WDSRJDN", "verbose": "Windsor and Jordan"},
"4346": {"id": "KBYWSFLD", "verbose": "Kirby and Westfield"},
"4347": {"id": "SPFLDPINE", "verbose": "Springfield and Pine"},
"4353": {"id": "PMNAEH", "verbose": "Pomona and Ed Hoffman"},
"4360": {"id": "GRNGWN", "verbose": "Green and Goodwin"},
"4361": {"id": "1STDAN", "verbose": "First and Daniel"},
"4363": {"id": "LNHSTEGRN", "verbose": "Lyndhurst and Evergreen Circle"},
"4365": {"id": "CTGRVPA", "verbose": "Cottage Grove and Penn."},
"4371": {"id": "TAT130", "verbose": "Tatman and Rt. 130"},
"4373": {"id": "STDMOAK", "verbose": "Stadium and Oak"},
"4377": {"id": "MYRATRLS", "verbose": "Myra Ridge and Trails"},
"4412": {"id": "MKTBELL", "verbose": "Market and Bellefontaine"},
"4421": {"id": "MNSMITH", "verbose": "Main and Smith Rd."},
"4424": {"id": "KBYCRGWY", "verbose": "Kirby and Carriage Way"},
"4426": {"id": "CMBLCMCHE", "verbose": "Campbell and Comanche"},
"4432": {"id": "SPFLDPRRE", "verbose": "Springfield and Prairie"},
"4440": {"id": "WNCHSMR", "verbose": "Winchester and Southmoor"},
"4441": {"id": "MPLPKMPLWD", "verbose": "Maplepark and Maplewood"},
"4443": {"id": "MHRYLYN1", "verbose": "McHenry and Lynn St. 1"},
"4446": {"id": "WESTGATE", "verbose": "Westgate Apts."},
"4450": {"id": "INTRSRCH", "verbose": "Interstate and Research"},
"4451": {"id": "MATSSGR", "verbose": "Mattis and Springer"},
"4452": {"id": "MKTVANT", "verbose": "Marketview and Anthony"},
"4455": {"id": "UIPS", "verbose": "U of I Personnel Services"},
"4456": {"id": "WDSRSSTN", "verbose": "Windsor and Susan Stone"},
"4462": {"id": "MCRTRIL", "verbose": "MacArthur and Illinois"},
"4463": {"id": "WRTHIL", "verbose": "Wright and Hill"},
"4466": {"id": "TMGTPNHST", "verbose": "Timbergate and Pinehurst"},
"4470": {"id": "UNICHSNT", "verbose": "University and Chestnut"},
"4472": {"id": "CVTRYHLFX", "verbose": "Coventry and Halifax"},
"4505": {"id": "3RDDAN", "verbose": "Third and Daniel"},
"4511": {"id": "MATSMDWDR", "verbose": "Mattis and Meadow Dr."},
"4512": {"id": "LNHSTBDFD", "verbose": "Lyndhurst and Bedford"},
"4515": {"id": "MNSCWD", "verbose": "Main and Scottswood"},
"4517": {"id": "MHRYVWTR", "verbose": "McHenry and Vawter"},
"4521": {"id": "CLRPK", "verbose": "Coler and Park"},
"4523": {"id": "NWTNRSRCH", "verbose": "Newton and Research"},
"4525": {"id": "STEWLM", "verbose": "State and William"},
"4526": {"id": "CLTNRSM", "verbose": "Clayton and Rossmoor"},
"4530": {"id": "RACEMN", "verbose": "Race and Main"},
"4532": {"id": "MNCTGRV", "verbose": "Main and Cottage Grove"},
"4533": {"id": "NEILCD", "verbose": "Market Place at Center Drive"},
"4540": {"id": "LNCLNWSCR", "verbose": "Lincoln and Wascher"},
"4543": {"id": "DNCNLGR", "verbose": "Duncan and Lager"},
"4551": {"id": "WHTWRT", "verbose": "White and Wright"},
"4553": {"id": "SPFLDKLYCT", "verbose": "Springfield and Kelly Ct."},
"4555": {"id": "CFDUNI", "verbose": "Country Fair Dr. and University"},
"4557": {"id": "CRSNTSANG", "verbose": "Crescent and Sangamon"},
"4563": {"id": "RNDLFBRAD", "verbose": "Randolph and Bradley"},
"4564": {"id": "NEILVIN", "verbose": "Neil and Vine"},
"4566": {"id": "MATSDVN", "verbose": "Mattis and Devonshire"},
"4572": {"id": "CFDHNDL", "verbose": "Country Fair Dr. at Hundman"},
"4573": {"id": "KBYCRSNT", "verbose": "Kirby and Crescent"},
"4576": {"id": "DVNSNPR", "verbose": "Devonshire and Sandpiper"},
"4588": {"id": "STLYINV", "verbose": "Staley and Inverness"},
"4601": {"id": "LNCLNIN", "verbose": "Lincoln and Indiana"},
"4602": {"id": "HLFX", "verbose": "Halifax"},
"4606": {"id": "UNINEW", "verbose": "University and New"},
"4611": {"id": "DVNDVNCT", "verbose": "Devonshire and Devonshire Ct."},
"4612": {"id": "BRAD", "verbose": "Bradley between Pomona and WLRW"},
"4613": {"id": "PSPCTVIN", "verbose": "Prospect and Vine"},
"4615": {"id": "TCBPSPCT", "verbose": "Town Center and Prospect"},
"4621": {"id": "RACEIA", "verbose": "Race and Iowa"},
"4624": {"id": "AMBMYRA", "verbose": "Amber and Myra Ridge"},
"4625": {"id": "HRTGPK", "verbose": "Bradley at Heritage Park"},
"4631": {"id": "JOHNWLWN", "verbose": "John and Westlawn"},
"4641": {"id": "CFDSPFLD", "verbose": "Springfield and Country Fair Dr."},
"4642": {"id": "GRNGRV", "verbose": "Green and Grove"},
"4645": {"id": "INTNWMK", "verbose": "Interstate and Newmark"},
"4650": {"id": "NEILMKTV", "verbose": "Neil and Marketview"},
"4651": {"id": "TRLSBRN", "verbose": "Trails and Baronry"},
"4652": {"id": "PSPCTMJR", "verbose": "Prospect at Meijer's Ent."},
"4655": {"id": "WHT2ND", "verbose": "White and Second"},
"4662": {"id": "VINMN", "verbose": "Vine and Main"},
"4666": {"id": "MRANLSD", "verbose": "Moraine and Lake Shore Dr"},
"4672": {"id": "HNTRLNR", "verbose": "Hunter and Lanore"},
"4673": {"id": "PABUSEY", "verbose": "Pennsylvania and Busey"},
"4676": {"id": "STP", "verbose": "Colorado at Steer Place"},
"4677": {"id": "WLNTCLMBA", "verbose": "Walnut and Columbia"},
"4711": {"id": "FLFLDR", "verbose": "Florida and Florida Dr."},
"4720": {"id": "PHILOFRLN", "verbose": "Philo and Fairlawn"},
"4722": {"id": "MATSBLOM", "verbose": "Mattis and Bloomington"},
"4723": {"id": "RNDLFWHT", "verbose": "Randolph and White"},
"4726": {"id": "RACEVT", "verbose": "Race and Vermont"},
"4730": {"id": "ANTDOBB", "verbose": "Anthony and Dobbins"},
"4731": {"id": "ILAPTS", "verbose": "Independent Living"},
"4740": {"id": "SPFLDNEW", "verbose": "Springfield and New"},
"4741": {"id": "SWNDPSMN", "verbose": "Sherwin and Persimmon"},
"4746": {"id": "KERCROL", "verbose": "Kerr and Carroll"},
"4747": {"id": "RMNTRMNT", "verbose": "Romine and Tremont"},
"4751": {"id": "DCC", "verbose": "Devonshire Center"},
"4752": {"id": "4THCHAL", "verbose": "Fourth and Chalmers"},
"4754": {"id": "MNHTL", "verbose": "Main and Hartle"},
"4757": {"id": "VINCO", "verbose": "Vine and Colorado"},
"4771": {"id": "MKTVSAMS", "verbose": "Marketview at Sams"},
"4775": {"id": "BDMRGTWN", "verbose": "Broadmoor and Georgetown"},
"4776": {"id": "MATSALTN", "verbose": "Mattis and Alton"},
"4854": {"id": "SSXOKMNT", "verbose": "Sussex and Oakmont"},
"4982": {"id": "NEILTWN", "verbose": "Neil and Twins"},
"5012": {"id": "RACEOR", "verbose": "Race and Oregon"},
"5021": {"id": "HRISFMS", "verbose": "Harris at Franklin Middle School"},
"5023": {"id": "CLTNIRVN", "verbose": "Clayton and Irvine"},
"5024": {"id": "MYFRBDMR", "verbose": "Mayfair and Broadmoor"},
"5030": {"id": "JOHNJACK", "verbose": "John and Jackson"},
"5034": {"id": "STEHSL", "verbose": "State and Hessel Blvd."},
"5042": {"id": "QNWAY1", "verbose": "Queensway"},
"5051": {"id": "DNCNBLR", "verbose": "Duncan and Blair"},
"5053": {"id": "URBMEIJ", "verbose": "Urbana Meijer"},
"5055": {"id": "RACEUA", "verbose": "Race at Urbana Assembly"},
"5062": {"id": "GRNWLS", "verbose": "Green and Willis"},
"5066": {"id": "BNFLDAPT", "verbose": "Brownfield and Airport Rd."},
"5076": {"id": "WLMDGWD", "verbose": "William and Dogwood"},
"5104": {"id": "LGNNEIL", "verbose": "Logan and Neil"},
"5105": {"id": "PALAW", "verbose": "Pennsylvania at Law School"},
"5110": {"id": "BRTTRLSTHFRD", "verbose": "Brittany Trail and Southford"},
"5112": {"id": "UNIWLS", "verbose": "University and Willis"},
"5114": {"id": "FRBRNWTN", "verbose": "Farber and Newton"},
"5115": {"id": "VKINGN", "verbose": "Viking North"},
"5123": {"id": "TLSNINTER", "verbose": "Toalson and Interstate"},
"5125": {"id": "MHRYFLCHR", "verbose": "McHenry and Fletcher"},
"5130": {"id": "FOXSURS", "verbose": "Fox Drive at SURS"},
"5135": {"id": "ROCKWELL", "verbose": "Rockwell"},
"5141": {"id": "PKNSEAST", "verbose": "Perkins and Eastern"},
"5142": {"id": "SPFLDFAIR", "verbose": "Springfield and Fair"},
"5143": {"id": "WLNTTYLR", "verbose": "Walnut and Taylor"},
"5144": {"id": "SLVRFLCHR", "verbose": "Silver and Fletcher"},
"5145": {"id": "ADRSNMFRD", "verbose": "Anderson and Mumford"},
"5150": {"id": "PSPCTINTER", "verbose": "Prospect and Interstate"},
"5151": {"id": "VINOR", "verbose": "Vine and Oregon"},
"5154": {"id": "PKNSHICRS", "verbose": "Perkins and Highcross"},
"5155": {"id": "CLRCHCH", "verbose": "Coler and Church"},
"5159": {"id": "CBLFLDCRL", "verbose": "Cobblefield and Crail"},
"5162": {"id": "KBYSRTFRD", "verbose": "Kirby and Stratford"},
"5164": {"id": "SPFLDKNWD", "verbose": "Springfield and Kenwood"},
"5171": {"id": "JOHNCHI", "verbose": "John and Chicago"},
"5172": {"id": "CHCHNEW", "verbose": "Church and New"},
"5173": {"id": "INTFRBR", "verbose": "Interstate and Farber"},
"5174": {"id": "WDSRCRSNG", "verbose": "Windsor and Crossing Ct."},
"5190": {"id": "CLTNCLW", "verbose": "Clayton and Clearwater"},
"5192": {"id": "JOHNDNCN", "verbose": "John and Duncan"},
"5201": {"id": "MPLPKSANG", "verbose": "Maplepark and Sangamon"},
"5205": {"id": "CTGRVMCHM", "verbose": "Cottage Grove and Mitchem"},
"5210": {"id": "STEBV", "verbose": "State and Buena Vista"},
"5212": {"id": "KBY1ST", "verbose": "Kirby and First"},
"5213": {"id": "RNDLFBRD", "verbose": "Randolph and Beardsley"},
"5214": {"id": "WNCHBLMR", "verbose": "Winchester and Belmore"},
"5220": {"id": "SPFLDRGWY", "verbose": "Springfield and Ridgeway"},
"5221": {"id": "CRSNTSWD", "verbose": "Crescent and Southwood"},
"5222": {"id": "WRTBSLN", "verbose": "Wright and Beslin"},
"5223": {"id": "TRLSCHAT", "verbose": "Trails and Chatham"},
"5224": {"id": "FRVWGRG", "verbose": "Fairview and Gregory"},
"5227": {"id": "BNBLRGDMD", "verbose": "Bonnie Blair and Gold Medal"},
"5231": {"id": "LNCLNIA", "verbose": "Lincoln and Iowa"},
"5232": {"id": "DODSLYBK", "verbose": "Dodson Dr. East and Slayback"},
"5235": {"id": "BSLNRMN", "verbose": "Beslin and Romine"},
"5243": {"id": "EAST", "verbose": "Eastern"},
"5246": {"id": "GRNRNDLF", "verbose": "Green and Randolph"},
"5251": {"id": "UNI1ST", "verbose": "University and First"},
"5252": {"id": "LNCLNCC", "verbose": "Lincoln and College Ct."},
"5255": {"id": "ANTCMBL", "verbose": "Anthony and Campbell"},
"5261": {"id": "KBYGDVWE", "verbose": "Kirby and Grandview Dr. E."},
"5271": {"id": "MKTRPR", "verbose": "Market and Roper"},
"5273": {"id": "MKTPCH", "verbose": "Market and Peach Tree"},
"5276": {"id": "MYFRWTRVN", "verbose": "Mayfair and Weathervane"},
"5295": {"id": "WDSRVIN", "verbose": "Windsor and Vine"},
"5303": {"id": "UNIHKRY", "verbose": "University and Hickory"},
"5305": {"id": "FLADRSN", "verbose": "Florida and Anderson"},
"5311": {"id": "FLMPL", "verbose": "Florida and Maple"},
"5312": {"id": "CHHLCPRTRE", "verbose": "Cherry Hills and Coppertree"},
"5317": {"id": "KBYCRNDO", "verbose": "Kirby and Coronado"},
"5323": {"id": "WDGWDCHCK", "verbose": "Wedgewood and Cherry Creek"},
"5325": {"id": "FLSUN", "verbose": "Sunnycrest Mall"},
"5330": {"id": "MKTGAR", "verbose": "Market St. and Garwood"},
"5333": {"id": "HMTNJFSN", "verbose": "Hamilton and Jefferson"},
"5343": {"id": "UNICTGRV", "verbose": "University and Cottage Grove"},
"5345": {"id": "RACEWASH1", "verbose": "Race and Washington #1"},
"5351": {"id": "JFSNCLMBA", "verbose": "Jefferson and Columbia"},
"5355": {"id": "BNBLRVLR", "verbose": "Bonnie Blair and Valerie"},
"5363": {"id": "CTGRVGRN", "verbose": "Cottage Grove and Green"},
"5367": {"id": "CRSTWDEDHFMN", "verbose": "Crestwood and Edward Hoffman"},
"5374": {"id": "WMBGTRNTN", "verbose": "Williamsburg and Thornton"},
"5377": {"id": "UNI6TH", "verbose": "University and Sixth"},
"5384": {"id": "BNTBRKCBLFLD", "verbose": "Bentbrook and Cobblefield"},
"5400": {"id": "CBRTPK", "verbose": "Colbert Park"},
"5402": {"id": "WLMDNCN", "verbose": "William and Duncan"},
"5405": {"id": "WILLARD", "verbose": "Willard Airport"},
"5412": {"id": "RACEIL", "verbose": "Race and Illinois"},
"5413": {"id": "KRBYMLKN", "verbose": "Kirby and Mullikin"},
"5414": {"id": "BDWYOKLN", "verbose": "Broadway and Oakland"},
"5415": {"id": "GRNMAT", "verbose": "Green and Mathews"},
"5417": {"id": "PKNSIVAN", "verbose": "Perkins at Ivanhoe"},
"5421": {"id": "WDFLDABT", "verbose": "Woodfield and Arbour Town Place"},
"5422": {"id": "6THBRAD", "verbose": "Sixth and Bradley"},
"5426": {"id": "LNCLNPK", "verbose": "Lincoln and Park"},
"5430": {"id": "SWALMART", "verbose": "Savoy Walmart"},
"5432": {"id": "PMNASTANA", "verbose": "Pomona and Santa Ana"},
"5434": {"id": "VINPRRE", "verbose": "Vine and Prairie"},
"5437": {"id": "150DALE", "verbose": "U.S. 150 and Dale"},
"5441": {"id": "JOHNWSTRN", "verbose": "John and Western"},
"5444": {"id": "GLNDVN", "verbose": "Galen and Devonshire"},
"5445": {"id": "SWNDSWNC", "verbose": "Sherwin and Sherwin Cir."},
"5450": {"id": "UNINEIL", "verbose": "University and Neil"},
"5451": {"id": "CRSNTWLM", "verbose": "Crescent and William"},
"5452": {"id": "5THBRAD", "verbose": "Fifth and Bradley"},
"5454": {"id": "DNCNDNL", "verbose": "Duncan and Daniel"},
"5456": {"id": "FRVWLNVW", "verbose": "Fairview and Linview"},
"5457": {"id": "BRNTWDGLDVW", "verbose": "Brentwood and Goldenview"},
"5460": {"id": "RNDLFELS", "verbose": "Randolph and Ells"},
"5461": {"id": "RACEMDW", "verbose": "Race and Meadow"},
"5463": {"id": "ADRSNSNYC", "verbose": "Anderson and Sunnycrest"},
"5466": {"id": "HICRSNDLD", "verbose": "Highcross and Nordland"},
"5474": {"id": "PAVIN", "verbose": "Pennsylvania and Vine"},
"5477": {"id": "BRTTRLMLKN", "verbose": "Brittany Trail and Mullikin"},
"5500": {"id": "CPRRDGBLKHK", "verbose": "Copper Ridge and Blackhawk"},
"5505": {"id": "MKTPLCW", "verbose": "Market Place West"},
"5510": {"id": "LGNWTR", "verbose": "Logan and Water"},
"5511": {"id": "VETMED", "verbose": "Vet-Med"},
"5512": {"id": "KBYCAROL", "verbose": "Kirby and Carolyn"},
"5514": {"id": "JOHNDRPR", "verbose": "John and Draper"},
"5516": {"id": "BRTTRLSTHFRDTR", "verbose": "Brittany Trail and Southford Trace West"},
"5520": {"id": "LNHSTOML", "verbose": "Lyndhurst and Old Maple Lane"},
"5524": {"id": "PAR", "verbose": "Pennsylvania Ave. Residence Hall"},
"5525": {"id": "JOHNJAS", "verbose": "John and James"},
"5531": {"id": "WDSRLYN", "verbose": "Windsor and Lynn"},
"5532": {"id": "WRTHLY", "verbose": "Wright and Healey"},
"5535": {"id": "CHCHRSL", "verbose": "Church and Russell"},
"5540": {"id": "LNCLNFL", "verbose": "Lincoln and Florida"},
"5541": {"id": "BLOMAL", "verbose": "Bloomington and Alabama"},
"5542": {"id": "CROL", "verbose": "Carroll between Community Center and Kerr"},
"5543": {"id": "MLKNTRSTSHR", "verbose": "Mullikin and Trostshire"},
"5551": {"id": "HRDGSTP", "verbose": "Harding at Steer Place"},
"5553": {"id": "VINHRIS", "verbose": "Vine and Harris"},
"5561": {"id": "CLTNHGN", "verbose": "Clayton and Higgins"},
"5562": {"id": "1NE14", "verbose": "First and Northeast Lot E-14"},
"5563": {"id": "KBYCBLFLD", "verbose": "Kirby and Cobblefield"},
"5565": {"id": "CRSNTLWNDL", "verbose": "Crescent and Lawndale"},
"5571": {"id": "5THWASH", "verbose": "Fifth and Washington"},
"5572": {"id": "SPFLDGRGST", "verbose": "Springfield and Gregory St."},
"5573": {"id": "LNHSTMAGN", "verbose": "Lyndhurst and Magnolia Ct."},
"5574": {"id": "MNLYN", "verbose": "Main and Lynn"},
"5576": {"id": "4THARY", "verbose": "Fourth and Armory"},
"5601": {"id": "RMNELLIS", "verbose": "Romine and Ellis"},
"5610": {"id": "1STWDSR", "verbose": "First and Windsor"},
"5612": {"id": "GRGPS", "verbose": "Gregory at Personnel Services"},
"5614": {"id": "KBYPRKHVN", "verbose": "Kirby and Park Haven"},
"5616": {"id": "UICU", "verbose": "U of I Credit Union"},
"5622": {"id": "NEILBRWS", "verbose": "Neil and Burwash"},
"5627": {"id": "PSPCTPNR", "verbose": "Prospect and Pioneer"},
"5631": {"id": "CHHLLKVW", "verbose": "Cherry Hills and Lakeview"},
"5633": {"id": "MLKNDVRBRK", "verbose": "Mullikin and Doverbrook"},
"5634": {"id": "NEILBELL", "verbose": "Neil and Bellefontaine"},
"5640": {"id": "JOHNPINE", "verbose": "John and Pine"},
"5643": {"id": "GWNCHCH", "verbose": "Goodwin and Church"},
"5645": {"id": "MKTPAUL", "verbose": "Market and Paul"},
"5647": {"id": "SPFLDRSL", "verbose": "Springfield and Russell"},
"5651": {"id": "PDYKAM", "verbose": "Peabody at Krannert Art Museum"},
"5653": {"id": "MATSSTNGT", "verbose": "Mattis and Stonegate Dr."},
"5657": {"id": "MKTBRAD", "verbose": "Market St. and Bradley"},
"5663": {"id": "MKTPLCCD", "verbose": "Market Place and Convenience Drive"},
"5664": {"id": "JOHNGLDVW", "verbose": "John and Goldenview"},
"5665": {"id": "GLNHRTN", "verbose": "Galen and Harrington"},
"5667": {"id": "ADRSNCO", "verbose": "Anderson and Colorado"},
"5671": {"id": "KERCNHM", "verbose": "Kerr and Cunningham"},
"5673": {"id": "JOHNTLCV", "verbose": "John and Teal Cove"},
"5677": {"id": "1STSPFLD", "verbose": "First and Springfield"},
"5701": {"id": "SPGHLGLNHL", "verbose": "Springhill and Glenhill"},
"5705": {"id": "MATS", "verbose": "Mattis at Schnucks"},
"5712": {"id": "LNHSTPKLN", "verbose": "Lyndhurst and Park Lane"},
"5714": {"id": "PARACE", "verbose": "Pennsylvania and Race"},
"5721": {"id": "CHCHGRFLD", "verbose": "Church and Garfield"},
"5722": {"id": "WDSRCLV", "verbose": "Windsor at Clark Lindsey Village"},
"5725": {"id": "PSPCTKBY", "verbose": "Prospect and Kirby"},
"5731": {"id": "LNHSTARBR1", "verbose": "Lyndhurst and Arbours Drive South"},
"5735": {"id": "BDWYCHPN", "verbose": "Broadway and Chapin"},
"5736": {"id": "FLJASCHER", "verbose": "Florida and James Cherry"},
"5742": {"id": "ANTMATS", "verbose": "Anthony and Mattis"},
"5743": {"id": "2NDUNI", "verbose": "Second and University"},
"5744": {"id": "PHILOPA", "verbose": "Philo and Pennsylvania"},
"5745": {"id": "MHRYPHILO", "verbose": "McHenry and Philo"},
"5747": {"id": "1STGRG", "verbose": "First and Gregory"},
"5753": {"id": "PSPCTMPL", "verbose": "Prospect and Maple"},
"5755": {"id": "MCRTRCT", "verbose": "MacArthur and MacArthur Ct."},
"5761": {"id": "FRVWBUSEY", "verbose": "Fairview and Busey"},
"5762": {"id": "ARC", "verbose": "Activities and Recreation"},
"5764": {"id": "CNHMTPSN", "verbose": "Cunningham and Thompson"},
"5774": {"id": "VINNV", "verbose": "Vine and Nevada"},
"5873": {"id": "PKMCCLGH", "verbose": "Park and McCullough"},
"5904": {"id": "BRADNEIL", "verbose": "Bradley and Neil"},
"6003": {"id": "LNCLNMI", "verbose": "Lincoln and Michigan"},
"6011": {"id": "CHHLCYPCK", "verbose": "Cherry Hills and Cypress Creek"},
"6012": {"id": "SMITH150", "verbose": "Smith Rd. and U.S. 150"},
"6014": {"id": "BRADWMBG", "verbose": "Bradley and Willliamsburg"},
"6016": {"id": "RACEMTCLR", "verbose": "Race and Montclair"},
"6022": {"id": "LWNDLCENT", "verbose": "Lawndale and Centennial"},
"6023": {"id": "SPFLDCHI", "verbose": "Springfield and Chicago"},
"6025": {"id": "MATSBDMR", "verbose": "Mattis and Broadmoor"},
"6026": {"id": "1STHLY", "verbose": "First and Healey"},
"6033": {"id": "PDKELOTB", "verbose": "Paddock Dr. East at Winfield Village Lot"},
"6035": {"id": "PHILOLRL", "verbose": "Philo and Laurel"},
"6051": {"id": "GWNMN", "verbose": "Goodwin and Main"},
"6052": {"id": "BRADCFD", "verbose": "Bradley and Country Fair Drive"},
"6055": {"id": "WSFLDSANG", "verbose": "Westfield and Sangamon"},
"6056": {"id": "ANTKANK", "verbose": "Anthony and Kankakee"},
"6062": {"id": "STEAVNDL", "verbose": "State and Avondale"},
"6063": {"id": "PSPCTKENT", "verbose": "Prospect and Kent"},
"6100": {"id": "VINBKWD", "verbose": "Vine and Burkwood Ct. W."},
"6103": {"id": "RACEIN", "verbose": "Race and Indiana"},
"6104": {"id": "MYFRGTOWN", "verbose": "Mayfair and Georgetown"},
"6111": {"id": "SWTCHGRSDFDL", "verbose": "Switchgrass and Daffodil"},
"6121": {"id": "STECDR", "verbose": "State and Cedar"},
"6123": {"id": "WSFLDLWNDL", "verbose": "Westfield and Lawndale"},
"6126": {"id": "CLTNDLMR", "verbose": "Clayton and Delmar"},
"6131": {"id": "CRSTWDCLTN", "verbose": "Crestwood and Clayton"},
"6132": {"id": "BRDWLKTCB", "verbose": "Boardwalk and Town Center Blvd"},
"6134": {"id": "SPFLDVNDRN", "verbose": "Springfield and VanDoren"},
"6140": {"id": "NEILANT", "verbose": "Neil and Anthony Dr."},
"6141": {"id": "BDWYFRKLN", "verbose": "Broadway and Franklin"},
"6142": {"id": "LNHSTLNVCT", "verbose": "Lyndhurst and Lyndhurst Village Court"},
"6143": {"id": "SLVRCTGRV", "verbose": "Silver and Cottage Grove"},
"6147": {"id": "MLKNVLA", "verbose": "Mullikin and Villa"},
"6151": {"id": "CTGRVGNWD", "verbose": "Cottage Grove and Glenwood Oaks"},
"6155": {"id": "PLAMCNLY", "verbose": "Paula and McKinley"},
"6161": {"id": "2NDCHCH", "verbose": "Second and Church"},
"6162": {"id": "HRISBLOM", "verbose": "Harris and Bloomington"},
"6163": {"id": "SMRNBVW", "verbose": "Smith and Rainbow View"},
"6165": {"id": "CCRGFVW", "verbose": "Country Club and Golfview"},
"6167": {"id": "VINFRLN", "verbose": "Vine and Fairlawn"},
"6170": {"id": "DNCNVYBK", "verbose": "Duncan and Valleybrook"},
"6173": {"id": "MNMKT", "verbose": "Main and Market"},
"6176": {"id": "WLNTWASH", "verbose": "Walnut and Washington"},
"6201": {"id": "MNDWY", "verbose": "Main and Dewey"},
"6212": {"id": "LNCLNSNST", "verbose": "Lincoln and Sunset"},
"6213": {"id": "UNIVCTR", "verbose": "University and Victor"},
"6216": {"id": "BRADGH", "verbose": "Bradley and Garden Hills"},
"6220": {"id": "PHILOBCLF", "verbose": "Philo and Briarcliff"},
"6222": {"id": "BDWYCCR", "verbose": "Broadway and Country Club"},
"6223": {"id": "SLYBKCRE", "verbose": "Slayback and Carrie"},
"6226": {"id": "DDSNNV", "verbose": "Dodson and Nevada"},
"6231": {"id": "CE", "verbose": "Central High East"},
"6232": {"id": "BRADHGN", "verbose": "Bradley and Hagan"},
"6234": {"id": "WLMKNWD", "verbose": "William and Kenwood"},
"6235": {"id": "UNIDRPR", "verbose": "University and Draper"},
"6236": {"id": "1STARY", "verbose": "First and Armory"},
"6237": {"id": "DNCNSRA", "verbose": "Duncan and Sierra"},
"6242": {"id": "CHEMLS", "verbose": "Chemical and Life Sciences"},
"6246": {"id": "SMITHCRE", "verbose": "Smith and Carrie"},
"6250": {"id": "KBYGRNCFT", "verbose": "Kirby and Greencroft"},
"6257": {"id": "CHCHLYN", "verbose": "Church and Lynn"},
"6262": {"id": "UNIRNDLF", "verbose": "University and Randolph"},
"6265": {"id": "PLAGH", "verbose": "Paula and Garden Hills Drive"},
"6272": {"id": "CTGRVCRWD", "verbose": "Cottage Grove and Crestwood"},
"6273": {"id": "WASHMCRTR", "verbose": "Washington and MacArthur"},
"6276": {"id": "BLOMMCNLY", "verbose": "Bloomington and McKinley"},
"6301": {"id": "MATSSHRDN", "verbose": "Mattis and Sheridan"},
"6306": {"id": "MNENIS", "verbose": "Main and Ennis"},
"6314": {"id": "NEILHSL", "verbose": "Neil and Hessel"},
"6315": {"id": "WNCHGLNK", "verbose": "Winchester and Glenoak"},
"6316": {"id": "FTHLRBT", "verbose": "Foothill and Robert"},
"6320": {"id": "STETRMNT", "verbose": "State and Tremont"},
"6321": {"id": "LNCLNPA", "verbose": "Lincoln and Pennsylvania"},
"6322": {"id": "GRNUBNA", "verbose": "Green and Urbana"},
"6324": {"id": "CTGRVCA", "verbose": "Cottage Grove and California"},
"6325": {"id": "GRNMCNLY", "verbose": "Green and McKinley"},
"6330": {"id": "MLKNCRSGT", "verbose": "Mullikin and Crossgate"},
"6332": {"id": "WLMCENT", "verbose": "William and Centennial"},
"6333": {"id": "KBYVYRD", "verbose": "Kirby and Valley Rd."},
"6334": {"id": "SSTNSMT", "verbose": "Susan Stone and Summit"},
"6335": {"id": "MLKNCPRRG", "verbose": "Mullikin and Copper Ridge"},
"6341": {"id": "SLVRVWTR", "verbose": "Silver and Vawter"},
"6346": {"id": "FRLNPTN", "verbose": "Fairlawn and Patton"},
"6347": {"id": "GLNSSX", "verbose": "Galen and Sussex"},
"6350": {"id": "HRISAL", "verbose": "Harris and Alabama"},
"6352": {"id": "FLLNCLN", "verbose": "Florida and Lincoln"},
"6353": {"id": "SPFLDDNCN", "verbose": "Springfield and Duncan"},
"6357": {"id": "MNBRDY", "verbose": "Main and Brady"},
"6360": {"id": "DDSNWASH", "verbose": "Dodson and Washington"},
"6362": {"id": "RMNEADS", "verbose": "Romine and Eads"},
"6363": {"id": "STEMPL", "verbose": "State and Maple"},
"6365": {"id": "UNIWRT", "verbose": "University and Wright"},
"6367": {"id": "VINSCVL", "verbose": "Vine and Scovill"},
"6374": {"id": "MATSCAMP", "verbose": "Mattis and Camp"},
"6402": {"id": "WDSRBKSR", "verbose": "Windsor and Brookshire"},
"6412": {"id": "SPFLDAFRC", "verbose": "Springfield at Armed Forces Recruiting"},
"6414": {"id": "FRLNGRNT", "verbose": "Fairlawn and Grant Pl."},
"6417": {"id": "WSFLDALTN", "verbose": "Westfield and Alton"},
"6422": {"id": "BRADWLS", "verbose": "Bradley and Willis"},
"6423": {"id": "GRNJNSN", "verbose": "Green and Johnson"},
"6424": {"id": "TRLSPHILO", "verbose": "Trails and Philo"},
"6425": {"id": "NEILWASH", "verbose": "Neil and Washington"},
"6431": {"id": "GRN2ND", "verbose": "Green and Second"},
"6432": {"id": "CHCHSTE", "verbose": "Church and State"},
"6434": {"id": "UNISBN", "verbose": "University and Sabin"},
"6437": {"id": "PNCRSTSTLY", "verbose": "Pinecrest and Staley"},
"6441": {"id": "VINPELL", "verbose": "Vine and Pell Cir."},
"6444": {"id": "BLOMHILND", "verbose": "Bloomington and Highland"},
"6445": {"id": "ALDI150", "verbose": "Aldi at Rt. 150"},
"6446": {"id": "BLBOASWD", "verbose": "Balboa and Southwest Dr."},
"6447": {"id": "ODMIDN", "verbose": "Orchard Downs Mid-Block North"},
"6450": {"id": "VLRALPN", "verbose": "Valerie and Alpine"},
"6453": {"id": "WLMGLDVW", "verbose": "William and Goldenview"},
"6454": {"id": "DVRBLBOA", "verbose": "Dover and Balboa"},
"6455": {"id": "BDMRMCD", "verbose": "Broadmoor and McDonald"},
"6456": {"id": "GRNWRT", "verbose": "Green and Wright"},
"6464": {"id": "SUNNYCREST", "verbose": "Sunnycrest Shopping Center"},
"6465": {"id": "SCWDIL", "verbose": "Scottswood and Illinois"},
"6466": {"id": "PDKWLOTG", "verbose": "Paddock Dr. West at Winfield Village Lot"},
"6467": {"id": "STEHLY", "verbose": "State and Healey"},
"6474": {"id": "MERCFEDEX", "verbose": "Mercury at FedEx"},
"6503": {"id": "CHCHEDWN", "verbose": "Church and Edwin"},
"6506": {"id": "WDSRFNY", "verbose": "Windsor and Phinney"},
"6507": {"id": "HRISHRVRD", "verbose": "Harris and Harvard"},
"6510": {"id": "LNHSTBRWS", "verbose": "Lyndhurst and Burwash"},
"6512": {"id": "CHCHMATS", "verbose": "Church and Mattis"},
"6515": {"id": "PSPCTBAY", "verbose": "Prospect and Baytowne"},
"6516": {"id": "FLADAMS", "verbose": "Florida and Adams"},
"6521": {"id": "MATSCYPS", "verbose": "Mattis and Cypress"},
"6522": {"id": "JOHNECRKCT", "verbose": "John and English Creek Ct."},
"6524": {"id": "PHILOMFRD", "verbose": "Philo and Mumford"},
"6526": {"id": "ANTVP", "verbose": "Anthony Dr. at Value Place"},
"6531": {"id": "SPFLDRYLCT", "verbose": "Springfield and Royal Ct."},
"6532": {"id": "MKTV", "verbose": "Marketview Dr. at Marketview Center"},
"6541": {"id": "PDKWLOTK", "verbose": "Paddock Dr. West at Winfield Village Lot"},
"6542": {"id": "ELMPK", "verbose": "Elm and Park"},
"6543": {"id": "CTGRVBRITN", "verbose": "Cottage Grove and Brighton"},
"6544": {"id": "WRTSTOTN", "verbose": "Wright and Stoughton"},
"6545": {"id": "JOHNFAIR", "verbose": "John and Fair"},
"6552": {"id": "PNCRSTPRTFLD", "verbose": "Pinecrest and Porterfield"},
"6554": {"id": "SSTNMYRA", "verbose": "Susan Stone and Myra Ridge"},
"6555": {"id": "MYNRDKBY", "verbose": "Maynard and Kirby"},
"6556": {"id": "CSQRKNCH", "verbose": "Country Squire and Kinch"},
"6561": {"id": "MNMPL", "verbose": "Main and Maple"},
"6563": {"id": "NEILSPFLD", "verbose": "Neil and Springfield"},
"6565": {"id": "MATSINT", "verbose": "Mattis and Interstate"},
"6566": {"id": "BNFLDPRVW", "verbose": "Brownfield and Prairieview"},
"6570": {"id": "WASHTIM", "verbose": "Washington and Timothy Tr."},
"6572": {"id": "WLMSTFRD", "verbose": "William and Stratford"},
"6575": {"id": "GWNPK", "verbose": "Goodwin and Park"},
"6601": {"id": "MLKNGRVCT", "verbose": "Mullikin and Graves Ct."},
"6603": {"id": "TCA", "verbose": "Town and Country Apts."},
"6610": {"id": "UIIA", "verbose": "Institute of Aviation"},
"6612": {"id": "FOXKLWD", "verbose": "Fox and Knollwood"},
"6613": {"id": "MNWBR", "verbose": "Main and Webber"},
"6614": {"id": "SPFLDBSY", "verbose": "Springfield and Busey"},
"6615": {"id": "BDWYCLD", "verbose": "Broadway and Crystal Lake Dr."},
"6620": {"id": "CTSWIN", "verbose": "Curtis Road at Winfield Village"},
"6622": {"id": "GRGOAK", "verbose": "Gregory and Oak"},
"6626": {"id": "UNILRMN", "verbose": "University and Lierman"},
"6630": {"id": "CBLFDABDN", "verbose": "Cobblefield and Aberdeen"},
"6633": {"id": "PSPCTSHWD", "verbose": "Prospect and Sherwood Terrace"},
"6634": {"id": "JOHNMCNLY", "verbose": "John and McKinley"},
"6635": {"id": "1STCHSTR", "verbose": "First and Chester"},
"6641": {"id": "RLNDDBNS", "verbose": "Roland and Dobbins"},
"6643": {"id": "RNDLFJOHN", "verbose": "Randolph and John"},
"6644": {"id": "WNCHBDMR", "verbose": "Winchester and Broadmoor"},
"6645": {"id": "RNDLFWASH", "verbose": "Randolph and Washington"},
"6652": {"id": "MERCAPLO", "verbose": "Mercury and Apollo Dr."},
"6654": {"id": "SMROAK", "verbose": "St. Mary's Road and Oak"},
"6666": {"id": "NEILKNYN", "verbose": "Neil and Kenyon Road"},
"6673": {"id": "MKTWLACE", "verbose": "Market and Wallace"},
"6674": {"id": "CNHMOKLN", "verbose": "Cunningham and Oakland"},
"6675": {"id": "4THKBY", "verbose": "Fourth and Kirby"},
"6700": {"id": "SLYBKSMITH", "verbose": "Slayback and Smith Rd."},
"6711": {"id": "WHT6TH", "verbose": "White and Sixth"},
"6726": {"id": "GRNBUSEY", "verbose": "Green and Busey"},
"6731": {"id": "PSL", "verbose": "Plant Sciences Lab"},
"6733": {"id": "PKNSRICH", "verbose": "Perkins and Richard"},
"6735": {"id": "4THPA", "verbose": "Fourth and Pennsylvania"},
"6741": {"id": "150UNI", "verbose": "U.S. 150 and University"},
"6751": {"id": "FLPLSNT", "verbose": "Florida and Pleasant Dr."},
"6752": {"id": "FLHLCRST", "verbose": "Florida and Hillcrest"},
"6753": {"id": "MYRAAUTM", "verbose": "Myra Ridge and Autumn Ridge"},
"6764": {"id": "PKNSCROL", "verbose": "Perkins and Carroll"},
"6767": {"id": "CRNDODVR", "verbose": "Coronado and Dover"},
"7011": {"id": "CSQRCT", "verbose": "Country Squire Ct."},
"7024": {"id": "CFDSSI", "verbose": "Country Fair Dr. at Social Security"},
"7025": {"id": "HNTRASTN", "verbose": "Hunter and Austin Dr."},
"7035": {"id": "RNDLFCHAS", "verbose": "Randolph and Charles"},
"7036": {"id": "FLPHILO", "verbose": "Florida and Philo"},
"7050": {"id": "JOHNCSTLTN", "verbose": "John and Castleton"},
"7097": {"id": "CLTNDNCN", "verbose": "Clayton and Duncan"},
"7123": {"id": "MYFROF", "verbose": "Mayfair and Old Farm"},
"7124": {"id": "HLFXMYNRD", "verbose": "Halifax and Maynard"},
"7133": {"id": "MKTUNI", "verbose": "Market and University"},
"7134": {"id": "WASHSCL", "verbose": "Washington School"},
"7137": {"id": "PHILOSCVL", "verbose": "Philo and Scovill"},
"7141": {"id": "PSPCTTRMNT", "verbose": "Prospect and Tremont"},
"7142": {"id": "LCNSRFTHL", "verbose": "Lincolnshire and Foothill"},
"7151": {"id": "MCNLYBRD", "verbose": "McKinley and Beardsley"},
"7155": {"id": "CHCH", "verbose": "Church between New and Prospect"},
"7160": {"id": "WDSRMYRA", "verbose": "Windsor and Myra Ridge"},
"7174": {"id": "PAGWN", "verbose": "Pennsylvania and Goodwin"},
"7175": {"id": "GRNPSPCT", "verbose": "Green and Prospect"},
"7201": {"id": "FLBUSEY", "verbose": "Florida and Busey"},
"7213": {"id": "WASHSMITH", "verbose": "Washington and Smith"},
"7216": {"id": "BDMRLSDED", "verbose": "Broadmoor and Lakeside Dr."},
"7221": {"id": "CROLFD", "verbose": "Carrol Fire Department"},
"7226": {"id": "KBYDWSN", "verbose": "Kirby and Dawson"},
"7233": {"id": "RACEBLSS", "verbose": "Race and Bliss"},
"7234": {"id": "INDIGO", "verbose": "Indigo Place"},
"7243": {"id": "UNILAKE", "verbose": "University and Lake"},
"7244": {"id": "JOHNFRANK", "verbose": "John and Frank"},
"7253": {"id": "PSPCTERKA", "verbose": "Prospect and Eureka"},
"7255": {"id": "RACEGRN", "verbose": "Race and Green"},
"7256": {"id": "BLBOAPSPCT", "verbose": "Balboa and Prospect"},
"7267": {"id": "KBYMATS", "verbose": "Kirby and Mattis"},
"7270": {"id": "SWNDSWNC2", "verbose": "Sherwin and Sherwin Cir 2"},
"7301": {"id": "MERCGEMCT", "verbose": "Mercury and Gemini Ct."},
"7303": {"id": "LGGTBRDN", "verbose": "Leggett and Bardeen"},
"7306": {"id": "MYNDCVTRY", "verbose": "Maynard and Coventry"},
"7311": {"id": "SPFLDCFD", "verbose": "Springfield and Country Fair Dr."},
"7312": {"id": "GWNCLK", "verbose": "Goodwin and Clark"},
"7317": {"id": "ODSS", "verbose": "Orchard Downs South Shelter"},
"7322": {"id": "CRSTWDKTLYN", "verbose": "Crestwood and Katie Lynn"},
"7323": {"id": "PACARL", "verbose": "Pennsylvania and Carle"},
"7331": {"id": "MHRYLYN2", "verbose": "McHenry and Lynn St. #2"},
"7332": {"id": "WDSR", "verbose": "Windsor at Bus Stop Sign"},
"7337": {"id": "LNCLNSMR", "verbose": "Lincoln and St. Marys Rd"},
"7342": {"id": "DNCNSWOOD", "verbose": "Duncan and Southwood"},
"7344": {"id": "WASHLRMN", "verbose": "Washington and Lierman"},
"7345": {"id": "CLTNBLRV", "verbose": "Clayton and Bellerieve"},
"7346": {"id": "CCRDVSN", "verbose": "Country Club and Division"},
"7350": {"id": "MKTPLCNMKT", "verbose": "Market Place North Entrance and Market S"},
"7354": {"id": "PLAJEANNE", "verbose": "Paula and Jeanne"},
"7365": {"id": "BDMRCRSNT", "verbose": "Broadmoor and Crescent"},
"7366": {"id": "TMGTWLWBD", "verbose": "Timbergate and Willow Bend"},
"7403": {"id": "RACEHLMS", "verbose": "Race and Holmes"},
"7411": {"id": "PLAZA", "verbose": "Transit Plaza"},
"7416": {"id": "WNDSRSTLY", "verbose": "Windsor and Staley"},
"7422": {"id": "PSPCTHILL", "verbose": "Prospect and Hill"},
"7423": {"id": "VINGRN", "verbose": "Vine and Green"},
"7424": {"id": "4THSMR", "verbose": "Fourth and St. Mary's"},
"7425": {"id": "TCBMRLND", "verbose": "Town Center and Moreland"},
"7430": {"id": "PHILOCO", "verbose": "Philo and Colorado"},
"7431": {"id": "DNCNRDGWD", "verbose": "Duncan and Ridgewood"},
"7441": {"id": "UNICLR", "verbose": "University and Coler"},
"7443": {"id": "BRADCRVR", "verbose": "Bradley and Carver"},
"7445": {"id": "LCNSR", "verbose": "St. Mathews Parking Lot and Lincolnshire"},
"7455": {"id": "VKINGS", "verbose": "Viking - South"},
"7456": {"id": "FLLCLNWD", "verbose": "Florida and Lincolnwood"},
"7460": {"id": "ADRSNBKWD", "verbose": "Anderson and Burkwood"},
"7461": {"id": "CROLKER", "verbose": "Carroll and Kerr"},
"7464": {"id": "CRSTWDFLNC", "verbose": "Crestwood and Florence"},
"7471": {"id": "WNCHBKTRN", "verbose": "Winchester and Blackthorn"},
"7474": {"id": "MPLPKWLPK", "verbose": "Maplepark and Willowpark"},
"7503": {"id": "BRADMCNLY", "verbose": "Bradley and McKinley"},
"7505": {"id": "MCRTRCA", "verbose": "MacArthur and California"},
"7513": {"id": "KBYNEIL", "verbose": "Kirby and Neil"},
"7515": {"id": "FRVWHRVY", "verbose": "Fairview and Harvey"},
"7522": {"id": "WDSRSCTDL", "verbose": "Windsor and Scotsdale"},
"7524": {"id": "WDSRMYPK", "verbose": "Windsor and Morrissey Park Dr."},
"7526": {"id": "WRDKER", "verbose": "Ward and Kerr"},
"7527": {"id": "PLAJOANE", "verbose": "Paula and Joanne Lane"},
"7533": {"id": "CHCHNEIL", "verbose": "Church and Neil"},
"7542": {"id": "ANTGOODWILL", "verbose": "Anthony Dr. at Goodwill"},
"7543": {"id": "CMBLAZTEC", "verbose": "Campbell and Aztec"},
"7551": {"id": "JPN", "verbose": "Lincoln at Japan House"},
"7555": {"id": "5THCHAL", "verbose": "Fifth and Chalmers"},
"7561": {"id": "BRTTRLKNTNKNL", "verbose": "Brittany Trail and Kensington Knoll"},
"7562": {"id": "BDWYWTR", "verbose": "Broadway and Water"},
"7566": {"id": "CHCHDRPR", "verbose": "Church and Draper"},
"7567": {"id": "RNDLFVIN", "verbose": "Randolph and Vine"},
"7570": {"id": "CLTNHV", "verbose": "Clayton and High View"},
"7573": {"id": "CHHLCTS", "verbose": "Cherry Hills and Curtis"},
"7574": {"id": "WLMOKCRST", "verbose": "William and Oakcrest"},
"7588": {"id": "RACEMUMFRD", "verbose": "Race and Mumford"},
"7620": {"id": "JOHNPRRE", "verbose": "John and Prairie"},
"7622": {"id": "MKTMERC", "verbose": "Market St. and Mercury Dr."},
"7623": {"id": "SGRCFD", "verbose": "Springer and Country Fair Dr."},
"7633": {"id": "PKNSCHKE", "verbose": "Perkins and Cherokee"},
"7634": {"id": "CMBLRLND", "verbose": "Campbell and Roland"},
"7641": {"id": "PAWILEY", "verbose": "Pennsylvania and Wiley Dr."},
"7644": {"id": "CRSGTCHWK", "verbose": "Crossgate and Charwick"},
"7647": {"id": "DVNNL", "verbose": "Devonshire and Noel"},
"7653": {"id": "WNCHBKHVN", "verbose": "Winchester and Brookhaven"},
"7654": {"id": "CHCHWLS", "verbose": "Church and Willis"},
"7665": {"id": "SWCF", "verbose": "Springfield and Southwest Country Fair"},
"7703": {"id": "JOHNPSPCT", "verbose": "John and Prospect"},
"7709": {"id": "CBLFLDEGLWD", "verbose": "Cobblefield and Engelwood"},
"7732": {"id": "SPFLDBRCH", "verbose": "Springfield and Birch"},
"7741": {"id": "WLMMPLPK", "verbose": "William and Maplepark"},
"7751": {"id": "WNCHBRCH", "verbose": "Winchester and Branch"},
"7771": {"id": "PLACYNTHA", "verbose": "Paula and Cynthia"},
"7918": {"id": "MIGRNRDG", "verbose": "Michigan and Green Ridge"},
"7953": {"id": "CTSUS45", "verbose": "Curtis Road and Route 45"},
"8030": {"id": "GRNHGHLND", "verbose": "Green and Highland"},
"8066": {"id": "GRN1ST", "verbose": "Green and First"},
"8078": {"id": "CENTRAL", "verbose": "Central High"},
"8112": {"id": "FLLNCLWD", "verbose": "Florida and Lincolnwood"},
"8268": {"id": "WINDPT", "verbose": "Windward Point"},
"8302": {"id": "SPFLDMATS", "verbose": "Springfield and Mattis"},
"8341": {"id": "CVTRYMYNRD", "verbose": "Coventry and Maynard"},
"8386": {"id": "WINDATMWD", "verbose": "Windward and Autumnwood"},
"8449": {"id": "ELMVIN", "verbose": "Elm and Vine"},
"8553": {"id": "1STJOHN", "verbose": "First and John"},
"8595": {"id": "VALDUN", "verbose": "Valerie Dr. and Duncan"},
"8831": {"id": "GWNOR", "verbose": "Goodwin and Oregon"},
"9105": {"id": "SSXWIND", "verbose": "Sussex and Windward"},
"9108": {"id": "FRHLSTLY", "verbose": "Farhills and Staley"},
"9378": {"id": "WNDVRSMRVW", "verbose": "Wendover and Summerview"},
"9443": {"id": "WNDVRWDSPG", "verbose": "Wendover and Woodspring"},
"9467": {"id": "CBLFLDBLML", "verbose": "Cobblefield and Balmoral"},
"9564": {"id": "FLBRMD", "verbose": "Florida and Bermuda"},
"9616": {"id": "WNDVRCTRYBND", "verbose": "Wendover and Country Bend"},
"9956": {"id": "MYFRLCLNSH", "verbose": "Mayfair and Lincolnshire"},
"9974": {"id": "RMNBRRD", "verbose": "Romine and Beardsley"}
};
