var formatted_route_names = {
	"AIR BUS": "Air Bus",
	"AIR BUS CAMPUS": "Air Bus <span style='font-weight: normal; font-size: 80%'>Campus</span>",
	"AIR BUS EXPRESS": "Air Bus <span style='font-size: 85%'>EXP.</span>",
	"AIR BUS IT": "Air Bus <span style='font-weight: normal; font-size: 80%'>I.T.</span>",
	"AIR BUS PLAZA": "Air Bus <span style='font-weight: normal; font-size: 80%'>Plaza</span>",
	"BLUE": "Blue",
	"BLUE ALTERNATE": "Blue <span style='font-size: 85%'>ALT.</span>",
	"BLUE CAMPUS": "Blue <span style='font-weight: normal; font-size: 80%'>Campus</span>",
	"BRONZE": "Bronze",
	"BRONZE ALTERNATE": "Bronze <span style='font-size: 85%'>ALT.</span>",
	"BRONZE YANKEE RIDGE": "Bronze <span style='font-weight: normal; font-size: 80%'>Yank. Rdg.</span>",
	"BROWN": "Brown",
	"BROWN ALT": "Brown <span style='font-size: 85%'>ALT.</span>",
	"BROWN ALTERNATE": "Brown <span style='font-size: 85%'>ALT.</span>",
	"BROWN IT": "Brown <span style='font-weight: normal; font-size: 80%'>I.T.</span>",
	"GOLD": "Gold",
	"GOLD ALTERNATE": "Gold <span style='font-size: 85%'>ALT.</span>",
	"GOLD E-14": "Gold E-14",
	"GOLD EXPRESS": "Gold <span style='font-size: 85%'>EXP.</span>",
	"GOLD KRANNERT": "Gold <span style='font-weight: normal; font-size: 80%'>Krannert</span>",
	"GOLD LSQ": "Gold <span style='font-weight: normal; font-size: 80%'>LSQ</span>",
	"GOLDHOPPER": "GoldH<span style='font-size: 85%'>OPPER</span>",
	"GREEN": "Green",
	"GREEN ALTERNATE": "Green <span style='font-size: 85%'>ALT.</span>",
	"GREEN EX ALT": "Green <span style='font-size: 85%'>EXP.</span> <span style='font-size: 85%'>ALT.</span>",
	"GREEN EXPRESS": "Green <span style='font-size: 85%'>EXP.</span>",
	"GREEN IT": "Green <span style='font-weight: normal; font-size: 80%'>I.T.</span>",
	"GREEN LSQ": "Green <span style='font-weight: normal; font-size: 80%'>LSQ</span>",
	"GREEN UNION": "Green <span style='font-weight: normal; font-size: 80%'>Union</span>",
	"GREENHOPPER": "GreenH<span style='font-size: 85%'>OPPER</span>",
	"GREENHOPPER I.T.": "GreenH<span style='font-size: 85%'>OP</span>. <span style='font-weight: normal; font-size: 80%'>I.T.</span>",
	"GREY": "Grey",
	"GREY ALTERNATE": "Grey <span style='font-size: 85%'>ALT.</span>",
	"ILLINI": "Illini",
	"ILLINI LIMITED": "Illini <span style='font-size: 85%'>LIMITED</span>",
	"LAVENDER": "Lavender",
	"LAVENDER ALTERNATE": "Lavender <span style='font-size: 85%'>ALT.</span>",
	"LAVENDER EX": "Lavender <span style='font-size: 85%'>EXP.</span>",
	"LAVENDER EX CAMPUS": "Lav. <span style='font-size: 85%'>EXP.</span> <span style='font-weight: normal; font-size: 80%'>Campus</span>",
	"LAVENDER EXPRESS": "Lavender <span style='font-size: 85%'>EXP</span>.",
	"LIME": "Lime",
	"NAVY": "Navy",
	"ORANGE": "Orange",
	"ORANGE IT": "Orange <span style='font-weight: normal; font-size: 80%'>I.T.</span>",
	"ORANGE LSQ": "Orange <span style='font-weight: normal; font-size: 80%'>LSQ</span>",
	"ORANGEHOPPER": "OrangeH<span style='font-size: 85%'>OPPER</span>",
	"ORCHARD DOWNS": "Orchard Downs",
	"PLUM": "Plum",
	"RED": "Red",
	"RED EX": "Red <span style='font-size: 85%'>EXP.</span>",
	"RED EXPRESS": "Red <span style='font-size: 85%'>EXP.</span>",
	"RED IT": "Red <span style='font-weight: normal; font-size: 80%'>I.T.</span>",
	"RED LINCOLN & NEVADA": "Red <span style='font-weight: normal; font-size: 80%'>Lincoln/Nevada</span>",
	"SILVER": "Silver",
	"SILVER LIMITED": "Silver <span style='font-size: 85%'>LIMITED</span>",
	"TEAL": "Teal",
	"TEAL ORCHARD DOWNS": "Teal <span style='font-weight: normal; font-size: 80%'>Orch. Downs</span>",
	"TEAL PAR": "Teal <span style='font-weight: normal; font-size: 80%'>PAR</span>",
	"TRANSPORT": "TranSPORT",
	"YELLOW": "Yellow",
	"YELLOW ALTERNATE": "Yellow <span style='font-size: 85%'>ALT.</span>",
	"YELLOW CAMPUS": "Yellow <span style='font-weight: normal; font-size: 80%'>Campus</span>",
	"YELLOW E-14": "Yellow <span style='font-weight: normal; font-size: 80%'>E-14</span>",
	"YELLOW EXPRESS": "Yellow <span style='font-size: 85%'>EXP.</span>",
	"YELLOW GERTY": "Yellow <span style='font-weight: normal; font-size: 80%'>Gerty</span>",
	"YELLOW IKENBERRY": "Yellow <span style='font-weight: normal; font-size: 80%'>Ikenberry</span>",
	"YELLOW IT": "Yellow <span style='font-weight: normal; font-size: 80%'>I.T.</span>",
	"YELLOW PLAZA": "Yellow <span style='font-weight: normal; font-size: 80%'>Plaza</span>",
	"YELLOWHOPPER": "YellowH<span style='font-size: 85%'>OPPER</span>",
	"YELLOWHOPPER E-14": "YellowH<span style='font-size: 85%'>OP</span>. <span style='font-weight: normal; font-size: 80%'>E-14</span>",
	"YELLOWHOPPER GERTY": "YellowH<span style='font-size: 85%'>OP</span>. <span style='font-weight: normal; font-size: 80%'>Gerty</span>",
};
