var formatted_route_names = {
	"AIR BUS CAMPUS": "Air Bus <span style='font-weight: normal; font-size: 80%'>Campus</span>",
	"AIR BUS EXPRESS": "Air Bus <span style='font-size: 85%'>EXP.</span>",
	"AIR BUS IT": "Air Bus <span style='font-weight: normal; font-size: 80%'>I.T.</span>",
	"AIR BUS PAR": "Air Bus <span style='font-weight: normal; font-size: 80%'>PAR</span>",
	"AIR BUS PLAZA": "Air Bus <span style='font-weight: normal; font-size: 80%'>Plaza</span>",
	"AIR BUS": "Air Bus",
	"BLUE ALTERNATE": "Blue <span style='font-size: 85%'>ALT.</span>",
	"BLUE CAMPUS": "Blue <span style='font-weight: normal; font-size: 80%'>Campus</span>",
	"BLUE": "Blue",
	"BRONZE ALTERNATE": "Bronze <span style='font-size: 85%'>ALT.</span>",
	"BRONZE YANKEE RIDGE": "Bronze <span style='font-weight: normal; font-size: 80%'>Yankee Ridge</span>",
	"BRONZE": "Bronze",
	"BROWN ALT": "Brown <span style='font-size: 85%'>ALT.</span>",
	"BROWN ALTERNATE": "Brown <span style='font-size: 85%'>ALT.</span>",
	"BROWN IT": "Brown <span style='font-weight: normal; font-size: 80%'>I.T.</span>",
	"BROWN": "Brown",
	"GOLD ALTERNATE": "Gold <span style='font-size: 85%'>ALT.</span>",
	"GOLD E-14": "Gold E-14",
	"GOLD EXPRESS": "Gold <span style='font-size: 85%'>EXP.</span>",
	"GOLD KRANNERT": "Gold <span style='font-weight: normal; font-size: 80%'>Krannert</span>",
	"GOLD LSQ": "Gold <span style='font-weight: normal; font-size: 80%'>LSQ</span>",
	"GOLD UNION": "Gold <span style='font-weight: normal; font-size: 80%'>Union</span>",
	"GOLD": "Gold",
	"GOLDHOPPER": "GoldH<span style='font-size: 85%'>OPPER</span>",
	"GREEN ALTERNATE": "Green <span style='font-size: 85%'>ALT.</span>",
	"GREEN CAMPUS": "Green <span style='font-weight: normal; font-size: 80%'>Campus</span>",
	"GREEN CF": "Green <span style='font-weight: normal; font-size: 80%'>C.F.</span>",
	"GREEN EX ALT": "Green <span style='font-size: 85%'>EXP.</span> <span style='font-size: 85%'>ALT.</span>",
	"GREEN EXPRESS": "Green <span style='font-size: 85%'>EXP.</span>",
	"GREEN ILLINI UNION": "Green <span style='font-weight: normal; font-size: 80%'>Union</span>",
	"GREEN IT": "Green <span style='font-weight: normal; font-size: 80%'>I.T.</span>",
	"GREEN LINCOLN SQ": "Green <span style='font-weight: normal; font-size: 80%'>LSQ</span>",
	"GREEN LSQ": "Green <span style='font-weight: normal; font-size: 80%'>LSQ</span>",
	"GREEN MEIJER": "Green <span style='font-weight: normal; font-size: 80%'>Meijer</span>",
	"GREEN SAVANNAH": "Green <span style='font-weight: normal; font-size: 80%'>Savannah</span>",
	"GREEN SCOTTSWOOD": "Green <span style='font-weight: normal; font-size: 80%'>Scottswood</span>",
	"GREEN SUNNYCREST": "Green <span style='font-weight: normal; font-size: 80%'>Sunnycrest</span>",
	"GREEN UNION": "Green <span style='font-weight: normal; font-size: 80%'>Union</span>",
	"GREEN": "Green",
	"GREENHOPPER I.T.": "GreenH<span style='font-size: 85%'>OPPER</span> <span style='font-weight: normal; font-size: 80%'>I.T.</span>",
	"GREENHOPPER IT": "GreenH<span style='font-size: 85%'>OPPER</span> <span style='font-weight: normal; font-size: 80%'>I.T.</span>",
	"GREENHOPPER LSQ": "GreenH<span style='font-size: 85%'>OPPER</span> <span style='font-weight: normal; font-size: 80%'>LSQ</span>",
	"GREENHOPPER": "GreenH<span style='font-size: 85%'>OPPER</span>",
	"GREY ALTERNATE": "Grey <span style='font-size: 85%'>ALT.</span>",
	"GREY": "Grey",
	"ILLINI LIMITED": "Illini <span style='font-size: 85%'>LIMITED</span>",
	"ILLINI": "Illini",
	"LAVENDER ALTERNATE": "Lavender <span style='font-size: 85%'>ALT.</span>",
	"LAVENDER EX CAMPUS": "Lavender <span style='font-size: 85%'>EXP.</span> <span style='font-weight: normal; font-size: 80%'>Campus</span>",
	"LAVENDER EX": "Lavender <span style='font-size: 85%'>EXP.</span>",
	"LAVENDER EXPRESS": "Lavender <span style='font-size: 85%'>EXP</span>.",
	"LAVENDER": "Lavender",
	"LIME": "Lime",
	"NAVY": "Navy",
	"ORANGE IT": "Orange <span style='font-weight: normal; font-size: 80%'>I.T.</span>",
	"ORANGE LSQ": "Orange <span style='font-weight: normal; font-size: 80%'>LSQ</span>",
	"ORANGE": "Orange",
	"ORANGEHOPPER": "OrangeH<span style='font-size: 85%'>OPPER</span>",
	"ORCHARD DOWNS": "Orchard Downs",
	"PINK": "Pink",
	"PLUM": "Plum",
	"RED EX CAMPUS ONLY": "Red <span style='font-size: 85%'>EXP.</span> <span style='font-weight: normal; font-size: 80%'>Campus</span>",
	"RED EX NO MALL": "Red <span style='font-size: 85%'>EXP.</span> <span style='font-weight: normal; font-size: 80%'>No Mall</span>",
	"RED EX": "Red <span style='font-size: 85%'>EXP.</span>",
	"RED EXPRESS": "Red <span style='font-size: 85%'>EXP.</span>",
	"RED IT": "Red <span style='font-weight: normal; font-size: 80%'>I.T.</span>",
	"RED LINCOLN & NEVADA": "Red <span style='font-weight: normal; font-size: 80%'>Lincoln &amp; Nevada</span>",
	"RED": "Red",
	"RUBY": "Ruby",
	"SILVER LIMITED": "Silver <span style='font-size: 85%'>LIMITED</span>",
	"SILVER": "Silver",
	"TEAL ORCHARD DOWNS": "Teal <span style='font-weight: normal; font-size: 80%'>Orchard Downs</span>",
	"TEAL PAR": "Teal <span style='font-weight: normal; font-size: 80%'>PAR</span>",
	"TEAL": "Teal",
	"TRANSPORT": "Tran<span style='font-size: 85%'>SPORT</span>",
	"YELLOW ALTERNATE": "Yellow <span style='font-size: 85%'>ALT.</span>",
	"YELLOW CAMPUS": "Yellow <span style='font-weight: normal; font-size: 80%'>Campus</span>",
	"YELLOW E-14": "Yellow <span style='font-weight: normal; font-size: 80%'>E-14</span>",
	"YELLOW E14": "Yellow <span style='font-weight: normal; font-size: 80%'>E-14</span>",
	"YELLOW EXPRESS": "Yellow <span style='font-size: 85%'>EXP.</span>",
	"YELLOW GERTY": "Yellow <span style='font-weight: normal; font-size: 80%'>Gerty</span>",
	"YELLOW IKENBERRY": "Yellow <span style='font-weight: normal; font-size: 80%'>Ikenberry</span>",
	"YELLOW IT": "Yellow <span style='font-weight: normal; font-size: 80%'>I.T.</span>",
	"YELLOW PLAZA": "Yellow <span style='font-weight: normal; font-size: 80%'>Plaza</span>",
	"YELLOW": "Yellow",
	"YELLOWHOPPER E-14": "YellowH<span style='font-size: 85%'>OPPER</span> <span style='font-weight: normal; font-size: 80%'>E-14</span>",
	"YELLOWHOPPER GERTY": "YellowH<span style='font-size: 85%'>OPPER</span> <span style='font-weight: normal; font-size: 80%'>Gerty</span>",
	"YELLOWHOPPER": "YellowH<span style='font-size: 85%'>OPPER</span>",
};
