var stops = {
"0001": {"id": "VLRMGHN:3", "verbose": "Valerie & Meaghan"},
"0002": {"id": "MCNLYERKA:4", "verbose": "McKinley & Eureka"},
"0005": {"id": "TCBTGT:3", "verbose": "Town Center at Target"},
"0021": {"id": "BLOMPNR:1", "verbose": "Bloomington  at Pioneer Plaza"},
"0055": {"id": "WSFLDWLM:3", "verbose": "Westfield & William"},
"0062": {"id": "MHRYADRSN:4", "verbose": "McHenry & Anderson"},
"0063": {"id": "RLNDAZTEC:4", "verbose": "Roland & Aztec"},
"0066": {"id": "PLAKIRK:3", "verbose": "Paula & Kirk Ln."},
"0067": {"id": "CFDCAMP:4", "verbose": "Countyr Fair Dr. & Camp"},
"0074": {"id": "STEPK:4", "verbose": "State & Park"},
"0076": {"id": "WNCHTMRK:4", "verbose": "Winchester & Tamarack"},
"0102": {"id": "CLTNCRVCR:3", "verbose": "Clayton & Creve Coeur"},
"0112": {"id": "LNCLNVT:2", "verbose": "Lincoln & Vermont"},
"0113": {"id": "FLKNCH:5", "verbose": "Florida & Kinch"},
"0114": {"id": "SLYBKDOD:1", "verbose": "Slayback & Dodson West"},
"0127": {"id": "UWALMART:2", "verbose": "Urbana Walmart"},
"0142": {"id": "MYRARGPK:2", "verbose": "Myra Ridge & Ridge Park"},
"0144": {"id": "MKTPLCN:4", "verbose": "Market Place North Entrance"},
"0153": {"id": "6THPDY:5", "verbose": "Sixth & Peabody"},
"0156": {"id": "GDWNCB:1", "verbose": "Goodwin at Ceramics Building"},
"0173": {"id": "WDFLDCTS:4", "verbose": "Woodfield & Curtis"},
"0202": {"id": "MKTMKTV:8", "verbose": "Market & Marketview"},
"0206": {"id": "CTGRVDE:4", "verbose": "Cottage Grove & Delaware"},
"0211": {"id": "ADRSNELIOT:4", "verbose": "Anderson & Eliot"},
"0212": {"id": "NWTNNWMK:3", "verbose": "Newton & Newmark"},
"0213": {"id": "UNIAVE:2", "verbose": "University Ave Mid Block"},
"0215": {"id": "BRDNTLSN:3", "verbose": "Bardeen & Toalson"},
"0217": {"id": "PKLNCTBRAD:5", "verbose": "Parkland Ct. & Bradley"},
"0223": {"id": "CHCHPSPCT:4", "verbose": "Church & Prospect"},
"0226": {"id": "PADNR:4", "verbose": "Penn & Dorner"},
"0231": {"id": "SWTCHGRSTRLWY:2", "verbose": "Switchgrass & Trailway"},
"0233": {"id": "WNDSRMLKN:5", "verbose": "Windsor & Mullikin"},
"0235": {"id": "STEBRD:4", "verbose": "State & Beardsley"},
"0240": {"id": "WNCHSMC:4", "verbose": "Winchester & Sumac"},
"0241": {"id": "CRSNTROD:4", "verbose": "Crescent & Rodney"},
"0243": {"id": "FRLNCTGRV:6", "verbose": "Fairlawn & Cottage Grove"},
"0245": {"id": "MIKNCH:4", "verbose": "Michigan & Kinch"},
"0256": {"id": "RNDLFSTNAG:2", "verbose": "Randolph & Stanage"},
"0263": {"id": "GRNNEW:3", "verbose": "Green & New"},
"0265": {"id": "CTSMDWBRTN:3", "verbose": "Curtis Meadow & Brighton"},
"0270": {"id": "JOHNNEW:3", "verbose": "John & New"},
"0303": {"id": "SCWDCACT:4", "verbose": "Scottswood & Calif. Ct."},
"0311": {"id": "PSPCTASRD:4", "verbose": "Prospect & Ayrshire"},
"0314": {"id": "PSPCTFRNS:2", "verbose": "Prospect & Francis"},
"0323": {"id": "BDMRLCNPL:3", "verbose": "Broadmoor & Lincoln Pl."},
"0327": {"id": "VINBRKNS:4", "verbose": "Vine & Brookens"},
"0331": {"id": "KBYWAVE:1", "verbose": "Kirby & Waverly"},
"0333": {"id": "SOLO:2", "verbose": "Solo Cup"},
"0334": {"id": "PMNADSK:4", "verbose": "Pomona & Deske Ct."},
"0336": {"id": "VINSRTS:4", "verbose": "Vine & Shurts"},
"0338": {"id": "ITMKT:9", "verbose": "I. T. at Market St."},
"0342": {"id": "1STHZLWD:4", "verbose": "First & Hazelwood"},
"0344": {"id": "ANTHYRK:3", "verbose": "Anthony at Rural King"},
"0347": {"id": "CFS:4", "verbose": "Country Fair South Entrance"},
"0352": {"id": "BDMRGLN:7", "verbose": "Broadmoor & Galen"},
"0353": {"id": "JMS:9", "verbose": "Jefferson Middle School"},
"0356": {"id": "KBYDNCN:7", "verbose": "Kirby & Duncan"},
"0366": {"id": "RACEWASH2:4", "verbose": "Race & Washington #2"},
"0402": {"id": "MCNLYTRMNT:4", "verbose": "McKinley & Tremont"},
"0404": {"id": "RNDLFERKA:2", "verbose": "Randolph & Eureka"},
"0407": {"id": "PSPCTMKTV:4", "verbose": "Prospect & Marketview"},
"0411": {"id": "DNCNSTNBK:8", "verbose": "Duncan & Stoneybrook"},
"0414": {"id": "SPFLDWHTN:1", "verbose": "Springfield & Wheaton"},
"0415": {"id": "WASHCSQR:3", "verbose": "Washington & Country Squire"},
"0427": {"id": "STLYKBY:2", "verbose": "Staley & Kirby"},
"0435": {"id": "WDSRCLSL:3", "verbose": "Windsor & Carlisle"},
"0436": {"id": "MLKNSTNBDG:4", "verbose": "Mullikin & Stonebridge"},
"0443": {"id": "RACESWND:6", "verbose": "Race & Sherwin"},
"0445": {"id": "GRNPINE:3", "verbose": "Green & Pine"},
"0452": {"id": "UNIELM:4", "verbose": "University & Elm"},
"0462": {"id": "CCRAPTS:2", "verbose": "Country Club Rd. at Apts."},
"0463": {"id": "MHRYPND:3", "verbose": "McHenry & Pond"},
"0466": {"id": "CLTNCSV:3", "verbose": "Clayton and Crestview"},
"0496": {"id": "OD#3:2", "verbose": "Orchard Downs #3"},
"0511": {"id": "RMNBRAD:3", "verbose": "Romine & Bradley"},
"0513": {"id": "CRSNTRBR:3", "verbose": "Crescent & Round Barn"},
"0522": {"id": "BNTBRKRVRKNL:1", "verbose": "Bentbrook and Riverknoll"},
"0523": {"id": "STEBRCH:4", "verbose": "State & Birch"},
"0530": {"id": "GLNYKSH:3", "verbose": "Galen & Yorkshire"},
"0543": {"id": "KRANNERT:2", "verbose": "Krannert"},
"0546": {"id": "NEILERKA:4", "verbose": "Neil & Eureka"},
"0547": {"id": "CTGRVHRDG:4", "verbose": "Cottage Grove & Harding"},
"0554": {"id": "SCWDNV:4", "verbose": "Scottswood & Nevada"},
"0560": {"id": "VTKNCH:4", "verbose": "Vermont & Kinch"},
"0563": {"id": "MPLPKWLM:2", "verbose": "Maplepark & William"},
"0564": {"id": "ADRSNHTHN:2", "verbose": "Anderson & Hawthorne"},
"0573": {"id": "WSFLDCRLTN:4", "verbose": "Westfield & Carrelton"},
"0576": {"id": "WMBGWNTN:3", "verbose": "Williamsburg & Winston"},
"0586": {"id": "GRG6TH:7", "verbose": "Gregory & Sixth"},
"0595": {"id": "PKLNBDFD:3", "verbose": "Park Lane and Bedford"},
"0603": {"id": "CBLFLDBDGPT:4", "verbose": "Cobblefield and Bridge Point Dr"},
"0612": {"id": "HNTRCSQR:3", "verbose": "Hunter & Country Squire"},
"0613": {"id": "PAAG:2", "verbose": "Ag. Engineering"},
"0623": {"id": "DEPOT:9", "verbose": "MTD Garage"},
"0626": {"id": "PSPCTBRD:4", "verbose": "Prospect & Beardsley"},
"0632": {"id": "FLDSFRHL:2", "verbose": "Fields South & Farhills"},
"0634": {"id": "CPRRDGMLKN:1", "verbose": "Copper Ridge & Mullikin"},
"0636": {"id": "VINCA:4", "verbose": "Vine & California"},
"0655": {"id": "WDSRCCS:2", "verbose": "Christie Clinic"},
"0660": {"id": "MNLRMN:7", "verbose": "Main & Lierman"},
"0662": {"id": "UNIMATS:6", "verbose": "University & Mattis"},
"0700": {"id": "FOXSTE:4", "verbose": "Fox & State"},
"0724": {"id": "FRVWGWN:3", "verbose": "Fairview & Goodwin"},
"0732": {"id": "KBYGDVWW:3", "verbose": "Kirby & Grandview"},
"0735": {"id": "PAPAR:2", "verbose": "Pennsylvania at PAR"},
"0750": {"id": "JOHNEDWN:3", "verbose": "John & Edwin"},
"0765": {"id": "MNCHSNT:3", "verbose": "Main & Chestnut"},
"0787": {"id": "CLTNHLT:3", "verbose": "Clayton and Hilltop"},
"0795": {"id": "ALPBRAD:5", "verbose": "Alpine & Bradley"},
"1000": {"id": "1SE14:1", "verbose": "First &  Lot E-14"},
"1011": {"id": "PSPCTHVD:4", "verbose": "Prospect & Harvard"},
"1014": {"id": "MN150:7", "verbose": "Main & Rt. 150"},
"1025": {"id": "PSPCTLOW:4", "verbose": "Prospect at Lowes"},
"1026": {"id": "PHILOMI:4", "verbose": "Philo & Michigan"},
"1034": {"id": "SGRPKLNCT:3", "verbose": "Springer & Parkland Ct."},
"1051": {"id": "BRADWLNT:3", "verbose": "Bradley & Walnut"},
"1054": {"id": "SSTNJACT:2", "verbose": "Susan Stone & Jane Ann Ct."},
"1101": {"id": "BRDYGBC:2", "verbose": "Brady at Grace Baptist Church"},
"1132": {"id": "ADRSNSLVR:4", "verbose": "Anderson & Silver"},
"1133": {"id": "NEILEGB:4", "verbose": "Neil & Edgebrook"},
"1134": {"id": "PSPCTPKLN:6", "verbose": "Prospect & Park Ln."},
"1135": {"id": "LSDMYNRD:4", "verbose": "Lakeshore & Maynard"},
"1136": {"id": "BNFLDPKNS:4", "verbose": "Brownfield & Perkins"},
"1141": {"id": "ONESOUTH:1", "verbose": "One Illinois South"},
"1142": {"id": "NEILGAR:4", "verbose": "Neil & Garwood"},
"1143": {"id": "PAADRSN:4", "verbose": "Penn & Anderson"},
"1144": {"id": "SSTNPLN:2", "verbose": "Susan Stone & Plains Ct."},
"1145": {"id": "TMGTCHHL:4", "verbose": "Timbergate & Cherry Hills"},
"1150": {"id": "PSPCTVTRA:4", "verbose": "Prospect & Ventura"},
"1151": {"id": "FLOD:3", "verbose": "Florida & Orchard"},
"1154": {"id": "WASHRAIN:3", "verbose": "Washington & Rainbow Vw"},
"1156": {"id": "PDKWLOTM:2", "verbose": "Winfield Village Lot M"},
"1162": {"id": "CRSNTGRNDL:4", "verbose": "Crescent & Greendale"},
"1164": {"id": "WDSRWIND:3", "verbose": "Windsor & Windward"},
"1166": {"id": "SSXWTRFD:3", "verbose": "Sussex and Waterford"},
"1174": {"id": "CTGRVBKWD:4", "verbose": "Cottage Grove & Burkwood"},
"1175": {"id": "NWTNNBL:3", "verbose": "Newton & Nobel"},
"1211": {"id": "RNDLFHIL:2", "verbose": "Randolph & Hill"},
"1214": {"id": "PKNSCOOK:3", "verbose": "Perkins & Cooks Ln."},
"1216": {"id": "ISWS:2", "verbose": "Water Survey"},
"1217": {"id": "SPFLDEDWN:3", "verbose": "Springfield & Edwin"},
"1221": {"id": "UNIPSPCT:6", "verbose": "University & Prospect"},
"1222": {"id": "RNDLFSPFLD:5", "verbose": "Randolph & Springfield"},
"1223": {"id": "CCSJ:2", "verbose": "County Satellite Jail"},
"1224": {"id": "CPRRDGCPR:1", "verbose": "Copper Ridge & Copper"},
"1226": {"id": "WNDSRLHRST:3", "verbose": "Windsor & Lyndhurst"},
"1232": {"id": "5THERKA:4", "verbose": "Fifth & Eureka"},
"1233": {"id": "MATSGNSQ:4", "verbose": "Mattis & Gentry Square South"},
"1234": {"id": "CHSTRWTR:1", "verbose": "Chester & Water"},
"1241": {"id": "RSRCHHBCO:2", "verbose": "Research at Hobbico"},
"1242": {"id": "GWNNV:4", "verbose": "Goodwin & Nevada"},
"1243": {"id": "CRNDOVTRA:4", "verbose": "Coronado & Ventura"},
"1246": {"id": "TLGRSSWTCHGRS:1", "verbose": "Tallgrass & Switchgrass"},
"1247": {"id": "MATSGVA:2", "verbose": "Garden Village"},
"1250": {"id": "LNVWKLRNY:2", "verbose": "Linview & Killarney"},
"1251": {"id": "JOHNLYN:3", "verbose": "John & Lynn"},
"1252": {"id": "CHHLAPLWD:3", "verbose": "Cherry Hills & Applewood"},
"1253": {"id": "BNBLRSHRN:2", "verbose": "Bonnie Blair & Sharon"},
"1254": {"id": "CRSTWDLDU:4", "verbose": "Crestwood & Ladue"},
"1255": {"id": "5THVIN:4", "verbose": "Fifth & Vine"},
"1256": {"id": "ANTWTRS:5", "verbose": "Anthony & Walters"},
"1262": {"id": "CTGRVPHILO:2", "verbose": "Cottage Grove & Philo"},
"1266": {"id": "UNIMPL:3", "verbose": "University & Maple"},
"1267": {"id": "MPLPKCRLTN:2", "verbose": "Maplepark & Carrelton"},
"1274": {"id": "DSCCLK:2", "verbose": "D.S.C. on Clark"},
"1276": {"id": "CTRYBNDSPGHL:3", "verbose": "Country Bend & Springhill"},
"1312": {"id": "NWTNLGGT:3", "verbose": "Newton & Leggett"},
"1313": {"id": "RNDLFCLARK:2", "verbose": "Randolph & Clark"},
"1314": {"id": "HRISSHWD:4", "verbose": "Harris & Sherwood"},
"1315": {"id": "MISMITH:3", "verbose": "Michigan & Smith"},
"1317": {"id": "VINWASH:4", "verbose": "Vine & Washington"},
"1322": {"id": "JOHNRSL:3", "verbose": "John & Russell"},
"1323": {"id": "UNIMKT:3", "verbose": "University & Market"},
"1324": {"id": "BDWYTPSN:4", "verbose": "Broadway & Thompson"},
"1325": {"id": "PSPCTWASH:4", "verbose": "Prospect & Washington"},
"1327": {"id": "UNIGWN:7", "verbose": "University & Goodwin"},
"1331": {"id": "RLNDWTRS:3", "verbose": "Roland & Walters"},
"1332": {"id": "KBYWSTRN:3", "verbose": "Kirby & Western"},
"1333": {"id": "1STSMR:8", "verbose": "First & St. Mary's"},
"1334": {"id": "MYFRTDR:2", "verbose": "Mayfair & Theodore"},
"1337": {"id": "BDWYBLY:4", "verbose": "Broadway & Bailey"},
"1340": {"id": "PARKVIEW:2", "verbose": "Parkview"},
"1344": {"id": "BNFLDJHN:4", "verbose": "Brownfield & Johnson"},
"1346": {"id": "KBYCRRGWY:3", "verbose": "Kirby & Carriage Way"},
"1347": {"id": "GRNMPL:3", "verbose": "Green & Maple"},
"1350": {"id": "UNIPRRE:3", "verbose": "University & Prairie"},
"1352": {"id": "WNCHASP:4", "verbose": "Winchester & Aspen"},
"1354": {"id": "MATSCHEVY:4", "verbose": "Mattis & Chevy Chase"},
"1355": {"id": "KNCHEASY:4", "verbose": "Kinch & Easy"},
"1356": {"id": "CHCHMCNLY:1", "verbose": "Church & McKinley"},
"1366": {"id": "FAR:1", "verbose": "FAR"},
"1370": {"id": "GRNPRRE:1", "verbose": "Green & Prairie"},
"1374": {"id": "WALMART:2", "verbose": "Walmart"},
"1404": {"id": "STEWHT:4", "verbose": "State & White"},
"1411": {"id": "4THGRG:7", "verbose": "Fourth & Gregory"},
"1412": {"id": "IETC:2", "verbose": "I.E.T.C."},
"1413": {"id": "WDSRRACE:1", "verbose": "Windsor & Race"},
"1414": {"id": "PSPCTCLMBA:4", "verbose": "Prospect & Columbia"},
"1422": {"id": "BCHRMN:4", "verbose": "Beech & Romine"},
"1425": {"id": "UNICHSTR:7", "verbose": "University & Chester"},
"1426": {"id": "BLOMKMRT:6", "verbose": "Bloomington at Home Depot"},
"1427": {"id": "CHCHFAIR:1", "verbose": "Church & Fair"},
"1430": {"id": "GRNRDGWY:3", "verbose": "Green & Ridgeway"},
"1437": {"id": "PKCNTRL:3", "verbose": "Park & Central"},
"1443": {"id": "WNDSRFLDS:3", "verbose": "Windsor & Fields"},
"1444": {"id": "ISR:2", "verbose": "ISR"},
"1451": {"id": "NEILBRD:4", "verbose": "Neil & Beardsley"},
"1454": {"id": "CNVMKT:4", "verbose": "Convenience Dr. & Market"},
"1455": {"id": "GRGLIB:2", "verbose": "Gregory at Library"},
"1456": {"id": "MYRASLVHL:2", "verbose": "Myra Ridge & Silver Hill"},
"1460": {"id": "RACEHIGH:2", "verbose": "Race & High St."},
"1462": {"id": "FLCRTS:3", "verbose": "Florida & Curtiss"},
"1465": {"id": "FRVWLNCLN:4", "verbose": "Fairview & Lincoln"},
"1476": {"id": "UNIASH:1", "verbose": "University & Ash"},
"1494": {"id": "CBLFLDINV:3", "verbose": "Cobblefield and Inverness"},
"1503": {"id": "BNTBRKPNCRST:2", "verbose": "Bentbrook & Pinecrest"},
"1511": {"id": "AMBPHILO:6", "verbose": "Amber & Philo"},
"1512": {"id": "BLOMPSPCT:4", "verbose": "Bloomington & Prospect"},
"1514": {"id": "KNCHRAIN:4", "verbose": "Kinch & Rainbow View"},
"1515": {"id": "JOHNELM:3", "verbose": "John & Elm"},
"1520": {"id": "SLYBKMG:1", "verbose": "Slayback & McGee"},
"1523": {"id": "6THGRG:5", "verbose": "Sixth & Gregory"},
"1531": {"id": "PKRMN:3", "verbose": "Park & Romine"},
"1532": {"id": "JOHNGRFLD:3", "verbose": "John & Garfield"},
"1536": {"id": "LNCLNOR:4", "verbose": "Lincoln & Oregon"},
"1537": {"id": "WASHASH:1", "verbose": "Washington & Ash"},
"1542": {"id": "KBYROSE:3", "verbose": "Kirby & Rose"},
"1546": {"id": "6THCHAL:1", "verbose": "Sixth & Chalmers"},
"1552": {"id": "BNFLDML:4", "verbose": "Brownfield & Mary Lou"},
"1553": {"id": "PLAMATS:6", "verbose": "Paula & Mattis"},
"1554": {"id": "SPFLDHILND:3", "verbose": "Springfield & Highland"},
"1557": {"id": "SWNDYNKR:2", "verbose": "Sherwin & Yankee Ridge"},
"1566": {"id": "BLOMSNST:1", "verbose": "Bloomington & Sunset"},
"1567": {"id": "TCBMNRDS:3", "verbose": "Town Center & Menards"},
"1573": {"id": "JOHNKNWD:4", "verbose": "John & Kenwood"},
"1600": {"id": "DNCNCRSNG:4", "verbose": "Duncan & Crossing Ct."},
"1601": {"id": "WASHSCWD:5", "verbose": "Washington & Scottswood"},
"1605": {"id": "WMBGMATS:1", "verbose": "Williamsburg & Mattis"},
"1611": {"id": "CMBLQNWAY:8", "verbose": "Campbell & Queensway"},
"1613": {"id": "NEILN:4", "verbose": "Neil & North"},
"1614": {"id": "PLAHNYSKL:3", "verbose": "Paula & Honeysuckle"},
"1616": {"id": "CACC:1", "verbose": "Carroll at CACC"},
"1623": {"id": "CRSGTCRSGTCT:3", "verbose": "Crossgate & Crossgate Ct."},
"1625": {"id": "CLTNPMNA:4", "verbose": "Clayton & Pomona"},
"1626": {"id": "BLOMMTDF:3", "verbose": "Bloomington & Mittendorf"},
"1631": {"id": "PSPCTDNSN:4", "verbose": "Prospect & Dennison"},
"1632": {"id": "NEILARC:4", "verbose": "Neil & Arcadia"},
"1633": {"id": "PAKNCH:4", "verbose": "Penn & Kinch"},
"1635": {"id": "DNCNVLR:4", "verbose": "Duncan & Valerie"},
"1636": {"id": "CTGRVWASH:4", "verbose": "Cottage Grove & Washington"},
"1637": {"id": "VINWDSR:5", "verbose": "Vine & Windsor"},
"1640": {"id": "OAKGTY:1", "verbose": "Oak & Gerty"},
"1641": {"id": "RACEWTHL:4", "verbose": "Race & Whitehall Ct."},
"1643": {"id": "VINSNYC:4", "verbose": "Vine & Sunnycrest"},
"1645": {"id": "MNUBNA:3", "verbose": "Main & Urbana"},
"1646": {"id": "BLOMHGN:3", "verbose": "Bloomington & Hagan"},
"1651": {"id": "CHCHPRRE:1", "verbose": "Church & Prairie"},
"1652": {"id": "LNCLNBRAD:4", "verbose": "Lincoln & Bradley"},
"1656": {"id": "BNTBRKGLFCRK:3", "verbose": "Bentbrook & Golf Creek"},
"1661": {"id": "STEJOHN:4", "verbose": "State & John"},
"1662": {"id": "LGN1ST:4", "verbose": "Logan & First"},
"1663": {"id": "MNGLVR:3", "verbose": "Main & Glover"},
"1666": {"id": "BNBLRNNBTH:3", "verbose": "Bonnie Blair & Nancy Beth"},
"1670": {"id": "DDSNIL:2", "verbose": "Dodson & Illinois"},
"1672": {"id": "FLRACE:3", "verbose": "Florida & Race"},
"1675": {"id": "PDKECTS:2", "verbose": "Paddock East & Curtis"},
"1682": {"id": "RACEWDSR:7", "verbose": "Race & Windsor"},
"1714": {"id": "STESTNAG:4", "verbose": "State & Stanage"},
"1717": {"id": "LKVWWTGTN:4", "verbose": "Lakeview & Worthington"},
"1721": {"id": "MATSPRNCTN:2", "verbose": "Mattis & Princeton"},
"1722": {"id": "BNTBRKSTLY:6", "verbose": "Bentbrook & Staley"},
"1725": {"id": "WSFLDSRDN:4", "verbose": "Westfield & Sheridan"},
"1735": {"id": "CB:2", "verbose": "Country Brook"},
"1742": {"id": "BDMRRBT:4", "verbose": "Broadmoor & Robert"},
"1746": {"id": "SPFLDPSPCT:3", "verbose": "Springfield & Prospect"},
"1752": {"id": "CRSNTJOHN:4", "verbose": "Crescent & John"},
"1756": {"id": "1STSTDM:5", "verbose": "1st & Stadium"},
"1774": {"id": "OAK:2", "verbose": "Oak St."},
"1777": {"id": "2NDHILL:4", "verbose": "Second & Hill"},
"1952": {"id": "CFDRP:2", "verbose": "Country Fair Dr. at R.P. Lumber"},
"1961": {"id": "GLNWLSH:4", "verbose": "Galen & Wilshire"},
"1971": {"id": "ANTHYVP:2", "verbose": "Anthony at Value Place"},
"2003": {"id": "MLKNWSTBRGH:4", "verbose": "Mullikin & Westborough"},
"2004": {"id": "WINDWTRFD:4", "verbose": "Windward and Waterford"},
"2006": {"id": "LAR:2", "verbose": "LAR"},
"2009": {"id": "NEILTCA:4", "verbose": "Neil & Town Center Apt."},
"2012": {"id": "STLYAMHT:2", "verbose": "Staley & Amherst"},
"2013": {"id": "HGNDNSN:4", "verbose": "Hagan & Dennison"},
"2015": {"id": "TCBMJR:2", "verbose": "Town Center at Meijer"},
"2021": {"id": "BDWYUNI:4", "verbose": "Broadway & University"},
"2024": {"id": "JOHNDGWD:3", "verbose": "John & Dogwood"},
"2033": {"id": "PHILOHRDG:4", "verbose": "Philo & Harding"},
"2036": {"id": "5THCLMBA:4", "verbose": "Fifth & Columbia"},
"2040": {"id": "WASH2ND:7", "verbose": "Washington & Second"},
"2041": {"id": "NEILHLY:4", "verbose": "Neil & Healey"},
"2054": {"id": "5THBRD:4", "verbose": "Fifth & Beardsley"},
"2061": {"id": "RACEMI:4", "verbose": "Race & Michigan"},
"2062": {"id": "WASH4TH:3", "verbose": "Washington & Fourth"},
"2063": {"id": "MEIJER:1", "verbose": "Meijer Dr. at Meijer"},
"2093": {"id": "GLNSLBY:3", "verbose": "Galen and Salisbury"},
"2101": {"id": "CPRRDGSND:1", "verbose": "Copper Ridge & Sand"},
"2103": {"id": "SMRNEIL:3", "verbose": "St. Mary's & Neil"},
"2111": {"id": "FOXWDSR:4", "verbose": "Fox & Windsor"},
"2112": {"id": "PLAPWRS:3", "verbose": "Paula & Powers"},
"2114": {"id": "BDMRDVD:3", "verbose": "Broadmoor & David"},
"2115": {"id": "IUE:4", "verbose": "Illini Union Engineering Side"},
"2124": {"id": "FOXCE:2", "verbose": "Fox at Community Elements"},
"2126": {"id": "LNCLNCHCH:4", "verbose": "Lincoln & Church"},
"2143": {"id": "LNCLNOH:4", "verbose": "Lincoln & Ohio"},
"2145": {"id": "MPLPKALTN:2", "verbose": "Maplepark & Alton"},
"2146": {"id": "MPLPKLWNDL:1", "verbose": "Maplepark & Lawndale"},
"2147": {"id": "SWTCHGRSWLDFLWR:2", "verbose": "Switchgrass & Wildflower"},
"2152": {"id": "PHILOWDSR:4", "verbose": "Philo & Windsor"},
"2157": {"id": "WDGWDTMGT:3", "verbose": "Wedgewood & Timbergate"},
"2163": {"id": "CHCHMLR:1", "verbose": "Church & Miller"},
"2164": {"id": "CHCHELM:2", "verbose": "Church & Elm"},
"2166": {"id": "RBRCFD:6", "verbose": "Round Barn & Country Fair Dr."},
"2170": {"id": "HZLWDOAK:2", "verbose": "Hazelwood & Oak"},
"2174": {"id": "FLFLCT:3", "verbose": "Florida & Florida Ct."},
"2181": {"id": "MKTLGN:4", "verbose": "Market & Logan"},
"2201": {"id": "MNBRDWY:6", "verbose": "Main & Broadway"},
"2205": {"id": "VINEGRN:2", "verbose": "Vine & Evergreen Ct."},
"2206": {"id": "PAMD:2", "verbose": "Penn & Maryland"},
"2212": {"id": "BRDWLKMJR:2", "verbose": "Boardwalk & Meijer Dr."},
"2213": {"id": "CFDCONE:4", "verbose": "Country Fair Dr. & Cone"},
"2214": {"id": "6THARY:4", "verbose": "Sixth & Armory"},
"2215": {"id": "WASHKNCH:3", "verbose": "Washington & Kinch"},
"2216": {"id": "BNFLDSLYN:4", "verbose": "Brownfield & Sharlyn"},
"2217": {"id": "KBYDODD:1", "verbose": "Kirby & Dodds"},
"2221": {"id": "UNIMCNLY:3", "verbose": "University & McKinley"},
"2222": {"id": "PKMAT:3", "verbose": "Park & Mathews"},
"2223": {"id": "CCRWLLW:3", "verbose": "Country Club & Willow"},
"2224": {"id": "ADRSNFRLN:8", "verbose": "Anderson & Fairlawn"},
"2225": {"id": "HRISMPL:4", "verbose": "Harris & Maple"},
"2227": {"id": "WMBGSTRG:3", "verbose": "Williamsburg & Summit Ridge"},
"2234": {"id": "BRADDNCN:4", "verbose": "Bradley & Duncan"},
"2236": {"id": "CCNH:2", "verbose": "County Nursing Home"},
"2237": {"id": "MYFRSNFR:2", "verbose": "Mayfair & Sandpiper"},
"2242": {"id": "RNDLFAVNDL:2", "verbose": "Randolph & Avondale"},
"2245": {"id": "VINMHRY:4", "verbose": "Vine & McHenry"},
"2247": {"id": "SMRGRIF:3", "verbose": "St. Mary's & Griffith"},
"2252": {"id": "FLCTGRV:4", "verbose": "Florida & Cottage Grove"},
"2255": {"id": "PSPCTFLRPK:2", "verbose": "Prospect & Floral Park"},
"2257": {"id": "WASHHKRY:1", "verbose": "Washington & Hickory"},
"2261": {"id": "LNCLNKING:4", "verbose": "Lincoln & Kettering Park"},
"2264": {"id": "GRNGRGST:3", "verbose": "Green & Gregory"},
"2266": {"id": "MLKNCTSMDW:2", "verbose": "Mullikin & Curtis Meadow"},
"2267": {"id": "WDSRNEIL:7", "verbose": "Windsor & Neil"},
"2270": {"id": "VINELM:3", "verbose": "Vine & Elm"},
"2271": {"id": "LKVWWGWD:5", "verbose": "Lakeview & Wedgewood"},
"2272": {"id": "PSPCTHIL:2", "verbose": "Prospect & Hill"},
"2273": {"id": "ONENORTH:1", "verbose": "One Illinois North"},
"2303": {"id": "GRNRACE:5", "verbose": "Green & Race"},
"2304": {"id": "WNDVRPBLCK:4", "verbose": "Wendover & Pebble Creek"},
"2305": {"id": "NEILHIL:4", "verbose": "Neil & Hill"},
"2306": {"id": "LWNDLBLPK:3", "verbose": "Lawndale & Bellepark"},
"2311": {"id": "ODGHF:4", "verbose": "Orchard & George Huff"},
"2313": {"id": "MATSSTHWD:4", "verbose": "Mattis & Southwood"},
"2315": {"id": "STEVIN:4", "verbose": "State & Vine"},
"2316": {"id": "MHRYLYN:3", "verbose": "McHenry & Lynn"},
"2321": {"id": "CTGRVOR:4", "verbose": "Cottage Grove & Oregon"},
"2323": {"id": "FLRTLG:3", "verbose": "Florida & Rutledge"},
"2325": {"id": "VINGHF:4", "verbose": "Vine & George Huff"},
"2327": {"id": "EASTKER:4", "verbose": "Eastern & Kerr"},
"2332": {"id": "BRADRNDLF:8", "verbose": "Bradley & Randolph"},
"2333": {"id": "BL:2", "verbose": "Big Lots"},
"2335": {"id": "CHCHCRSN:1", "verbose": "Church & Carson"},
"2337": {"id": "5THGRV:4", "verbose": "Fifth & Grove"},
"2341": {"id": "SPFLDPRC:2", "verbose": "Springfield at Phillips Rec. Ctr."},
"2343": {"id": "WHT4TH:3", "verbose": "White & Fourth"},
"2344": {"id": "MJRPSPCT:4", "verbose": "Meijer Drive & Prospect"},
"2345": {"id": "WLRW:2", "verbose": "Bradley at WLRW"},
"2351": {"id": "FRLNERN:3", "verbose": "Fairlawn & Eastern"},
"2352": {"id": "BDWYLST:4", "verbose": "Broadway & Crystal View"},
"2353": {"id": "BRADCLTN:6", "verbose": "Bradley & Clayton"},
"2355": {"id": "CRSNTPKDL:4", "verbose": "Crescent & Parkdale"},
"2356": {"id": "RNDLFMPL:2", "verbose": "Randolph & Maple"},
"2360": {"id": "GDWNMRL:2", "verbose": "Goodwin at Materials Research"},
"2361": {"id": "UHS:2", "verbose": "Urbana High School"},
"2362": {"id": "NEILMSHL:2", "verbose": "Neil & Marshall"},
"2364": {"id": "APTHICRS:3", "verbose": "Airport & Highcross"},
"2365": {"id": "QNWAYRLND:7", "verbose": "Queensway & Roland"},
"2370": {"id": "CLTNHTG:4", "verbose": "Clayton and Heritage"},
"2373": {"id": "WRTCLMBA:4", "verbose": "Wright & Columbia"},
"2375": {"id": "WRTDBLN:2", "verbose": "Wright & Dublin"},
"2401": {"id": "WDSRCHHL:3", "verbose": "Windsor & Cherry Hills"},
"2403": {"id": "RACEMHRY:4", "verbose": "Race & McHenry"},
"2406": {"id": "HGNPNR:4", "verbose": "Hagan & Pioneer"},
"2410": {"id": "SSXSFLD:3", "verbose": "Sussex & Southfield"},
"2411": {"id": "HICRSALC:2", "verbose": "Highcross & Apostalic Life Church"},
"2412": {"id": "MATSANTA:2", "verbose": "Mattis & Anita"},
"2413": {"id": "PKNSRNTRW:3", "verbose": "Perkins & Raintree"},
"2414": {"id": "PACT:1", "verbose": "Pennsylvania Ct."},
"2416": {"id": "WDSRDNBK:3", "verbose": "Windsor & Donnybrook"},
"2421": {"id": "SPFLDWLWN:3", "verbose": "Springfield & Westlawn"},
"2422": {"id": "STLYTRNBRY:2", "verbose": "Staley & Turnberry"},
"2423": {"id": "STEERKA:4", "verbose": "State & Eureka"},
"2431": {"id": "SPFLDEMWD:1", "verbose": "Springfield & Elmwood"},
"2434": {"id": "LNCLNIL:8", "verbose": "Lincoln & Illinois"},
"2435": {"id": "KNCHLH:2", "verbose": "Kinch & Lantern Hill"},
"2437": {"id": "GC:2", "verbose": "Ginger Creek"},
"2441": {"id": "CVTRYRXFRD:4", "verbose": "Coventry & Roxford"},
"2444": {"id": "STMAT:1", "verbose": "St. Mathews"},
"2446": {"id": "BTSLRMN:2", "verbose": "Butzow & Lierman"},
"2450": {"id": "STEUNI:4", "verbose": "State & University"},
"2451": {"id": "GRGDNR:3", "verbose": "Gregory & Dorner"},
"2456": {"id": "CF:2", "verbose": "Country Fair"},
"2460": {"id": "PA6TH:1", "verbose": "Penn & Sixth"},
"2463": {"id": "NVLNCLN:8", "verbose": "Nevada & Lincoln"},
"2466": {"id": "CTSMDWFXBRGH:3", "verbose": "Curtis Meadow & Foxborough"},
"2470": {"id": "MLKNRMGNTN:4", "verbose": "Mullikin & Remington Way"},
"2472": {"id": "GRNISR:1", "verbose": "Green at ISR"},
"2475": {"id": "ADRSNMI:4", "verbose": "Anderson & Michigan"},
"2507": {"id": "DNCNLWNDL:2", "verbose": "Duncan & Lawndale"},
"2512": {"id": "RMNBRD:4", "verbose": "Romine & Bradley"},
"2513": {"id": "HNKHMTN:2", "verbose": "Hancock & Hamilton"},
"2515": {"id": "GLNPLMT:4", "verbose": "Galen & Plymouth"},
"2516": {"id": "CMBLCRT:4", "verbose": "Campbell & Curt"},
"2521": {"id": "MATSUSPS:1", "verbose": "Mattis at Post Office"},
"2524": {"id": "KBYLCLNRD:3", "verbose": "Kirby & Lincoln Rd."},
"2526": {"id": "WDSRDNCN:6", "verbose": "Windsor & Duncan"},
"2527": {"id": "TMPSNPK:1", "verbose": "Thompson Park"},
"2530": {"id": "CRTSWNSTN:3", "verbose": "Curtis & Wynstone"},
"2533": {"id": "JOHNVCTR:3", "verbose": "John & Victor"},
"2534": {"id": "ODMIDS:4", "verbose": "Orchard Downs Mid-South"},
"2543": {"id": "FLLNDN:3", "verbose": "Florida & Linden"},
"2547": {"id": "LNCLNHIL:4", "verbose": "Lincoln & Hill"},
"2551": {"id": "INT1STSTP:2", "verbose": "Insterstate & First Step"},
"2552": {"id": "GLNROSS:4", "verbose": "Galen & Ross"},
"2553": {"id": "NEILCLMBA:4", "verbose": "Neil & Columbia"},
"2554": {"id": "GWNGRG:9", "verbose": "Goodwin & Gregory"},
"2556": {"id": "ADRSNBRTN:4", "verbose": "Anderson & Brighton"},
"2560": {"id": "CHCHRNDLF:3", "verbose": "Church & Randolph"},
"2561": {"id": "MNABD:3", "verbose": "Main & Art Bartell"},
"2562": {"id": "ATRIUM:2", "verbose": "Atrium Apts"},
"2570": {"id": "CTSMDWSTLY:3", "verbose": "Curtis Meadow & Staley"},
"2571": {"id": "LSGS:8", "verbose": "Lincoln Square Garage South"},
"2577": {"id": "BRADHKRY:3", "verbose": "Bradley & Hickory"},
"2602": {"id": "GHFRACE:4", "verbose": "George Huff & Race"},
"2606": {"id": "BDMRLNWD:3", "verbose": "Broadmoor & Lynwood"},
"2612": {"id": "GRNADRSN:3", "verbose": "Green & Anderson"},
"2614": {"id": "KBYBLPK:3", "verbose": "Kirby & Bellepark"},
"2617": {"id": "DNCNHTWD:4", "verbose": "Duncan & Heathwood"},
"2620": {"id": "CNHMPKNS:8", "verbose": "Cunningham & Perkins"},
"2622": {"id": "BRADJAS:3", "verbose": "Bradley & James"},
"2623": {"id": "PLALRKSPR:3", "verbose": "Paula & Larkspur"},
"2624": {"id": "GRGMUM:2", "verbose": "Gregory at Mumford Hall"},
"2626": {"id": "BNFLDCFTN:4", "verbose": "Brownfield & Clifton"},
"2633": {"id": "DNCNCLTN:7", "verbose": "Duncan & Clayton"},
"2634": {"id": "150DOD:5", "verbose": "U.S. 150 & Dodson"},
"2635": {"id": "CLMBANEIL:1", "verbose": "Columbia & Neil"},
"2636": {"id": "BRWSLNST:1", "verbose": "Burwash & Lynhurst"},
"2641": {"id": "WDSRPSPCT:4", "verbose": "Windsor & Prospect"},
"2643": {"id": "CFW:9", "verbose": "Country Fair West Entrance"},
"2644": {"id": "WDSRWWBK:3", "verbose": "Windsor & Willowbrook"},
"2651": {"id": "BDWYKER:4", "verbose": "Broadway & Kerr"},
"2652": {"id": "KBYCMBG:3", "verbose": "Kirby & Cambridge"},
"2654": {"id": "LNHSTARBR:4", "verbose": "Lyndhurst & Arbours"},
"2660": {"id": "SPFLDLYN:3", "verbose": "Springfield & Lynn"},
"2663": {"id": "WLNTMN:2", "verbose": "Walnut & Main"},
"2666": {"id": "DVNLSDED:3", "verbose": "Devonshire & Lakeside"},
"2674": {"id": "WLNTUNI:2", "verbose": "Walnut & University"},
"2703": {"id": "PDKELOTD:2", "verbose": "Winfeld Village Lot D"},
"2714": {"id": "MHRYCTGRV:3", "verbose": "McHenry & Cottage Grove"},
"2715": {"id": "UNIRACE:3", "verbose": "University & Race"},
"2716": {"id": "ANTHYGW:2", "verbose": "Anthony at Goodwill"},
"2733": {"id": "PABDWY:3", "verbose": "Penn & Broadway"},
"2735": {"id": "2NDPK:4", "verbose": "Second & Park"},
"2740": {"id": "NEILINTR:3", "verbose": "Neil & Interstate"},
"2745": {"id": "GRDBTZ:3", "verbose": "Guardian Dr. & Butzow"},
"2746": {"id": "STESPFLD:4", "verbose": "State & Springfield"},
"2754": {"id": "STECLMBA:6", "verbose": "State & Columbia"},
"2761": {"id": "WRTCHCH:4", "verbose": "Wright & Church"},
"2762": {"id": "BLOMLA:3", "verbose": "Bloomington & Louisiana"},
"2764": {"id": "CLMBAHNK:1", "verbose": "Columbia & Hancock"},
"2770": {"id": "MATSWLM:4", "verbose": "Mattis & William"},
"2774": {"id": "WDSRMTRY:3", "verbose": "Windsor & Monterey"},
"2778": {"id": "JOHNHLYCST:3", "verbose": "John & Hollycrest"},
"2872": {"id": "4THBRAD:1", "verbose": "Fourth & Bradley"},
"2961": {"id": "INVPSTWK:3", "verbose": "Inverness and Prestwick Pt"},
"3001": {"id": "UNISCMR:3", "verbose": "University & Sycamore"},
"3003": {"id": "WLMSCTDL:1", "verbose": "William & Scottsdale"},
"3014": {"id": "4THPDY:7", "verbose": "Fourth & Peabody"},
"3036": {"id": "MHRYCMBS:3", "verbose": "McHenry & Combes"},
"3043": {"id": "SSTNGLNA:2", "verbose": "Susan Stone & Galena"},
"3051": {"id": "HICRSBA:4", "verbose": "Highcross & Bruce Acres"},
"3060": {"id": "MCNLYMPL:5", "verbose": "McKinley & Maple"},
"3062": {"id": "UNIFAIR:3", "verbose": "University & Fair"},
"3063": {"id": "DNCNWTRSN:4", "verbose": "Duncan & Watterson"},
"3064": {"id": "MKTKNYN:2", "verbose": "Market & Kenyon"},
"3067": {"id": "BRADRDWD:3", "verbose": "Bradley & Redwood"},
"3072": {"id": "CHHLPNVY:4", "verbose": "Cherry Hills & Pine Valley"},
"3077": {"id": "MLKNIRNWD:2", "verbose": "Mullikin & Ironwood"},
"3100": {"id": "VINIL:4", "verbose": "Vine & Illinois"},
"3102": {"id": "DVNMYFR:3", "verbose": "Devonshire & Mayfair"},
"3103": {"id": "PSPCTBDMR:8", "verbose": "Prospect & Broadmoor"},
"3104": {"id": "MNDDSN:3", "verbose": "Main & Dodson"},
"3105": {"id": "VINWTR:4", "verbose": "Vine & Water"},
"3110": {"id": "LNCLNDE:2", "verbose": "Lincoln & Delaware"},
"3111": {"id": "KBYSCTDL:3", "verbose": "Kirby & Scottsdale"},
"3112": {"id": "FOXDVN:5", "verbose": "Fox & Devonshire"},
"3121": {"id": "IT:4", "verbose": "Illinois Terminal (Platform B)"},
"3123": {"id": "BRADCMI:3", "verbose": "Bradley & Champaign"},
"3124": {"id": "CTRYBNDSUMHL:3", "verbose": "Country Bend & Summerhill"},
"3125": {"id": "BRDYHI:4", "verbose": "Brady & High"},
"3126": {"id": "PSPCTFRAN:4", "verbose": "Prospect & Francis"},
"3127": {"id": "MATSHNRY:2", "verbose": "Mattis & Henry"},
"3135": {"id": "ANTDALE:3", "verbose": "Anthony & Dale"},
"3137": {"id": "KPDLNVW:3", "verbose": "Kettering & Linview"},
"3140": {"id": "MNPLR:3", "verbose": "Main & Poplar"},
"3142": {"id": "MYNRDCMRN:4", "verbose": "Maynard & Cameron"},
"3144": {"id": "MKTPLCS:1", "verbose": "Market Place South"},
"3147": {"id": "WDSRMLRS:3", "verbose": "Windsor & Melrose"},
"3152": {"id": "GLNNWBY:4", "verbose": "Galen & Newbury"},
"3153": {"id": "STECLARK:4", "verbose": "State & Clark"},
"3159": {"id": "CBLFLDGLNBRK:4", "verbose": "Cobblefield and Glenn Brooke"},
"3161": {"id": "FOXREMAX:2", "verbose": "Fox at Remax"},
"3162": {"id": "SPFLD:4", "verbose": "Springfield at Country Fair"},
"3163": {"id": "CCVA:3", "verbose": "College Ct. & Virginia"},
"3164": {"id": "BLGRSSDGGRS:4", "verbose": "Bluegrass & Sedgegrass"},
"3171": {"id": "MKTPLC:1", "verbose": "Market Place"},
"3172": {"id": "BDWYPK:8", "verbose": "Broadway & Park"},
"3201": {"id": "KBYRSWD:3", "verbose": "Kirby & Rosewood"},
"3202": {"id": "SPFLDDRPR:3", "verbose": "Springfield & Draper"},
"3207": {"id": "CPRRDGIRNWD:1", "verbose": "Copper Ridge & Ironwood"},
"3212": {"id": "CCCH:1", "verbose": "Champaign County Court House"},
"3214": {"id": "ODNS:2", "verbose": "Orchard Downs North Shelter"},
"3216": {"id": "PLASTIPAK:2", "verbose": "Plastipak"},
"3223": {"id": "SLYBKIRA:1", "verbose": "Slayback & Ira"},
"3227": {"id": "MCRTRHI:2", "verbose": "MacArthur & High"},
"3232": {"id": "KBYOAK:7", "verbose": "Kirby & Oak"},
"3236": {"id": "BNFLDDON:4", "verbose": "Brownfield & Donald"},
"3237": {"id": "BAYBRDWLK:4", "verbose": "Baytown & Boardwalk"},
"3242": {"id": "UNIRSL:3", "verbose": "University & Russell"},
"3243": {"id": "GRNLYN:3", "verbose": "Green & Lynn"},
"3244": {"id": "CHCHVCTR:1", "verbose": "Church & Victor"},
"3246": {"id": "1STPDY:4", "verbose": "First & Peabody"},
"3250": {"id": "GLNWDSR:6", "verbose": "Galen & Windsor"},
"3252": {"id": "HRISLA:4", "verbose": "Harris & Louisiana"},
"3253": {"id": "IETCMATS:3", "verbose": "I.E.T.C. and Mattis"},
"3254": {"id": "BRADSTE:7", "verbose": "Bradley & State"},
"3260": {"id": "PSPCTDVN:6", "verbose": "Prospect & Devonshire"},
"3261": {"id": "PSPCTLNSH:4", "verbose": "Prospect & Lincolnshire"},
"3262": {"id": "LYNPRK:4", "verbose": "Lynn & Park"},
"3263": {"id": "KBYSTE:4", "verbose": "Kirby & State"},
"3264": {"id": "WNCHBRBY:4", "verbose": "Winchester & Barberry"},
"3271": {"id": "MATSGLNPK:4", "verbose": "Mattis & Glenn Park"},
"3272": {"id": "ILGLN:3", "verbose": "Illinois & Glenn"},
"3274": {"id": "WDSRWEST:2", "verbose": "Windsor West Apts"},
"3304": {"id": "STEELS:4", "verbose": "State & Ells"},
"3305": {"id": "BNBLRAMY:2", "verbose": "Bonnie Blair & Amy"},
"3311": {"id": "GRN4TH:3", "verbose": "Green & Fourth"},
"3313": {"id": "STNBKMRAN:4", "verbose": "Stoneybrook & Moraine"},
"3315": {"id": "SPFLDWLS:3", "verbose": "Springfield & Willis"},
"3317": {"id": "KBYRDGRD:3", "verbose": "Kirby & Ridge"},
"3321": {"id": "MHRYLYNE:3", "verbose": "McHenry and Lynn - East"},
"3324": {"id": "ADRSNHRDG:4", "verbose": "Anderson & Harding"},
"3326": {"id": "PA4TH:1", "verbose": "Pennsylvania & Fourth"},
"3330": {"id": "WRTBCH:2", "verbose": "Wright & Beech"},
"3333": {"id": "DNCNCLKRD:4", "verbose": "Duncan & Clark"},
"3334": {"id": "NEILWLGFRD:4", "verbose": "Neil & Walingford"},
"3336": {"id": "GRNNEIL:8", "verbose": "Green & Neil"},
"3337": {"id": "WASH3RD:3", "verbose": "Washington & Third"},
"3341": {"id": "KERWRD:1", "verbose": "Kerr & Ward"},
"3343": {"id": "GRN6TH:3", "verbose": "Green & Sixth"},
"3344": {"id": "6THTFT:2", "verbose": "Sixth & Lorado Taft"},
"3356": {"id": "UNIVIN:7", "verbose": "University & Vine"},
"3360": {"id": "PMNABRAD:7", "verbose": "Pomona & Bradley"},
"3362": {"id": "JOHNDNCN:3", "verbose": "John & Duncan"},
"3364": {"id": "WHT1ST:3", "verbose": "White & First"},
"3365": {"id": "RNDLFCLMBA:3", "verbose": "Randolph & Columbia"},
"3366": {"id": "BLOMCLLK:1", "verbose": "Bloomington & Clearlake"},
"3371": {"id": "DNCNPMDW:4", "verbose": "Duncan & Prairie Meadow"},
"3374": {"id": "WDSRLKWD:3", "verbose": "Windsor & Lakewood"},
"3376": {"id": "WMBG:2", "verbose": "Williamsburg"},
"3396": {"id": "OD#1:1", "verbose": "Orchard Downs #1"},
"3401": {"id": "WDSRBA:3", "verbose": "Windsor & Bel Air"},
"3407": {"id": "VINMNTCLR:4", "verbose": "Vine & Montclair"},
"3412": {"id": "CRSNTRBM:2", "verbose": "Round Barn Manor"},
"3416": {"id": "CFDPK:4", "verbose": "Country Fair Dr. & Park"},
"3421": {"id": "HRISBRAD:4", "verbose": "Harris & Bradley"},
"3422": {"id": "CRSNTOLA:4", "verbose": "Crescent & Ola"},
"3423": {"id": "KBYALMA:1", "verbose": "Kirby & Alma"},
"3424": {"id": "JOHNMCHLCT:3", "verbose": "John & Mitchell Ct."},
"3432": {"id": "BDWYCM:2", "verbose": "Save A Lot"},
"3435": {"id": "DVNPCH:3", "verbose": "Devonshire & Peach"},
"3441": {"id": "KBYKNWD:3", "verbose": "Kirby & Kenwood"},
"3442": {"id": "COLRCH:1", "verbose": "Colorado & Larch"},
"3443": {"id": "WDSRSTLW:3", "verbose": "Windsor & Stillwater"},
"3444": {"id": "FLWLY:3", "verbose": "Florida & Wiley"},
"3445": {"id": "DNRPDY:4", "verbose": "Dorner & Peabody"},
"3446": {"id": "SPFLDMCNLY:3", "verbose": "Springfield & McKinley"},
"3447": {"id": "RNDLFUNI:2", "verbose": "Randolph & University"},
"3450": {"id": "RACEDE:4", "verbose": "Race & Delaware"},
"3451": {"id": "BRADPSPCT:5", "verbose": "Bradley & Prospect"},
"3452": {"id": "MNFREMNT:3", "verbose": "Main & Fremont"},
"3453": {"id": "WDFLDSV16:4", "verbose": "Woodfield at Savoy 16"},
"3456": {"id": "BRADCRPS:1", "verbose": "Bradley & Crispus"},
"3457": {"id": "PAORCH:3", "verbose": "Penn & Orchard"},
"3460": {"id": "GRG2ND:3", "verbose": "Gregory & Second"},
"3462": {"id": "WLNTBLY:2", "verbose": "Walnut & Bailey"},
"3464": {"id": "VINHLMS:4", "verbose": "Vine & Holmes"},
"3474": {"id": "TRLSFWN:3", "verbose": "Trails & Fawn Hill"},
"3487": {"id": "WINDCNTYSD:4", "verbose": "Windward and Countryside"},
"3501": {"id": "STEWASH:4", "verbose": "State & Washington"},
"3502": {"id": "PATTERSON:2", "verbose": "Patterson"},
"3503": {"id": "MKTBNB:4", "verbose": "Barnes & Noble Books"},
"3504": {"id": "WASHLNR:3", "verbose": "Washington & Lanore"},
"3505": {"id": "CHCHORCD:3", "verbose": "Church & Orchard"},
"3511": {"id": "WDSRWNCH:5", "verbose": "Windsor & Winchester"},
"3513": {"id": "E14:2", "verbose": "Lot E-14"},
"3514": {"id": "CLMBAHKRY:1", "verbose": "Columbia & Hickory"},
"3516": {"id": "HOBBICO:1", "verbose": "Viking at Hobbico"},
"3520": {"id": "PLAZA:1", "verbose": "Transit Plaza (NW Platform)"},
"3521": {"id": "UNI4TH:3", "verbose": "University & Fourth"},
"3527": {"id": "WMBGGH:3", "verbose": "Williamsburg & Garden Hills"},
"3532": {"id": "LNCLNEADS:4", "verbose": "Lincoln & Eads"},
"3534": {"id": "PKLN:1", "verbose": "Parkland College"},
"3537": {"id": "WLMBRNTWD:1", "verbose": "William & Brentwood"},
"3539": {"id": "BNTBRKBBCT:1", "verbose": "Bentbrook and Bentbrook ct"},
"3540": {"id": "BLGRSTLGRS:4", "verbose": "Bluegrass & Tallgrass"},
"3541": {"id": "BLOMWLS:3", "verbose": "Bloomington & Willis"},
"3542": {"id": "MKTPLCSE:4", "verbose": "Market Place Southeast"},
"3544": {"id": "GRNLCST:3", "verbose": "Green & Locust"},
"3552": {"id": "GRNCDR:3", "verbose": "Green & Cedar"},
"3554": {"id": "LUMBER:1", "verbose": "Country Fair Dr. at Hundman Lumber"},
"3556": {"id": "WLMBLPRK:3", "verbose": "William & Bellepark"},
"3562": {"id": "TCBNEIL:8", "verbose": "Town Center & Neil"},
"3565": {"id": "FLSMITH:5", "verbose": "Florida & Smith"},
"3566": {"id": "SPFLDFLRA:1", "verbose": "Springfield & Flora"},
"3571": {"id": "WNCHCYPS:4", "verbose": "Winchester & Cypress"},
"3601": {"id": "RNDLFTRMNT:2", "verbose": "Randolph & Tremont"},
"3602": {"id": "MKTTLP:4", "verbose": "Market & Tulip Tree"},
"3606": {"id": "MDCC:4", "verbose": "Maryland & College Ct"},
"3615": {"id": "RE:4", "verbose": "Highcross & Kyle"},
"3617": {"id": "GRNORCH:3", "verbose": "Green & Orchard"},
"3621": {"id": "VINMCNLY:6", "verbose": "Vine & McKinley"},
"3622": {"id": "CTGRVERN:4", "verbose": "Cottage Grove & Eastern"},
"3623": {"id": "CTGRVSYNC:4", "verbose": "Cottage Grove & Sunnycrest"},
"3624": {"id": "ALPTMBLN:4", "verbose": "Alpine & Timberline"},
"3630": {"id": "MNWLNT:3", "verbose": "Main & Walnut"},
"3632": {"id": "FLSUNAPTS:1", "verbose": "Florida at Sunnycrest Apts."},
"3641": {"id": "BDMRBLMY:3", "verbose": "Broadmoor & Bellamy"},
"3642": {"id": "CFDCHCH:2", "verbose": "Country Fair Dr. & Church"},
"3643": {"id": "GWNHIL:4", "verbose": "Goodwin & Hill"},
"3644": {"id": "RLNDCMCHE:4", "verbose": "Roland & Comanche"},
"3650": {"id": "CRSGTIRNWD:4", "verbose": "Crossgate & Ironwood Ln"},
"3651": {"id": "LNCLNCA:4", "verbose": "Lincoln & California"},
"3652": {"id": "BRWSWDFLD:7", "verbose": "Burwash & Woodfield"},
"3653": {"id": "UNILYN:4", "verbose": "University & Lynn"},
"3655": {"id": "PHILOSLVR:8", "verbose": "Philo & Silver"},
"3656": {"id": "BNFLDCLMBA:4", "verbose": "Brownfield & Columbia"},
"3665": {"id": "BRADELM:3", "verbose": "Bradley & Elm"},
"3675": {"id": "BRADMATS:7", "verbose": "Bradley & Mattis"},
"3703": {"id": "VINLYN:3", "verbose": "Vine & Lynn"},
"3710": {"id": "STETC:4", "verbose": "State & Trade Center Dr."},
"3715": {"id": "CLRFRVW:3", "verbose": "Coler & Fairview"},
"3721": {"id": "SCWDOR:4", "verbose": "Scottswood & Oregon"},
"3723": {"id": "WASHPHLPS:1", "verbose": "Washington & Phillips"},
"3725": {"id": "NEILWHT:4", "verbose": "Neil & White"},
"3729": {"id": "DVNLNWD:1", "verbose": "Devonshire and Lynnwood Dr."},
"3735": {"id": "WDSRIMP:3", "verbose": "Windsor & Imperial"},
"3736": {"id": "PMNAHRTG:4", "verbose": "Pomona & Heritage"},
"3742": {"id": "BLGRSSMRSG:4", "verbose": "Bluegrass & Summersage"},
"3747": {"id": "JOHNMATS:8", "verbose": "John & Mattis"},
"3754": {"id": "RNDLFWLM:2", "verbose": "Randolph & William"},
"3762": {"id": "SPFLDELM:3", "verbose": "Springfield & Elm"},
"3766": {"id": "WRTSPFLD:4", "verbose": "Wright & Springfield"},
"3799": {"id": "CLTNCPT:3", "verbose": "Clayton and Compton"},
"3889": {"id": "SPFLDMAT:3", "verbose": "Springfield & Mathews"},
"3926": {"id": "PKLNSTFD:3", "verbose": "Park Lane and Stanford"},
"4006": {"id": "PSPCTGALN:3", "verbose": "Prospect & Galen"},
"4012": {"id": "UNIWLNT:3", "verbose": "University & Walnut"},
"4013": {"id": "SPFLDHVY:3", "verbose": "Springfield & Harvey"},
"4014": {"id": "ILBDWY:1", "verbose": "Illinois & Broadway"},
"4022": {"id": "RNDLFHLY:2", "verbose": "Randolph & Healey"},
"4024": {"id": "MKTPLCNE:4", "verbose": "Market Place NorthEast"},
"4025": {"id": "UNICENT:3", "verbose": "University & Central"},
"4027": {"id": "CMIHS:1", "verbose": "Champaign House"},
"4031": {"id": "FLBRDWY:1", "verbose": "Florida & Broadway"},
"4037": {"id": "SPFLDGRFLD:3", "verbose": "Springfield & Garfield"},
"4040": {"id": "RMNERKA:4", "verbose": "Romine & Eureka"},
"4043": {"id": "VINMFRD:4", "verbose": "Vine & Mumford"},
"4044": {"id": "NVGRGPL:3", "verbose": "Nevada & Gregory Pl."},
"4045": {"id": "EMS:9", "verbose": "Edison Middle School"},
"4051": {"id": "WRTWASH:4", "verbose": "Wright & Washington"},
"4053": {"id": "LRMNHNTR:4", "verbose": "Lierman & Hunter"},
"4061": {"id": "GRNBRCH:3", "verbose": "Green & Birch"},
"4064": {"id": "MATSSANG:4", "verbose": "Mattis & Sangamon"},
"4066": {"id": "UNIMCLGH:1", "verbose": "University & McCullough"},
"4067": {"id": "GLNTDR:4", "verbose": "Galen & Theodore"},
"4072": {"id": "CHHLBYHL:4", "verbose": "Cherry Hills & Bay Hill"},
"4075": {"id": "KBYDNCN:3", "verbose": "Kirby & Duncan"},
"4100": {"id": "KBYCM:2", "verbose": "Kirby at County Market"},
"4102": {"id": "5THTRMNT:4", "verbose": "Fifth & Tremont"},
"4103": {"id": "GRNSTE:6", "verbose": "Green & State"},
"4105": {"id": "HRISBRD:4", "verbose": "Harris & Beardsley"},
"4112": {"id": "HSLRNDLF:3", "verbose": "Hessel & Randolph"},
"4113": {"id": "CTS1ST:4", "verbose": "Curtis & First"},
"4116": {"id": "PLAMELNE:3", "verbose": "Paula & Melanie"},
"4120": {"id": "VINWLS:3", "verbose": "Vine & Willis"},
"4125": {"id": "FRLN:2", "verbose": "Fairlawn"},
"4130": {"id": "STECHAS:4", "verbose": "State & Charles"},
"4132": {"id": "WMBGSMLN:4", "verbose": "Williamsburg & Summerlin"},
"4135": {"id": "NEILSTDM:2", "verbose": "Neil & Stadium"},
"4140": {"id": "UNIMTD:3", "verbose": "University at MTD"},
"4141": {"id": "CMBLDBNS:4", "verbose": "Campbell & Dobbins"},
"4143": {"id": "MATSWDSR:3", "verbose": "Mattis & Windsor"},
"4144": {"id": "WLMFROAK:1", "verbose": "William & Fairoaks"},
"4145": {"id": "ARYWRT:3", "verbose": "Armory & Wright"},
"4146": {"id": "CTSPDKW:3", "verbose": "Curtis & Paddock West"},
"4149": {"id": "NEILCNTR:4", "verbose": "Neil & Center"},
"4150": {"id": "STEHIL:4", "verbose": "State & Hill"},
"4151": {"id": "KBYMYFR:3", "verbose": "Kirby & Mayfair"},
"4155": {"id": "MCNLYHVAD:4", "verbose": "McKinley & Harvard"},
"4160": {"id": "WDSRVYBK:3", "verbose": "Windsor & Valleybrk"},
"4164": {"id": "WRTCHAL:4", "verbose": "Wright & Chalmers"},
"4176": {"id": "SSTNMOS:2", "verbose": "Susan Stone & Moss"},
"4201": {"id": "GRNLNCLN:3", "verbose": "Green & Lincoln"},
"4203": {"id": "CLTNCVT:4", "verbose": "Clayton and Covington"},
"4205": {"id": "MNVIN:4", "verbose": "Main & Vine"},
"4206": {"id": "FLGRV:3", "verbose": "Florida & Grove"},
"4207": {"id": "DSC:2", "verbose": "Development Services Center"},
"4210": {"id": "UNI2ND:5", "verbose": "University & Second"},
"4215": {"id": "PSPCTASRC:4", "verbose": "Prospect & Ayrshire Cir."},
"4217": {"id": "IT:5", "verbose": "Illinois Terminal (Platform C)"},
"4222": {"id": "RACENV:4", "verbose": "Race & Nevada"},
"4223": {"id": "CTGRVCO:4", "verbose": "Cottage Grove & Colorado"},
"4225": {"id": "LNCLNKLRNY:1", "verbose": "Lincoln & Killarney"},
"4226": {"id": "GRD:1", "verbose": "Butzow at Guardian West"},
"4232": {"id": "ADRSNEVRGN:4", "verbose": "Anderson & Evergreen"},
"4235": {"id": "ASHTON:2", "verbose": "Ashton Woods"},
"4236": {"id": "CHCHJAS:1", "verbose": "Church & James"},
"4241": {"id": "1STGTY:7", "verbose": "First & Gerty"},
"4243": {"id": "RACEMBRK:1", "verbose": "Meadowbrook Park"},
"4244": {"id": "CTGRVIL:4", "verbose": "Cottage Grove & Illinois"},
"4246": {"id": "MNGRV:3", "verbose": "Main & Grove"},
"4247": {"id": "1STE14:8", "verbose": "First & Lot E-14"},
"4255": {"id": "PKWRT:8", "verbose": "Park & Wright"},
"4262": {"id": "GRGIKE:3", "verbose": "Gregory at Ikenberry Commons"},
"4263": {"id": "RACECA:4", "verbose": "Race & California"},
"4272": {"id": "CRSNTJMS:4", "verbose": "Jefferson Middle School"},
"4275": {"id": "SWNDPNDR:2", "verbose": "Sherwin & Pond Ridge"},
"4276": {"id": "WLNTLGN:2", "verbose": "Walnut & Logan"},
"4290": {"id": "OD#2:1", "verbose": "Orchard Downs #2"},
"4304": {"id": "JOHNFOLY:3", "verbose": "John & Foley"},
"4306": {"id": "FLVIN:4", "verbose": "Florida & Vine"},
"4310": {"id": "UMS:9", "verbose": "Urbana Middle School"},
"4315": {"id": "NEILBRAD:2", "verbose": "Neil & Bradley"},
"4322": {"id": "AMBUC:2", "verbose": "Ambucs Park"},
"4325": {"id": "RACEELM:5", "verbose": "Race & Elm"},
"4327": {"id": "GWNSPFLD:7", "verbose": "Goodwin & Springfield"},
"4330": {"id": "SPFLDJAS:3", "verbose": "Springfield & James"},
"4331": {"id": "KBYARW:3", "verbose": "Kirby & Arrow"},
"4333": {"id": "CRSTWDBRAD:3", "verbose": "Crestwood & Bradley"},
"4334": {"id": "BNFLDARL:4", "verbose": "Brownfield & Arlene"},
"4340": {"id": "UNIJAS:3", "verbose": "University & James"},
"4341": {"id": "GRNWBR:3", "verbose": "Green & Webber"},
"4345": {"id": "WDSRJDN:3", "verbose": "Windsor & Jordan"},
"4346": {"id": "KBYWSFLD:3", "verbose": "Kirby & Westfield"},
"4347": {"id": "SPFLDPINE:3", "verbose": "Springfield & Pine"},
"4353": {"id": "PMNAEH:4", "verbose": "Pomona & Ed Hoffman"},
"4360": {"id": "GRNGWN:4", "verbose": "Green & Goodwin"},
"4361": {"id": "1STDAN:6", "verbose": "First & Daniel"},
"4363": {"id": "LNHSTEGRN:4", "verbose": "Lyndhurst & Evergreen Circle"},
"4365": {"id": "CTGRVPA:3", "verbose": "Cottage Grove & Penn"},
"4371": {"id": "TAT130:6", "verbose": "Tatman Ct. & Rt. 130"},
"4373": {"id": "STDMOAK:4", "verbose": "Stadium & Oak"},
"4377": {"id": "MYRATRLS:4", "verbose": "Myra Ridge & Trails"},
"4412": {"id": "MKTBELL:4", "verbose": "Market & Bellefontaine"},
"4421": {"id": "MNSMITH:7", "verbose": "Main & Smith"},
"4424": {"id": "KBYCRGWY:1", "verbose": "Kirby & Carriage Way"},
"4426": {"id": "CMBLCMCHE:4", "verbose": "Campbell & Comanche"},
"4432": {"id": "SPFLDPRRE:3", "verbose": "Springfield & Prairie"},
"4440": {"id": "WNCHSMR:4", "verbose": "Winchester & Southmoor"},
"4441": {"id": "MPLPKMPLWD:2", "verbose": "Maplepark & Maplewood"},
"4443": {"id": "MHRYLYN1:1", "verbose": "McHenry & Lynn St. 1"},
"4446": {"id": "WESTGATE:2", "verbose": "Westgate Apts."},
"4450": {"id": "INTRSRCH:3", "verbose": "Interstate & Research"},
"4451": {"id": "MATSSGR:8", "verbose": "Mattis & Springer"},
"4452": {"id": "MKTVANT:7", "verbose": "Marketview & Anthony"},
"4455": {"id": "UIPS:2", "verbose": "U of I Personnel Services"},
"4456": {"id": "WDSRSSTN:2", "verbose": "Windsor & Susan Stone"},
"4462": {"id": "MCRTRIL:4", "verbose": "MacArthur & Illinois"},
"4463": {"id": "WRTHIL:5", "verbose": "Wright & Hill"},
"4466": {"id": "TMGTPNHST:4", "verbose": "Timbergate & Pinehurst"},
"4470": {"id": "UNICHSNT:3", "verbose": "University & Chestnut"},
"4472": {"id": "CVTRYHLFX:2", "verbose": "Coventry & Halifax"},
"4505": {"id": "3RDDAN:8", "verbose": "Third & Daniel"},
"4511": {"id": "MATSMDWDR:4", "verbose": "Mattis & Meadow"},
"4512": {"id": "LNHSTBDFD:4", "verbose": "Lyndhurst & Bedford"},
"4515": {"id": "MNSCWD:3", "verbose": "Main & Scottswood"},
"4517": {"id": "MHRYVWTR:3", "verbose": "McHenry & Vawter"},
"4521": {"id": "CLRPK:4", "verbose": "Coler & Park"},
"4523": {"id": "NWTNRSRCH:2", "verbose": "Newton & Research"},
"4525": {"id": "STEWLM:4", "verbose": "State & William"},
"4526": {"id": "CLTNRSM:3", "verbose": "Clayton and Rossmoor"},
"4530": {"id": "RACEMN:3", "verbose": "Race & Main"},
"4532": {"id": "MNCTGRV:3", "verbose": "Main & Cottage Grove"},
"4533": {"id": "NEILCD:6", "verbose": "Neil & Center Dr."},
"4540": {"id": "LNCLNWSCR:4", "verbose": "Lincoln & Wascher"},
"4543": {"id": "DNCNLGR:4", "verbose": "Duncan & Lager"},
"4551": {"id": "WHTWRT:8", "verbose": "White & Wright"},
"4553": {"id": "SPFLDKLYCT:1", "verbose": "Springfield & Kelly Ct."},
"4555": {"id": "CFDUNI:4", "verbose": "Country Fair Dr. & University"},
"4557": {"id": "CRSNTSANG:4", "verbose": "Crescent & Sangamon"},
"4563": {"id": "RNDLFBRAD:8", "verbose": "Randolph & Bradley"},
"4564": {"id": "NEILVIN:4", "verbose": "Neil & Vine"},
"4566": {"id": "MATSDVN:6", "verbose": "Mattis & Devonshire"},
"4572": {"id": "CFDHNDL:1", "verbose": "Country Fair Dr. at Hundman"},
"4573": {"id": "KBYCRSNT:4", "verbose": "Kirby & Crescent"},
"4576": {"id": "DVNSNPR:3", "verbose": "Devonshire & Sandpiper"},
"4588": {"id": "STLYINV:2", "verbose": "Staley and Inverness"},
"4601": {"id": "LNCLNIN:4", "verbose": "Lincoln & Indiana"},
"4602": {"id": "HLFX:2", "verbose": "Halifax"},
"4606": {"id": "UNINEW:3", "verbose": "University & New"},
"4611": {"id": "DVNDVNCT:3", "verbose": "Devonshire & Devonshire Ct."},
"4612": {"id": "BRAD:2", "verbose": "Bradley"},
"4613": {"id": "PSPCTVIN:8", "verbose": "Prospect & Vine"},
"4615": {"id": "TCBPSPCT:6", "verbose": "Town Center & Prospect"},
"4621": {"id": "RACEIA:4", "verbose": "Race & Iowa"},
"4624": {"id": "AMBMYRA:4", "verbose": "Amber & Myra Ridge"},
"4625": {"id": "HRTGPK:2", "verbose": "Heritage Park"},
"4631": {"id": "JOHNWLWN:3", "verbose": "John & Westlawn"},
"4641": {"id": "CFDSPFLD:7", "verbose": "Springfield & Country Fair Dr."},
"4642": {"id": "GRNGRV:3", "verbose": "Green & Grove"},
"4645": {"id": "INTNWMK:1", "verbose": "Interstate & Newmark"},
"4650": {"id": "NEILMKTV:4", "verbose": "Neil & Marketview"},
"4651": {"id": "TRLSBRN:3", "verbose": "Trails & Baronry"},
"4652": {"id": "PSPCTMJR:4", "verbose": "Prospect at Meijer"},
"4655": {"id": "WHT2ND:3", "verbose": "White & Second"},
"4662": {"id": "VINMN:3", "verbose": "Vine & Main"},
"4666": {"id": "MRANLSD:3", "verbose": "Moraine & Lake Shore"},
"4672": {"id": "HNTRLNR:3", "verbose": "Hunter & Lanore"},
"4673": {"id": "PABUSEY:3", "verbose": "Penn & Busey"},
"4676": {"id": "STP:1", "verbose": "Colorado at Steer Place"},
"4677": {"id": "WLNTCLMBA:2", "verbose": "Walnut & Columbia"},
"4681": {"id": "MYFRBDMR:4", "verbose": "Mayfair & Broadmoor"},
"4711": {"id": "FLFLDR:3", "verbose": "Florida & Florida Dr."},
"4720": {"id": "PHILOFRLN:8", "verbose": "Philo & Fairlawn"},
"4722": {"id": "MATSBLOM:4", "verbose": "Mattis & Bloomington"},
"4723": {"id": "RNDLFWHT:2", "verbose": "Randolph & White"},
"4726": {"id": "RACEVT:4", "verbose": "Race & Vermont"},
"4730": {"id": "ANTDOBB:4", "verbose": "Anthony & Dobbins"},
"4731": {"id": "ILAPTS:2", "verbose": "Independent Living"},
"4740": {"id": "SPFLDNEW:3", "verbose": "Springfield & New"},
"4741": {"id": "SWNDPSMN:3", "verbose": "Sherwin & Persimmon"},
"4746": {"id": "KERCROL:1", "verbose": "Kerr & Carroll"},
"4747": {"id": "RMNTRMNT:4", "verbose": "Romine & Tremont"},
"4751": {"id": "DCC:2", "verbose": "Devonshire Corporate Center"},
"4752": {"id": "4THCHAL:4", "verbose": "Fourth & Chalmers"},
"4754": {"id": "MNHTL:3", "verbose": "Main & Hartle"},
"4757": {"id": "VINCO:4", "verbose": "Vine & Colorado"},
"4771": {"id": "MKTVSAMS:1", "verbose": "Marketview at Sams"},
"4775": {"id": "BDMRGTWN:1", "verbose": "Broadmoor & Georgetown"},
"4776": {"id": "MATSALTN:4", "verbose": "Mattis & Alton"},
"4854": {"id": "SSXOKMNT:3", "verbose": "Sussex and Oakmont"},
"4982": {"id": "NEILTWN:4", "verbose": "Neil & Twins"},
"5012": {"id": "RACEOR:4", "verbose": "Race & Oregon"},
"5021": {"id": "HRISFMS:2", "verbose": "Franklin Middle School"},
"5023": {"id": "CLTNIRVN:3", "verbose": "Clayton & Irvine"},
"5024": {"id": "MYFRBDMR:2", "verbose": "Mayfair & Broadmoor"},
"5030": {"id": "JOHNJACK:3", "verbose": "John & Jackson"},
"5034": {"id": "STEHSL:6", "verbose": "State & Hessel"},
"5042": {"id": "QNWAY1:2", "verbose": "Queensway"},
"5051": {"id": "DNCNBLR:4", "verbose": "Duncan & Blair"},
"5053": {"id": "URBMEIJ:2", "verbose": "Urbana Meijer"},
"5055": {"id": "RACEUA:2", "verbose": "Race at Urbana Assembly"},
"5062": {"id": "GRNWLS:3", "verbose": "Green & Willis"},
"5066": {"id": "BNFLDAPT:7", "verbose": "Brownfield & Airport"},
"5072": {"id": "JOHNWILS:3", "verbose": "John & Willis"},
"5076": {"id": "WLMDGWD:1", "verbose": "William & Dogwood"},
"5103": {"id": "MKTLGN:4", "verbose": "Market & Logan"},
"5104": {"id": "LGNNEIL:1", "verbose": "Logan & Neil"},
"5105": {"id": "PALAW:1", "verbose": "Pennsylvania at Law Building"},
"5110": {"id": "BRTTRLSTHFRD:1", "verbose": "Brittany Trail & Southford"},
"5112": {"id": "UNIWLS:3", "verbose": "University & Willis"},
"5114": {"id": "FRBRNWTN:3", "verbose": "Farber & Newton"},
"5115": {"id": "VKINGN:1", "verbose": "Viking North"},
"5123": {"id": "TLSNINTER:4", "verbose": "Toalson & Interstate"},
"5125": {"id": "MHRYFLCHR:3", "verbose": "McHenry & Fletcher"},
"5130": {"id": "FOXSURS:2", "verbose": "Fox at SURS"},
"5135": {"id": "ROCKWELL:2", "verbose": "Rockwell"},
"5137": {"id": "LSE:2", "verbose": "Lincoln Square Courthouse"},
"5141": {"id": "PKNSEAST:3", "verbose": "Perkins & Eastern"},
"5142": {"id": "SPFLDFAIR:3", "verbose": "Springfield & Fair"},
"5143": {"id": "WLNTTYLR:2", "verbose": "Walnut & Taylor"},
"5144": {"id": "SLVRFLCHR:3", "verbose": "Silver & Fletcher"},
"5145": {"id": "ADRSNMFRD:4", "verbose": "Anderson & Mumford"},
"5150": {"id": "PSPCTINTER:7", "verbose": "Prospect & Interstate"},
"5151": {"id": "VINOR:4", "verbose": "Vine & Oregon"},
"5154": {"id": "PKNSHICRS:4", "verbose": "Perkins & Highcross"},
"5155": {"id": "CLRCHCH:4", "verbose": "Coler & Church"},
"5159": {"id": "CBLFLDCRL:4", "verbose": "Cobblefield and Crail"},
"5162": {"id": "KBYSRTFRD:3", "verbose": "Kirby & Stratford"},
"5164": {"id": "SPFLDKNWD:7", "verbose": "Springfield & Kenwood"},
"5171": {"id": "JOHNCHI:3", "verbose": "John & Chicago"},
"5172": {"id": "CHCHNEW:1", "verbose": "Church & New"},
"5173": {"id": "INTFRBR:4", "verbose": "Interstate & Farber"},
"5174": {"id": "WDSRCRSNG:1", "verbose": "Windsor & Crossing Ct."},
"5190": {"id": "CLTNCLW:4", "verbose": "Clayton and Clearwater"},
"5192": {"id": "JOHNDNCN:4", "verbose": "John & Duncan"},
"5201": {"id": "MPLPKSANG:2", "verbose": "Maplepark & Sangamon"},
"5205": {"id": "CTGRVMCHM:4", "verbose": "Cottage Grove & Mitchem"},
"5210": {"id": "STEBV:4", "verbose": "State & Buena Vista"},
"5212": {"id": "KBY1ST:5", "verbose": "Kirby & First"},
"5213": {"id": "RNDLFBRD:2", "verbose": "Randolph & Beardsley"},
"5214": {"id": "WNCHBLMR:4", "verbose": "Winchester & Belmore"},
"5220": {"id": "SPFLDRGWY:3", "verbose": "Springfield & Ridgeway"},
"5221": {"id": "CRSNTSWD:4", "verbose": "Crescent & Southwood"},
"5222": {"id": "WRTBSLN:2", "verbose": "Wright & Beslin"},
"5223": {"id": "TRLSCHAT:3", "verbose": "Trails & Chatham"},
"5224": {"id": "FRVWGRG:3", "verbose": "Fairview & Gregory"},
"5227": {"id": "BNBLRGDMD:2", "verbose": "Bonnie Blair & Gold Medal"},
"5231": {"id": "LNCLNIA:4", "verbose": "Lincoln & Iowa"},
"5232": {"id": "DODSLYBK:2", "verbose": "Dodson East & Slayback"},
"5235": {"id": "BSLNRMN:4", "verbose": "Beslin & Romine"},
"5243": {"id": "EAST:2", "verbose": "Eastern"},
"5246": {"id": "GRNRNDLF:3", "verbose": "Green & Randolph"},
"5251": {"id": "UNI1ST:3", "verbose": "University & First"},
"5252": {"id": "LNCLNCC:4", "verbose": "Lincoln & College Ct."},
"5255": {"id": "ANTCMBL:5", "verbose": "Anthony & Campbell"},
"5261": {"id": "KBYGDVWE:1", "verbose": "Kirby & Grandview"},
"5271": {"id": "MKTRPR:4", "verbose": "Market & Roper"},
"5273": {"id": "MKTPCH:4", "verbose": "Market & Peach Tree"},
"5276": {"id": "MYFRWTRVN:2", "verbose": "Mayfair & Weathervane"},
"5295": {"id": "WDSRVIN:6", "verbose": "Windsor & Vine"},
"5303": {"id": "UNIHKRY:3", "verbose": "University & Hickory"},
"5305": {"id": "FLADRSN:4", "verbose": "Florida & Anderson"},
"5311": {"id": "FLMPL:3", "verbose": "Florida & Maple"},
"5312": {"id": "CHHLCPRTRE:3", "verbose": "Cherry Hills & Coppertree"},
"5317": {"id": "KBYCRNDO:7", "verbose": "Kirby & Coronado"},
"5323": {"id": "WDGWDCHCK:3", "verbose": "Wedgewood & Cherry Creek"},
"5325": {"id": "FLSUN:3", "verbose": "Sunnycrest Mall"},
"5330": {"id": "MKTGAR:4", "verbose": "Market & Garwood"},
"5333": {"id": "HMTNJFSN:3", "verbose": "Hamilton & Jefferson"},
"5343": {"id": "UNICTGRV:3", "verbose": "University & Cottage Grove"},
"5345": {"id": "RACEWASH1:2", "verbose": "Race & Washington #1"},
"5351": {"id": "JFSNCLMBA:4", "verbose": "Jefferson and Columbia"},
"5355": {"id": "BNBLRVLR:1", "verbose": "Bonnie Blair & Valerie"},
"5363": {"id": "CTGRVGRN:3", "verbose": "Cottage Grove & Green"},
"5367": {"id": "CRSTWDEDHFMN:4", "verbose": "Crestwood & Edward Hoffman"},
"5374": {"id": "WMBGTRNTN:3", "verbose": "Williamsburg & Thornton"},
"5377": {"id": "UNI6TH:3", "verbose": "University & Sixth"},
"5384": {"id": "BNTBRKCBLFLD:1", "verbose": "Bentbrook and Cobblefield"},
"5400": {"id": "CBRTPK:2", "verbose": "Colbert Park"},
"5402": {"id": "WLMDNCN:4", "verbose": "William & Duncan"},
"5404": {"id": "PLAZA:3", "verbose": "Transit Plaza (SW Platform)"},
"5405": {"id": "WILLARD:1", "verbose": "Willard Airport"},
"5412": {"id": "RACEIL:7", "verbose": "Race & Illinois"},
"5413": {"id": "KRBYMLKN:7", "verbose": "Kirby and Mullikin"},
"5414": {"id": "BDWYOKLN:4", "verbose": "Broadway & Oakland"},
"5415": {"id": "GRNMAT:3", "verbose": "Green & Mathews"},
"5417": {"id": "PKNSIVAN:3", "verbose": "Perkins & Ivanhoe"},
"5421": {"id": "WDFLDABT:4", "verbose": "Woodfield & Arbor Town"},
"5422": {"id": "6THBRAD:3", "verbose": "Sixth & Bradley"},
"5426": {"id": "LNCLNPK:4", "verbose": "Lincoln & Park"},
"5430": {"id": "SWALMART:1", "verbose": "Savoy Walmart"},
"5432": {"id": "PMNASTANA:4", "verbose": "Pomona & Santa Ana"},
"5434": {"id": "VINPRRE:3", "verbose": "Vine & Prairie"},
"5437": {"id": "150DALE:3", "verbose": "U.S. 150 & Dale"},
"5441": {"id": "JOHNWSTRN:3", "verbose": "John & Western"},
"5444": {"id": "GLNDVN:4", "verbose": "Galen & Devonshire"},
"5445": {"id": "SWNDSWNC:4", "verbose": "Sherwin & Sherwin Cir."},
"5450": {"id": "UNINEIL:3", "verbose": "University & Neil"},
"5451": {"id": "CRSNTWLM:4", "verbose": "Crescent & William"},
"5452": {"id": "5THBRAD:7", "verbose": "Fifth & Bradley"},
"5454": {"id": "DNCNDNL:4", "verbose": "Duncan & Daniel"},
"5456": {"id": "FRVWLNVW:3", "verbose": "Fairview & Linview"},
"5457": {"id": "BRNTWDGLDVW:2", "verbose": "Brentwood & Goldenview"},
"5460": {"id": "RNDLFELS:2", "verbose": "Randolph & Ells"},
"5461": {"id": "RACEMDW:4", "verbose": "Race & Meadow"},
"5463": {"id": "ADRSNSNYC:4", "verbose": "Anderson & Sunnycrest"},
"5466": {"id": "HICRSNDLD:4", "verbose": "Highcross & Nordland"},
"5474": {"id": "PAVIN:8", "verbose": "Penn & Vine"},
"5477": {"id": "BRTTRLMLKN:4", "verbose": "Brittany Trail & Mullikin"},
"5500": {"id": "CPRRDGBLKHK:1", "verbose": "Copper Ridge & Blackhawk"},
"5505": {"id": "MKTPLCW:4", "verbose": "Market Place West"},
"5510": {"id": "LGNWTR:3", "verbose": "Logan & Water"},
"5511": {"id": "VETMED:1", "verbose": "Vet-Med"},
"5512": {"id": "KBYCAROL:3", "verbose": "Kirby & Carolyn"},
"5514": {"id": "JOHNDRPR:3", "verbose": "John & Draper"},
"5516": {"id": "BRTTRLSTHFRDTR:1", "verbose": "Brittany Trail & Southford Trace West"},
"5520": {"id": "LNHSTOML:4", "verbose": "Lyndhurst & Old Maple Lane"},
"5524": {"id": "PAR:2", "verbose": "PAR"},
"5525": {"id": "JOHNJAS:3", "verbose": "John & James"},
"5531": {"id": "WDSRLYN:3", "verbose": "Windsor & Lynn"},
"5532": {"id": "WRTHLY:4", "verbose": "Wright & Healey"},
"5535": {"id": "CHCHRSL:1", "verbose": "Church & Russell"},
"5540": {"id": "LNCLNFL:6", "verbose": "Lincoln & Florida"},
"5541": {"id": "BLOMAL:3", "verbose": "Bloomington & Alabama"},
"5542": {"id": "CROL:1", "verbose": "Carroll"},
"5543": {"id": "MLKNTRSTSHR:2", "verbose": "Mullikin & Trostshire"},
"5551": {"id": "HRDGSTP:2", "verbose": "Steer Place"},
"5553": {"id": "VINHRIS:4", "verbose": "Vine & Harris"},
"5561": {"id": "CLTNHGN:4", "verbose": "Clayton and Higgins"},
"5562": {"id": "1NE14:1", "verbose": "First & E-14"},
"5563": {"id": "KBYCBLFLD:4", "verbose": "Kirby and Cobblefield"},
"5565": {"id": "CRSNTLWNDL:4", "verbose": "Crescent & Lawndale"},
"5571": {"id": "5THWASH:4", "verbose": "Fifth & Washington"},
"5572": {"id": "SPFLDGRGST:3", "verbose": "Springfield & Gregory St."},
"5573": {"id": "LNHSTMAGN:4", "verbose": "Lyndhurst & Magnolia"},
"5574": {"id": "MNLYN:3", "verbose": "Main & Lynn"},
"5576": {"id": "4THARY:6", "verbose": "4th & Armory"},
"5601": {"id": "RMNELLIS:4", "verbose": "Romine & Ellis"},
"5610": {"id": "1STWDSR:4", "verbose": "First & Windsor"},
"5612": {"id": "GRGPS:1", "verbose": "Personnel Services"},
"5614": {"id": "KBYPRKHVN:3", "verbose": "Kirby & Park Haven"},
"5616": {"id": "UICU:8", "verbose": "U of I Credit Union"},
"5622": {"id": "NEILBRWS:8", "verbose": "Neil & Burwash"},
"5627": {"id": "PSPCTPNR:4", "verbose": "Prospect & Pioneer"},
"5631": {"id": "CHHLLKVW:7", "verbose": "Cherry Hills & Lakeview"},
"5633": {"id": "MLKNDVRBRK:2", "verbose": "Mullikin & Doverbrook"},
"5634": {"id": "NEILBELL:2", "verbose": "Neil & Bellefontaine"},
"5640": {"id": "JOHNPINE:3", "verbose": "John & Pine"},
"5643": {"id": "GWNCHCH:4", "verbose": "Goodwin & Church"},
"5645": {"id": "MKTPAUL:4", "verbose": "Market & Paul"},
"5647": {"id": "SPFLDRSL:3", "verbose": "Springfield & Russell"},
"5651": {"id": "PDYKAM:2", "verbose": "Krannert Art Museum"},
"5653": {"id": "MATSSTNGT:4", "verbose": "Mattis & Stonegate"},
"5657": {"id": "MKTBRAD:5", "verbose": "Market & Bradley"},
"5663": {"id": "MKTPLCCD:3", "verbose": "Market Place & Convenience"},
"5664": {"id": "JOHNGLDVW:2", "verbose": "John & Goldenview"},
"5665": {"id": "GLNHRTN:4", "verbose": "Galen & Harrington"},
"5667": {"id": "ADRSNCO:4", "verbose": "Anderson & Colorado"},
"5671": {"id": "KERCNHM:6", "verbose": "Kerr & Cunningham"},
"5673": {"id": "JOHNTLCV:3", "verbose": "John & Teal Cove"},
"5677": {"id": "1STSPFLD:4", "verbose": "First & Springfield"},
"5701": {"id": "SPGHLGLNHL:4", "verbose": "Springhill & Glenhill"},
"5705": {"id": "MATS:1", "verbose": "Mattis at Schnucks"},
"5712": {"id": "LNHSTPKLN:4", "verbose": "Lyndhurst & Park Ln"},
"5714": {"id": "PARACE:4", "verbose": "Penn & Race"},
"5721": {"id": "CHCHGRFLD:1", "verbose": "Church & Garfield"},
"5722": {"id": "WDSRCLV:2", "verbose": "Clark Lindsey Village"},
"5725": {"id": "PSPCTKBY:8", "verbose": "Prospect & Kirby"},
"5731": {"id": "LNHSTARBR1:4", "verbose": "Lyndhurst & Arbour"},
"5735": {"id": "BDWYCHPN:4", "verbose": "Broadway & Chapin"},
"5736": {"id": "FLJASCHER:3", "verbose": "Florida & James Cherry"},
"5742": {"id": "ANTMATS:8", "verbose": "Anthony & Mattis"},
"5743": {"id": "2NDUNI:5", "verbose": "Second & University"},
"5744": {"id": "PHILOPA:4", "verbose": "Philo & Pennsylvania"},
"5745": {"id": "MHRYPHILO:8", "verbose": "McHenry & Philo"},
"5747": {"id": "1STGRG:4", "verbose": "First & Gregory"},
"5753": {"id": "PSPCTMPL:4", "verbose": "Prospect & Maple"},
"5755": {"id": "MCRTRCT:4", "verbose": "MacArthur & MacArthur Ct."},
"5761": {"id": "FRVWBUSEY:3", "verbose": "Fairview & Busey"},
"5762": {"id": "ARC:2", "verbose": "ARC"},
"5764": {"id": "CNHMTPSN:4", "verbose": "Cunningham & Thompson"},
"5774": {"id": "VINNV:4", "verbose": "Vine & Nevada"},
"5873": {"id": "PKMCCLGH:4", "verbose": "Park & McCullough"},
"5904": {"id": "BRADNEIL:3", "verbose": "Bradley & Neil"},
"6003": {"id": "LNCLNMI:4", "verbose": "Lincoln & Michigan"},
"6011": {"id": "CHHLCYPCK:4", "verbose": "Cherry Hills & Cypress Creek"},
"6012": {"id": "SMITH150:4", "verbose": "Smith & U.S. 150"},
"6014": {"id": "BRADWMBG:4", "verbose": "Bradley & Williamsburg"},
"6016": {"id": "RACEMTCLR:4", "verbose": "Race & Montclair"},
"6022": {"id": "LWNDLCENT:3", "verbose": "Lawndale & Centennial"},
"6023": {"id": "SPFLDCHI:3", "verbose": "Springfield & Chicago"},
"6025": {"id": "MATSBDMR:6", "verbose": "Mattis & Broadmoor"},
"6026": {"id": "1STHLY:4", "verbose": "First & Healey"},
"6033": {"id": "PDKELOTB:2", "verbose": "Winfield Village Lot B"},
"6035": {"id": "PHILOLRL:4", "verbose": "Philo & Laurel"},
"6051": {"id": "GWNMN:4", "verbose": "Goodwin & Main"},
"6052": {"id": "BRADCFD:8", "verbose": "Bradley & Country Fair Dr."},
"6055": {"id": "WSFLDSANG:4", "verbose": "Westfield & Sangamon"},
"6056": {"id": "ANTKANK:3", "verbose": "Anthony & Kankakee"},
"6062": {"id": "STEAVNDL:4", "verbose": "State & Avondale"},
"6063": {"id": "PSPCTKENT:4", "verbose": "Prospect & Kent"},
"6100": {"id": "VINBKWD:4", "verbose": "Vine & Burkwood Ct."},
"6103": {"id": "RACEIN:4", "verbose": "Race & Indiana"},
"6104": {"id": "MYFRGTOWN:4", "verbose": "Mayfair & Georgetown"},
"6111": {"id": "SWTCHGRSDFDL:2", "verbose": "Switchgrass & Daffodil"},
"6115": {"id": "PLAZA:4", "verbose": "Transit Plaza (SE Platform)"},
"6121": {"id": "STECDR:4", "verbose": "State & Cedar"},
"6123": {"id": "WSFLDLWNDL:4", "verbose": "Westfield & Lawndale"},
"6126": {"id": "CLTNDLMR:3", "verbose": "Clayton & Delmar"},
"6131": {"id": "CRSTWDCLTN:4", "verbose": "Crestwood & Clayton"},
"6132": {"id": "BRDWLKTCB:7", "verbose": "Boardwalk & Town Center"},
"6134": {"id": "SPFLDVNDRN:1", "verbose": "Springfield & VanDoren"},
"6135": {"id": "SPFLDMATS:3", "verbose": "Springfield & Mattis"},
"6140": {"id": "NEILANT:4", "verbose": "Neil & Anthony"},
"6141": {"id": "BDWYFRKLN:4", "verbose": "Broadway & Franklin"},
"6142": {"id": "LNHSTLNVCT:2", "verbose": "Lyndhurst & Lyndhurst Village Ct."},
"6143": {"id": "SLVRCTGRV:4", "verbose": "Silver & Cottage Grove"},
"6147": {"id": "MLKNVLA:4", "verbose": "Mullikin & Villa"},
"6151": {"id": "CTGRVGNWD:4", "verbose": "Cottage Grove & Glenwood Oaks"},
"6155": {"id": "PLAMCNLY:4", "verbose": "Paula & McKinley"},
"6161": {"id": "2NDCHCH:4", "verbose": "Second & Church"},
"6162": {"id": "HRISBLOM:3", "verbose": "Harris & Bloomington"},
"6163": {"id": "SMRNBVW:2", "verbose": "Smith & Rainbowview"},
"6165": {"id": "CCRGFVW:3", "verbose": "Country Club & Golfview"},
"6167": {"id": "VINFRLN:6", "verbose": "Vine & Fairlawn"},
"6170": {"id": "DNCNVYBK:4", "verbose": "Duncan & Valleybrook"},
"6173": {"id": "MNMKT:3", "verbose": "Main & Market"},
"6176": {"id": "WLNTWASH:8", "verbose": "Walnut & Washington"},
"6201": {"id": "MNDWY:8", "verbose": "Main & Dewey"},
"6211": {"id": "GRNELM:3", "verbose": "Green & Elm"},
"6212": {"id": "LNCLNSNST:2", "verbose": "Lincoln & Sunset"},
"6213": {"id": "UNIVCTR:3", "verbose": "University & Victor"},
"6216": {"id": "BRADGH:3", "verbose": "Bradley & Garden Hills"},
"6220": {"id": "PHILOBCLF:4", "verbose": "Philo & Briarcliff"},
"6222": {"id": "BDWYCCR:7", "verbose": "Broadway & Country Club"},
"6223": {"id": "SLYBKCRE:1", "verbose": "Slayback & Carrie"},
"6224": {"id": "CLMBARNDLF:1", "verbose": "Columbia & Randolph"},
"6226": {"id": "DDSNNV:4", "verbose": "Dodson & Nevada"},
"6231": {"id": "CE:9", "verbose": "Central High East"},
"6232": {"id": "BRADHGN:5", "verbose": "Bradley & Hagan"},
"6234": {"id": "WLMKNWD:4", "verbose": "William & Kenwood"},
"6235": {"id": "UNIDRPR:3", "verbose": "University & Draper"},
"6236": {"id": "1STARY:5", "verbose": "First & Armory"},
"6237": {"id": "DNCNSRA:4", "verbose": "Duncan & Sierra"},
"6242": {"id": "CHEMLS:1", "verbose": "Chemical & Life Sciences"},
"6246": {"id": "SMITHCRE:4", "verbose": "Smith & Carrie"},
"6250": {"id": "KBYGRNCFT:1", "verbose": "Kirby & Greencroft"},
"6257": {"id": "CHCHLYN:2", "verbose": "Church & Lynn"},
"6262": {"id": "UNIRNDLF:3", "verbose": "University & Randolph"},
"6263": {"id": "PLAZA:2", "verbose": "Transit Plaza (NE Platform)"},
"6265": {"id": "PLAGH:3", "verbose": "Paula & Garden Hills"},
"6272": {"id": "CTGRVCRWD:4", "verbose": "Cottage Grove & Crestwood"},
"6273": {"id": "WASHMCRTR:5", "verbose": "Washington & MacArthur"},
"6276": {"id": "BLOMMCNLY:7", "verbose": "Bloomington & McKinley"},
"6301": {"id": "MATSSHRDN:2", "verbose": "Mattis & Sheridan"},
"6306": {"id": "MNENIS:3", "verbose": "Main & Ennis"},
"6314": {"id": "NEILHSL:3", "verbose": "Neil & Hessel"},
"6315": {"id": "WNCHGLNK:4", "verbose": "Winchester & Glenoak"},
"6316": {"id": "FTHLRBT:4", "verbose": "Foothill & Robert"},
"6320": {"id": "STETRMNT:4", "verbose": "State & Tremont"},
"6321": {"id": "LNCLNPA:6", "verbose": "Lincoln & Pennsylvania"},
"6322": {"id": "GRNUBNA:3", "verbose": "Green & Urbana"},
"6324": {"id": "CTGRVCA:4", "verbose": "Cottage Grove & California"},
"6325": {"id": "GRNMCNLY:2", "verbose": "Green & McKinley"},
"6330": {"id": "MLKNCRSGT:2", "verbose": "Mullikin & Crossgate"},
"6332": {"id": "WLMCENT:3", "verbose": "William & Centennial"},
"6333": {"id": "KBYVYRD:3", "verbose": "Kirby & Valley Rd."},
"6334": {"id": "SSTNSMT:2", "verbose": "Susan Stone & Summit"},
"6335": {"id": "MLKNCPRRG:4", "verbose": "Mullikin & Copper Ridge"},
"6336": {"id": "JOHNHILND:3", "verbose": "John & Highland"},
"6341": {"id": "SLVRVWTR:3", "verbose": "Silver & Vawter"},
"6345": {"id": "VACC:1", "verbose": "Virginia & College Ct."},
"6346": {"id": "FRLNPTN:3", "verbose": "Fairlawn & Patton"},
"6347": {"id": "GLNSSX:8", "verbose": "Galen & Sussex"},
"6350": {"id": "HRISAL:4", "verbose": "Harris & Alabama"},
"6352": {"id": "FLLNCLN:6", "verbose": "Florida & Lincoln"},
"6353": {"id": "SPFLDDNCN:4", "verbose": "Springfield & Duncan"},
"6356": {"id": "WRTCLARK:4", "verbose": "Wright & Clark"},
"6357": {"id": "MNBRDY:7", "verbose": "Main & Brady"},
"6360": {"id": "DDSNWASH:5", "verbose": "Dodson & Washington"},
"6362": {"id": "RMNEADS:4", "verbose": "Romine & Eads"},
"6363": {"id": "STEMPL:4", "verbose": "State & Maple"},
"6365": {"id": "UNIWRT:8", "verbose": "University & Wright"},
"6367": {"id": "VINSCVL:4", "verbose": "Vine & Scovill"},
"6374": {"id": "MATSCAMP:4", "verbose": "Mattis & Camp"},
"6402": {"id": "WDSRBKSR:1", "verbose": "Windsor & Brookshire"},
"6412": {"id": "SPFLDAFRC:2", "verbose": "Armed Forces Recruiting"},
"6414": {"id": "FRLNGRNT:3", "verbose": "Fairlawn & Grant Pl."},
"6417": {"id": "WSFLDALTN:4", "verbose": "Westfield & Alton"},
"6422": {"id": "BRADWLS:3", "verbose": "Bradley & Willis"},
"6423": {"id": "GRNJNSN:3", "verbose": "Green & Johnson"},
"6424": {"id": "TRLSPHILO:6", "verbose": "Trails & Philo"},
"6425": {"id": "NEILWASH:4", "verbose": "Neil & Washington"},
"6431": {"id": "GRN2ND:3", "verbose": "Green & Second"},
"6432": {"id": "CHCHSTE:7", "verbose": "Church & State"},
"6434": {"id": "UNISBN:3", "verbose": "University & Sabin"},
"6437": {"id": "PNCRSTSTLY:2", "verbose": "Pinecrest & Staley"},
"6441": {"id": "VINPELL:4", "verbose": "Vine & Pell Cir."},
"6444": {"id": "BLOMHILND:3", "verbose": "Bloomington & Highland"},
"6445": {"id": "ALDI150:2", "verbose": "Aldi"},
"6446": {"id": "BLBOASWD:1", "verbose": "Balboa & Southwest Dr."},
"6447": {"id": "ODMIDN:4", "verbose": "Orchard Downs Mid-North"},
"6450": {"id": "VLRALPN:3", "verbose": "Valerie & Alpine"},
"6451": {"id": "IU:2", "verbose": "Illini Union"},
"6453": {"id": "WLMGLDVW:1", "verbose": "William & Goldenview"},
"6454": {"id": "DVRBLBOA:4", "verbose": "Dover & Balboa"},
"6455": {"id": "BDMRMCD:3", "verbose": "Broadmoor & McDonald"},
"6456": {"id": "GRNWRT:5", "verbose": "Green & Wright"},
"6462": {"id": "IT:2", "verbose": "Illinois Terminal (Platform B)"},
"6464": {"id": "SUNNYCREST:2", "verbose": "Sunnycrest"},
"6465": {"id": "SCWDIL:3", "verbose": "Scottswood & Illinois"},
"6466": {"id": "PDKWLOTG:2", "verbose": "Winfield Village Lot G"},
"6467": {"id": "STEHLY:4", "verbose": "State & Healey"},
"6474": {"id": "MERCFEDEX:3", "verbose": "Mercury at FedEx"},
"6503": {"id": "CHCHEDWN:1", "verbose": "Church & Edwin"},
"6506": {"id": "WDSRFNY:3", "verbose": "Windsor & Phinney"},
"6507": {"id": "HRISHRVRD:4", "verbose": "Harris & Harvard"},
"6510": {"id": "LNHSTBRWS:4", "verbose": "Lyndhurst & Burwash"},
"6512": {"id": "CHCHMATS:1", "verbose": "Church & Mattis"},
"6514": {"id": "LSG:1", "verbose": "Lincoln Square Garage"},
"6515": {"id": "PSPCTBAY:4", "verbose": "Prospect & Baytowne"},
"6516": {"id": "FLADAMS:3", "verbose": "Florida & Adams"},
"6521": {"id": "MATSCYPS:4", "verbose": "Mattis & Cypress"},
"6522": {"id": "JOHNECRKCT:3", "verbose": "John & English Creek Ct."},
"6524": {"id": "PHILOMFRD:4", "verbose": "Philo & Mumford"},
"6526": {"id": "ANTVP:1", "verbose": "Anthony Dr. at Value Place"},
"6531": {"id": "SPFLDRYLCT:1", "verbose": "Springfield & Royal Ct."},
"6532": {"id": "MKTV:6", "verbose": "Marketview at Marketview Center"},
"6535": {"id": "JOHNRGWAY:3", "verbose": "John & Ridgeway"},
"6541": {"id": "PDKWLOTK:1", "verbose": "Winfield Village Lot K"},
"6542": {"id": "ELMPK:3", "verbose": "Elm & Park"},
"6543": {"id": "CTGRVBRITN:4", "verbose": "Cottage Grove & Brighton"},
"6544": {"id": "WRTSTOTN:4", "verbose": "Wright & Stoughton"},
"6545": {"id": "JOHNFAIR:3", "verbose": "John & Fair"},
"6552": {"id": "PNCRSTPRTFLD:1", "verbose": "Pinecrest & Porterfield"},
"6554": {"id": "SSTNMYRA:2", "verbose": "Susan Stone & Myra Ridge"},
"6555": {"id": "MYNRDKBY:7", "verbose": "Maynard & Kirby"},
"6556": {"id": "CSQRKNCH:8", "verbose": "Country Squire & Kinch"},
"6561": {"id": "MNMPL:3", "verbose": "Main & Maple"},
"6563": {"id": "NEILSPFLD:4", "verbose": "Neil & Springfield"},
"6565": {"id": "MATSINT:2", "verbose": "Mattis & Interstate"},
"6566": {"id": "BNFLDPRVW:4", "verbose": "Brownfield & Prairieview"},
"6570": {"id": "WASHTIM:3", "verbose": "Washington & Timothy Tr."},
"6572": {"id": "WLMSTFRD:3", "verbose": "William & Stratford"},
"6575": {"id": "GWNPK:8", "verbose": "Goodwin & Park"},
"6601": {"id": "MLKNGRVCT:2", "verbose": "Mullikin & Graves Ct."},
"6603": {"id": "TCA:2", "verbose": "Town & Country Apts."},
"6610": {"id": "UIIA:1", "verbose": "Institute of Aviation"},
"6612": {"id": "FOXKLWD:4", "verbose": "Fox & Knollwood"},
"6613": {"id": "MNWBR:3", "verbose": "Main & Webber"},
"6614": {"id": "SPFLDBSY:3", "verbose": "Springfield & Busey"},
"6615": {"id": "BDWYCLD:4", "verbose": "Broadway & Crystal Lake"},
"6620": {"id": "CTSWIN:1", "verbose": "Curtis Rd. at Winfield Village"},
"6622": {"id": "GRGOAK:2", "verbose": "Gregory & Oak"},
"6626": {"id": "UNILRMN:5", "verbose": "University & Lierman"},
"6630": {"id": "CBLFDABDN:4", "verbose": "Cobblefield and Aberdeen"},
"6633": {"id": "PSPCTSHWD:2", "verbose": "Prospect & Sherwood Tr."},
"6634": {"id": "JOHNMCNLY:4", "verbose": "John & McKinley"},
"6635": {"id": "1STCHSTR:4", "verbose": "First & Chester"},
"6641": {"id": "RLNDDBNS:4", "verbose": "Roland & Dobbins"},
"6643": {"id": "RNDLFJOHN:8", "verbose": "Randolph & John"},
"6644": {"id": "WNCHBDMR:2", "verbose": "Winchester & Broadmoor"},
"6645": {"id": "RNDLFWASH:2", "verbose": "Randolph & Washington"},
"6652": {"id": "MERCAPLO:5", "verbose": "Mercury & Apollo"},
"6654": {"id": "SMROAK:5", "verbose": "St. Mary's & Oak"},
"6666": {"id": "NEILKNYN:4", "verbose": "Neil & Kenyon"},
"6673": {"id": "MKTWLACE:4", "verbose": "Market & Wallace"},
"6674": {"id": "CNHMOKLN:7", "verbose": "Cunningham & Oakland"},
"6675": {"id": "4THKBY:5", "verbose": "Fourth & Kirby"},
"6700": {"id": "SLYBKSMITH:1", "verbose": "Slayback & Smith"},
"6711": {"id": "WHT6TH:3", "verbose": "White & Sixth"},
"6726": {"id": "GRNBUSEY:3", "verbose": "Green & Busey"},
"6731": {"id": "PSL:2", "verbose": "Plant Sciences Lab"},
"6733": {"id": "PKNSRICH:3", "verbose": "Perkins & Richard"},
"6735": {"id": "4THPA:4", "verbose": "Fourth & Pennsylvania"},
"6741": {"id": "150UNI:8", "verbose": "U.S. 150 & University"},
"6751": {"id": "FLPLSNT:3", "verbose": "Florida & Pleasant"},
"6752": {"id": "FLHLCRST:3", "verbose": "Florida & Hillcrest"},
"6753": {"id": "MYRAAUTM:2", "verbose": "Myra Ridge & Autumn Ridge"},
"6764": {"id": "PKNSCROL:7", "verbose": "Perkins & Carroll"},
"6767": {"id": "CRNDODVR:8", "verbose": "Coronado & Dover"},
"7011": {"id": "CSQRCT:4", "verbose": "Country Squire Ct."},
"7024": {"id": "CFDSSI:2", "verbose": "Social Security"},
"7025": {"id": "HNTRASTN:3", "verbose": "Hunter & Austin"},
"7035": {"id": "RNDLFCHAS:2", "verbose": "Randolph & Charles"},
"7036": {"id": "FLPHILO:4", "verbose": "Florida & Philo"},
"7050": {"id": "JOHNCSTLTN:3", "verbose": "John & Castleton"},
"7097": {"id": "CLTNDNCN:4", "verbose": "Clayton & Duncan"},
"7123": {"id": "MYFROF:2", "verbose": "Mayfair & Old Farm"},
"7124": {"id": "HLFXMYNRD:4", "verbose": "Halifax & Maynard"},
"7133": {"id": "MKTUNI:9", "verbose": "Market & University"},
"7134": {"id": "WASHSCL:2", "verbose": "Washington School"},
"7137": {"id": "PHILOSCVL:2", "verbose": "Philo & Scovill"},
"7141": {"id": "PSPCTTRMNT:4", "verbose": "Prospect & Tremont"},
"7142": {"id": "LCNSRFTHL:3", "verbose": "Lincolnshire & Foothill"},
"7151": {"id": "MCNLYBRD:4", "verbose": "McKinley & Beardsley"},
"7155": {"id": "CHCH:2", "verbose": "Church St."},
"7160": {"id": "WDSRMYRA:9", "verbose": "Windsor & Myra"},
"7174": {"id": "PAGWN:1", "verbose": "Penn & Goodwin"},
"7175": {"id": "GRNPSPCT:3", "verbose": "Green & Prospect"},
"7201": {"id": "FLBUSEY:3", "verbose": "Florida & Busey"},
"7209": {"id": "CLTNBLRV:3", "verbose": "Clayton & Bellerieve"},
"7213": {"id": "WASHSMITH:3", "verbose": "Washington & Smith"},
"7216": {"id": "BDMRLSDED:3", "verbose": "Broadmoor & Lakeside"},
"7221": {"id": "CROLFD:3", "verbose": "Carrol Fire Department"},
"7226": {"id": "KBYDWSN:1", "verbose": "Kirby & Dawson"},
"7233": {"id": "RACEBLSS:4", "verbose": "Race & Bliss"},
"7234": {"id": "INDIGO:2", "verbose": "Indigo Place"},
"7243": {"id": "UNILAKE:3", "verbose": "University & Lake"},
"7244": {"id": "JOHNFRANK:3", "verbose": "John & Frank"},
"7253": {"id": "PSPCTERKA:4", "verbose": "Prospect & Eureka"},
"7255": {"id": "RACEGRN:2", "verbose": "Race & Green"},
"7256": {"id": "BLBOAPSPCT:6", "verbose": "Balboa & Prospect"},
"7267": {"id": "KBYMATS:7", "verbose": "Kirby & Mattis"},
"7270": {"id": "SWNDSWNC2:4", "verbose": "Sherwin & Sherwin Cir 2"},
"7275": {"id": "LAR:2", "verbose": "LAR"},
"7301": {"id": "MERCGEMCT:3", "verbose": "Mercury & Gemini"},
"7303": {"id": "LGGTBRDN:4", "verbose": "Leggett & Bardeen"},
"7306": {"id": "MYNDCVTRY:4", "verbose": "Maynard & Coventry"},
"7311": {"id": "SPFLDCFD:7", "verbose": "Springfield & Country Fair Dr."},
"7312": {"id": "GWNCLK:4", "verbose": "Goodwin & Clark"},
"7317": {"id": "ODSS:3", "verbose": "Orchard Downs South Shelter"},
"7322": {"id": "CRSTWDKTLYN:4", "verbose": "Crestwood & Katie Lynn"},
"7323": {"id": "PACARL:3", "verbose": "Penn & Carle"},
"7331": {"id": "MHRYLYN2:1", "verbose": "McHenry & Lynn St. #2"},
"7332": {"id": "WDSR:2", "verbose": "Windsor Rd."},
"7337": {"id": "LNCLNSMR:4", "verbose": "Lincoln & St. Marys"},
"7342": {"id": "DNCNSWOOD:4", "verbose": "Duncan & Southwood"},
"7344": {"id": "WASHLRMN:7", "verbose": "Washington & Lierman"},
"7345": {"id": "CLTNBLBLRV:1", "verbose": "Clayton and Bellerieve"},
"7346": {"id": "CCRDVSN:3", "verbose": "Country Club & Division"},
"7350": {"id": "MKTPLCNMKT:8", "verbose": "Mkt Plc North Ent. & Market"},
"7354": {"id": "PLAJEANNE:3", "verbose": "Paula & Jeanne"},
"7362": {"id": "GRNPRIE:3", "verbose": "Green & Prairie"},
"7365": {"id": "BDMRCRSNT:4", "verbose": "Broadmoor & Crescent"},
"7366": {"id": "TMGTWLWBD:4", "verbose": "Timbergate & Willow Bend"},
"7403": {"id": "RACEHLMS:4", "verbose": "Race & Holmes"},
"7411": {"id": "PLAZA", "verbose": "Transit Plaza"},
"7416": {"id": "WNDSRSTLY:3", "verbose": "Windsor & Staley"},
"7422": {"id": "PSPCTHILL:4", "verbose": "Prospect & Hill"},
"7423": {"id": "VINGRN:6", "verbose": "Vine & Green"},
"7424": {"id": "4THSMR:5", "verbose": "Fourth & St. Mary's"},
"7425": {"id": "TCBMRLND:3", "verbose": "Town Center & Moreland"},
"7430": {"id": "PHILOCO:5", "verbose": "Philo & Colorado"},
"7431": {"id": "DNCNRDGWD:4", "verbose": "Duncan & Ridgewood"},
"7441": {"id": "UNICLR:4", "verbose": "University & Coler"},
"7443": {"id": "BRADCRVR:3", "verbose": "Bradley & Carver"},
"7445": {"id": "LCNSR:1", "verbose": "St. Mathews"},
"7455": {"id": "VKINGS:1", "verbose": "Viking South"},
"7456": {"id": "FLLCLNWD:1", "verbose": "Florida & Lincolnwood"},
"7460": {"id": "ADRSNBKWD:4", "verbose": "Anderson & Burkwood"},
"7461": {"id": "CROLKER:4", "verbose": "Carroll & Kerr"},
"7464": {"id": "CRSTWDFLNC:4", "verbose": "Crestwood & Florence"},
"7471": {"id": "WNCHBKTRN:4", "verbose": "Winchester & Blackthorn"},
"7474": {"id": "MPLPKWLPK:2", "verbose": "Maplepark & Willowpark"},
"7503": {"id": "BRADMCNLY:4", "verbose": "Bradley & McKinley"},
"7505": {"id": "MCRTRCA:4", "verbose": "MacArthur & California"},
"7513": {"id": "KBYNEIL:8", "verbose": "Kirby & Neil"},
"7515": {"id": "FRVWHRVY:3", "verbose": "Fairview & Harvey"},
"7522": {"id": "WDSRSCTDL:3", "verbose": "Windsor & Scotsdale"},
"7524": {"id": "WDSRMYPK:3", "verbose": "Windsor & Morrissey Park"},
"7526": {"id": "WRDKER:3", "verbose": "Ward & Kerr"},
"7527": {"id": "PLAJOANE:3", "verbose": "Paula & Joanne"},
"7533": {"id": "CHCHNEIL:3", "verbose": "Church & Neil"},
"7534": {"id": "IT:1", "verbose": "Illinois Terminal (Platform A)"},
"7542": {"id": "ANTGOODWILL:2", "verbose": "Anthony Dr. at Goodwill"},
"7543": {"id": "CMBLAZTEC:4", "verbose": "Campbell & Aztec"},
"7551": {"id": "JPN:4", "verbose": "Japan House"},
"7555": {"id": "5THCHAL:1", "verbose": "5th & Chalmers"},
"7561": {"id": "BRTTRLKNTNKNL:1", "verbose": "Brittany Trail & Kensington Knoll"},
"7562": {"id": "BDWYWTR:4", "verbose": "Broadway & Water"},
"7566": {"id": "CHCHDRPR:1", "verbose": "Church & Draper"},
"7567": {"id": "RNDLFVIN:8", "verbose": "Randolph & Vine"},
"7570": {"id": "CLTNHV:4", "verbose": "Clayton and High View"},
"7573": {"id": "CHHLCTS:5", "verbose": "Cherry Hills & Curtis"},
"7574": {"id": "WLMOKCRST:3", "verbose": "William & Oakcrest"},
"7588": {"id": "RACEMUMFRD:4", "verbose": "Race & Mumford"},
"7615": {"id": "WSFLDWLM:1", "verbose": "Westfield & William"},
"7620": {"id": "JOHNPRRE:3", "verbose": "John & Prairie"},
"7622": {"id": "MKTMERC:2", "verbose": "Market & Mercury"},
"7623": {"id": "SGRCFD:4", "verbose": "Springer & Country Fair Dr."},
"7633": {"id": "PKNSCHKE:3", "verbose": "Perkins & Cherokee"},
"7634": {"id": "CMBLRLND:4", "verbose": "Campbell & Roland"},
"7641": {"id": "PAWILEY:3", "verbose": "Penn & Wiley"},
"7642": {"id": "GRNLYNN:3", "verbose": "Green & Lynn"},
"7644": {"id": "CRSGTCHWK:3", "verbose": "Crossgate & Charwick"},
"7647": {"id": "DVNNL:1", "verbose": "Devonshire and Noel"},
"7653": {"id": "WNCHBKHVN:4", "verbose": "Winchester & Brookhaven"},
"7654": {"id": "CHCHWLS:1", "verbose": "Church & Willis"},
"7665": {"id": "SWCF:4", "verbose": "Springfield & Southwest Country Fair"},
"7703": {"id": "JOHNPSPCT:3", "verbose": "John & Prospect"},
"7709": {"id": "CBLFLDEGLWD:4", "verbose": "Cobblefield and Engelwood"},
"7732": {"id": "SPFLDBRCH:3", "verbose": "Springfield & Birch"},
"7741": {"id": "WLMMPLPK:3", "verbose": "William & Maplepark"},
"7751": {"id": "WNCHBRCH:4", "verbose": "Winchester & Branch"},
"7771": {"id": "PLACYNTHA:3", "verbose": "Paula & Cynthia"},
"7907": {"id": "OD#4:2", "verbose": "Orchard Downs #4"},
"7918": {"id": "MIGRNRDG:3", "verbose": "Michigan & Green Ridge"},
"7953": {"id": "CTSUS45:1", "verbose": "Curtis & U.S.45"},
"8030": {"id": "GRNHGHLND:1", "verbose": "Green & Highland"},
"8078": {"id": "CENTRAL:9", "verbose": "Central High"},
"8112": {"id": "FLLNCLWD:3", "verbose": "Florida & Lincolnwood"},
"8268": {"id": "WINDPT:4", "verbose": "Windward Point"},
"8302": {"id": "SPFLDMATS:9", "verbose": "Springfield & Mattis"},
"8341": {"id": "CVTRYMYNRD:2", "verbose": "Coventry & Maynard"},
"8386": {"id": "WINDATMWD:4", "verbose": "Windward and Autumnwood"},
"8449": {"id": "ELMVIN:8", "verbose": "Elm & Vine"},
"8595": {"id": "VALDUN:3", "verbose": "Valerie Dr. and Duncan"},
"8831": {"id": "GWNOR:4", "verbose": "Goodwin & Oregon"},
"9105": {"id": "SSXWIND:3", "verbose": "Sussex and Windward"},
"9108": {"id": "FRHLSTLY:1", "verbose": "Farhills & Staley"},
"9378": {"id": "WNDVRSMRVW:4", "verbose": "Wendover & Summerview"},
"9443": {"id": "WNDVRWDSPG:4", "verbose": "Wendover & Woodspring"},
"9467": {"id": "CBLFLDBLML:4", "verbose": "Cobblefield and Balmoral"},
"9564": {"id": "FLBRMD:3", "verbose": "Florida & Bermuda"},
"9614": {"id": "SMRSGRWTCHGRS:2", "verbose": "Summersage & Switchgrass"},
"9616": {"id": "WNDVRCTRYBND:4", "verbose": "Valleybrook & Country Bend"},
"9956": {"id": "MYFRLCLNSH:4", "verbose": "Mayfair & Lincolnshire"},
"9974": {"id": "RMNBRRD:4", "verbose": "Romine & Beardsley"}
};
